#ifndef MICRO_SCOPE_UI_GENERATED_HLSLI
#define MICRO_SCOPE_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: fdc53c454b9ea33975cf928756ac407dbb997ad15cc8b12625b7b14312121875
static const uint UI_CONTROL_COUNT = 1u;
static const uint UI_LABEL_COUNT = 1u;
static const uint4 UI_MANIFEST_HASH = uint4(0xfdc53c45u, 0x4b9ea339u, 0x75cf9287u, 0x56ac407du);

static const uint UI_INDEX_SPAN = 0u;
static const float4 UI_RECT_SPAN = float4(0.65, 0.79, 0.955, 0.93);

static const uint UI_LABEL_CONTROL_SPAN = 0u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 4;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[4] = { 83, 112, 97, 110 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
