#ifndef PAINT_CANVAS_UI_GENERATED_HLSLI
#define PAINT_CANVAS_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: f0720c0495a840bdd58381834cf7fedfba2708acf83e7a17897f1de9063d44d2
static const uint UI_CONTROL_COUNT = 0u;
static const uint UI_LABEL_COUNT = 3u;
static const uint4 UI_MANIFEST_HASH = uint4(0xf0720c04u, 0x95a840bdu, 0xd5838183u, 0x4cf7fedfu);


static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_NAV = 1u;
static const uint UI_LABEL_CLEAR = 2u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 12;
    if (labelId == 1u) return 77;
    if (labelId == 2u) return 5;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[12] = { 80, 65, 73, 78, 84, 32, 67, 65, 78, 86, 65, 83 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[77] = { 76, 77, 66, 32, 80, 65, 73, 78, 84, 32, 32, 47, 32, 32, 77, 77, 66, 32, 80, 65, 78, 32, 32, 47, 32, 32, 87, 72, 69, 69, 76, 32, 90, 79, 79, 77, 32, 32, 47, 32, 32, 65, 76, 84, 32, 87, 72, 69, 69, 76, 32, 83, 73, 90, 69, 32, 32, 47, 32, 32, 70, 32, 70, 73, 84, 32, 32, 47, 32, 32, 88, 32, 67, 76, 69, 65, 82 };
        return characterIndex >= 0 && characterIndex < 77 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[5] = { 67, 76, 69, 65, 82 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
