#ifndef SCIENTIFIC_SEED_LAB_UI_GENERATED_HLSLI
#define SCIENTIFIC_SEED_LAB_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 443a7b066f05efe2a50ada4e906d91675b775be4f8db6c4e658b6c8923bd0975
static const uint UI_CONTROL_COUNT = 4u;
static const uint UI_LABEL_COUNT = 10u;
static const uint4 UI_MANIFEST_HASH = uint4(0x443a7b06u, 0x6f05efe2u, 0xa50ada4eu, 0x906d9167u);

static const uint UI_INDEX_SEED = 0u;
static const float4 UI_RECT_SEED = float4(0.6, 0.027, 0.68, 0.096);
static const uint UI_INDEX_VORTEX = 1u;
static const float4 UI_RECT_VORTEX = float4(0.69, 0.027, 0.79, 0.096);
static const uint UI_INDEX_ERASE = 2u;
static const float4 UI_RECT_ERASE = float4(0.8, 0.027, 0.885, 0.096);
static const uint UI_INDEX_CLEAR = 3u;
static const float4 UI_RECT_CLEAR = float4(0.895, 0.027, 0.98, 0.096);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_SEED = 1u;
static const uint UI_LABEL_VORTEX = 2u;
static const uint UI_LABEL_ERASE = 3u;
static const uint UI_LABEL_CLEAR = 4u;
static const uint UI_LABEL_ACTIVE = 5u;
static const uint UI_LABEL_CONTROL_SEED = 6u;
static const uint UI_LABEL_CONTROL_VORTEX = 7u;
static const uint UI_LABEL_CONTROL_ERASE = 8u;
static const uint UI_LABEL_CONTROL_CLEAR = 9u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 19;
    if (labelId == 1u) return 4;
    if (labelId == 2u) return 6;
    if (labelId == 3u) return 5;
    if (labelId == 4u) return 5;
    if (labelId == 5u) return 6;
    if (labelId == 6u) return 9;
    if (labelId == 7u) return 11;
    if (labelId == 8u) return 10;
    if (labelId == 9u) return 9;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[19] = { 83, 67, 73, 69, 78, 84, 73, 70, 73, 67, 32, 83, 69, 69, 68, 32, 76, 65, 66 };
        return characterIndex >= 0 && characterIndex < 19 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[4] = { 83, 69, 69, 68 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[6] = { 86, 79, 82, 84, 69, 88 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[5] = { 69, 82, 65, 83, 69 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[5] = { 67, 76, 69, 65, 82 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[6] = { 65, 67, 84, 73, 86, 69 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[9] = { 83, 101, 101, 100, 32, 84, 111, 111, 108 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[11] = { 86, 111, 114, 116, 101, 120, 32, 84, 111, 111, 108 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[10] = { 69, 114, 97, 115, 101, 32, 84, 111, 111, 108 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[9] = { 67, 108, 101, 97, 114, 32, 65, 108, 108 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
