#ifndef SCIENTIFIC_UI_STYLE_TUNER_UI_GENERATED_HLSLI
#define SCIENTIFIC_UI_STYLE_TUNER_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 730da47ec0ad60a738f05dc44c4351add877ebd7bfd9fbfa406369eccea1013c
static const uint UI_CONTROL_COUNT = 13u;
static const uint UI_LABEL_COUNT = 22u;
static const uint4 UI_MANIFEST_HASH = uint4(0x730da47eu, 0xc0ad60a7u, 0x38f05dc4u, 0x4c4351adu);

static const uint UI_INDEX_TITLE_SCALE = 0u;
static const float4 UI_RECT_TITLE_SCALE = float4(0.22, 0.145, 0.402, 0.195);
static const uint UI_INDEX_TITLE_WEIGHT = 1u;
static const float4 UI_RECT_TITLE_WEIGHT = float4(0.22, 0.205, 0.402, 0.255);
static const uint UI_INDEX_TITLE_TRACKING = 2u;
static const float4 UI_RECT_TITLE_TRACKING = float4(0.22, 0.265, 0.402, 0.315);
static const uint UI_INDEX_SECTION_SCALE = 3u;
static const float4 UI_RECT_SECTION_SCALE = float4(0.22, 0.335, 0.402, 0.385);
static const uint UI_INDEX_SECTION_WEIGHT = 4u;
static const float4 UI_RECT_SECTION_WEIGHT = float4(0.22, 0.395, 0.402, 0.445);
static const uint UI_INDEX_SECTION_TRACKING = 5u;
static const float4 UI_RECT_SECTION_TRACKING = float4(0.22, 0.455, 0.402, 0.505);
static const uint UI_INDEX_BODY_SCALE = 6u;
static const float4 UI_RECT_BODY_SCALE = float4(0.22, 0.525, 0.402, 0.575);
static const uint UI_INDEX_BODY_WEIGHT = 7u;
static const float4 UI_RECT_BODY_WEIGHT = float4(0.22, 0.585, 0.402, 0.635);
static const uint UI_INDEX_BODY_TRACKING = 8u;
static const float4 UI_RECT_BODY_TRACKING = float4(0.22, 0.645, 0.402, 0.695);
static const uint UI_INDEX_OUTER_PADDING = 9u;
static const float4 UI_RECT_OUTER_PADDING = float4(0.22, 0.715, 0.402, 0.765);
static const uint UI_INDEX_SECTION_GAP = 10u;
static const float4 UI_RECT_SECTION_GAP = float4(0.22, 0.775, 0.402, 0.825);
static const uint UI_INDEX_CONTROL_HEIGHT = 11u;
static const float4 UI_RECT_CONTROL_HEIGHT = float4(0.22, 0.835, 0.402, 0.885);
static const uint UI_INDEX_CONTROL_GAP = 12u;
static const float4 UI_RECT_CONTROL_GAP = float4(0.22, 0.895, 0.402, 0.945);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_INSTRUCTION = 1u;
static const uint UI_LABEL_PREVIEW_TITLE = 2u;
static const uint UI_LABEL_PREVIEW_SECTION = 3u;
static const uint UI_LABEL_PREVIEW_BODY = 4u;
static const uint UI_LABEL_PREVIEW_DETAIL = 5u;
static const uint UI_LABEL_PREVIEW_SLIDER = 6u;
static const uint UI_LABEL_PREVIEW_ACTION = 7u;
static const uint UI_LABEL_PREVIEW_TOGGLE = 8u;
static const uint UI_LABEL_CONTROL_TITLE_SCALE = 9u;
static const uint UI_LABEL_CONTROL_TITLE_WEIGHT = 10u;
static const uint UI_LABEL_CONTROL_TITLE_TRACKING = 11u;
static const uint UI_LABEL_CONTROL_SECTION_SCALE = 12u;
static const uint UI_LABEL_CONTROL_SECTION_WEIGHT = 13u;
static const uint UI_LABEL_CONTROL_SECTION_TRACKING = 14u;
static const uint UI_LABEL_CONTROL_BODY_SCALE = 15u;
static const uint UI_LABEL_CONTROL_BODY_WEIGHT = 16u;
static const uint UI_LABEL_CONTROL_BODY_TRACKING = 17u;
static const uint UI_LABEL_CONTROL_OUTER_PADDING = 18u;
static const uint UI_LABEL_CONTROL_SECTION_GAP = 19u;
static const uint UI_LABEL_CONTROL_CONTROL_HEIGHT = 20u;
static const uint UI_LABEL_CONTROL_CONTROL_GAP = 21u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 14;
    if (labelId == 1u) return 23;
    if (labelId == 2u) return 23;
    if (labelId == 3u) return 17;
    if (labelId == 4u) return 36;
    if (labelId == 5u) return 39;
    if (labelId == 6u) return 12;
    if (labelId == 7u) return 19;
    if (labelId == 8u) return 15;
    if (labelId == 9u) return 11;
    if (labelId == 10u) return 12;
    if (labelId == 11u) return 14;
    if (labelId == 12u) return 13;
    if (labelId == 13u) return 14;
    if (labelId == 14u) return 16;
    if (labelId == 15u) return 10;
    if (labelId == 16u) return 11;
    if (labelId == 17u) return 13;
    if (labelId == 18u) return 13;
    if (labelId == 19u) return 11;
    if (labelId == 20u) return 14;
    if (labelId == 21u) return 11;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[14] = { 85, 73, 32, 83, 84, 89, 76, 69, 32, 84, 85, 78, 69, 82 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[23] = { 84, 85, 78, 69, 32, 76, 69, 70, 84, 44, 32, 82, 69, 86, 73, 69, 87, 32, 82, 73, 71, 72, 84 };
        return characterIndex >= 0 && characterIndex < 23 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[23] = { 83, 67, 73, 69, 78, 84, 73, 70, 73, 67, 32, 67, 79, 78, 84, 82, 79, 76, 32, 68, 69, 67, 75 };
        return characterIndex >= 0 && characterIndex < 23 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[17] = { 83, 73, 71, 78, 65, 76, 32, 80, 65, 82, 65, 77, 69, 84, 69, 82, 83 };
        return characterIndex >= 0 && characterIndex < 17 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[36] = { 80, 114, 105, 109, 97, 114, 121, 32, 99, 111, 110, 116, 114, 111, 108, 115, 32, 117, 115, 101, 32, 116, 104, 101, 32, 98, 111, 100, 121, 32, 115, 116, 121, 108, 101, 46 };
        return characterIndex >= 0 && characterIndex < 36 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[39] = { 83, 101, 99, 111, 110, 100, 97, 114, 121, 32, 114, 101, 97, 100, 111, 117, 116, 115, 32, 117, 115, 101, 32, 109, 117, 116, 101, 100, 32, 98, 111, 100, 121, 32, 116, 101, 120, 116, 46 };
        return characterIndex >= 0 && characterIndex < 39 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[12] = { 83, 73, 71, 78, 65, 76, 32, 76, 69, 86, 69, 76 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[19] = { 65, 80, 80, 76, 89, 32, 67, 79, 78, 70, 73, 71, 85, 82, 65, 84, 73, 79, 78 };
        return characterIndex >= 0 && characterIndex < 19 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[15] = { 77, 79, 78, 73, 84, 79, 82, 32, 69, 78, 65, 66, 76, 69, 68 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[11] = { 84, 105, 116, 108, 101, 32, 83, 99, 97, 108, 101 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[12] = { 84, 105, 116, 108, 101, 32, 87, 101, 105, 103, 104, 116 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[14] = { 84, 105, 116, 108, 101, 32, 84, 114, 97, 99, 107, 105, 110, 103 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    if (labelId == 12u) {
        int codes[13] = { 83, 101, 99, 116, 105, 111, 110, 32, 83, 99, 97, 108, 101 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 13u) {
        int codes[14] = { 83, 101, 99, 116, 105, 111, 110, 32, 87, 101, 105, 103, 104, 116 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    if (labelId == 14u) {
        int codes[16] = { 83, 101, 99, 116, 105, 111, 110, 32, 84, 114, 97, 99, 107, 105, 110, 103 };
        return characterIndex >= 0 && characterIndex < 16 ? codes[characterIndex] : 32;
    }
    if (labelId == 15u) {
        int codes[10] = { 66, 111, 100, 121, 32, 83, 99, 97, 108, 101 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 16u) {
        int codes[11] = { 66, 111, 100, 121, 32, 87, 101, 105, 103, 104, 116 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 17u) {
        int codes[13] = { 66, 111, 100, 121, 32, 84, 114, 97, 99, 107, 105, 110, 103 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 18u) {
        int codes[13] = { 79, 117, 116, 101, 114, 32, 80, 97, 100, 100, 105, 110, 103 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 19u) {
        int codes[11] = { 83, 101, 99, 116, 105, 111, 110, 32, 71, 97, 112 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 20u) {
        int codes[14] = { 67, 111, 110, 116, 114, 111, 108, 32, 72, 101, 105, 103, 104, 116 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    if (labelId == 21u) {
        int codes[11] = { 67, 111, 110, 116, 114, 111, 108, 32, 71, 97, 112 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
