#ifndef SCIENTIFIC_UI_KIT_GALLERY_UI_GENERATED_HLSLI
#define SCIENTIFIC_UI_KIT_GALLERY_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 84e1d0b4d35aaf1dd9af8b07d111c6f9d13304a42c4051197ea9755d904a3a0c
static const uint UI_CONTROL_COUNT = 4u;
static const uint UI_LABEL_COUNT = 11u;
static const uint4 UI_MANIFEST_HASH = uint4(0x84e1d0b4u, 0xd35aaf1du, 0xd9af8b07u, 0xd111c6f9u);

static const uint UI_INDEX_SLIDER = 0u;
static const float4 UI_RECT_SLIDER = float4(0.075, 0.237, 0.448, 0.319);
static const uint UI_INDEX_PULSE = 1u;
static const float4 UI_RECT_PULSE = float4(0.542, 0.237, 0.702, 0.319);
static const uint UI_INDEX_TOGGLE = 2u;
static const float4 UI_RECT_TOGGLE = float4(0.773, 0.237, 0.923, 0.319);
static const uint UI_INDEX_PAD = 3u;
static const float4 UI_RECT_PAD = float4(0.167, 0.441, 0.833, 0.811);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_CONTROLS = 1u;
static const uint UI_LABEL_LAYOUT = 2u;
static const uint UI_LABEL_IDLE = 3u;
static const uint UI_LABEL_ACTIVE = 4u;
static const uint UI_LABEL_SELECTED = 5u;
static const uint UI_LABEL_DISABLED = 6u;
static const uint UI_LABEL_CONTROL_SLIDER = 7u;
static const uint UI_LABEL_CONTROL_PULSE = 8u;
static const uint UI_LABEL_CONTROL_TOGGLE = 9u;
static const uint UI_LABEL_CONTROL_PAD = 10u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 24;
    if (labelId == 1u) return 8;
    if (labelId == 2u) return 19;
    if (labelId == 3u) return 4;
    if (labelId == 4u) return 6;
    if (labelId == 5u) return 8;
    if (labelId == 6u) return 15;
    if (labelId == 7u) return 17;
    if (labelId == 8u) return 12;
    if (labelId == 9u) return 13;
    if (labelId == 10u) return 17;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[24] = { 83, 67, 73, 69, 78, 84, 73, 70, 73, 67, 32, 85, 73, 32, 70, 79, 85, 78, 68, 65, 84, 73, 79, 78 };
        return characterIndex >= 0 && characterIndex < 24 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[8] = { 67, 79, 78, 84, 82, 79, 76, 83 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[19] = { 76, 65, 89, 79, 85, 84, 32, 65, 78, 68, 32, 82, 69, 65, 68, 79, 85, 84, 83 };
        return characterIndex >= 0 && characterIndex < 19 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[4] = { 73, 68, 76, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[6] = { 65, 67, 84, 73, 86, 69 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[8] = { 83, 69, 76, 69, 67, 84, 69, 68 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[15] = { 68, 73, 83, 65, 66, 76, 69, 68, 32, 86, 73, 83, 85, 65, 76 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[17] = { 83, 99, 105, 101, 110, 116, 105, 102, 105, 99, 32, 83, 108, 105, 100, 101, 114 };
        return characterIndex >= 0 && characterIndex < 17 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[12] = { 80, 117, 108, 115, 101, 32, 66, 117, 116, 116, 111, 110 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[13] = { 69, 110, 97, 98, 108, 101, 32, 84, 111, 103, 103, 108, 101 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[17] = { 83, 99, 105, 101, 110, 116, 105, 102, 105, 99, 32, 88, 89, 32, 80, 97, 100 };
        return characterIndex >= 0 && characterIndex < 17 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
