// Generated by tools/phage_labels.py. Edit the generator, not this file.
#ifndef PH_LABELS_HLSLI
#define PH_LABELS_HLSLI
static const uint PH_LBL_CH[142]={80,72,65,71,69,32,47,32,65,82,69,78,65,80,76,65,78,76,79,78,71,32,83,69,67,84,73,79,78,65,85,68,73,69,78,67,69,80,69,79,80,76,69,72,65,76,76,77,82,79,79,70,32,67,76,69,65,82,65,78,67,69,32,65,84,32,75,73,78,69,84,73,67,32,77,65,88,75,73,78,69,84,73,67,32,77,65,88,66,65,82,83,32,76,73,84,83,84,65,71,69,88,82,79,79,70,32,83,84,69,69,76,67,65,80,83,73,68,32,84,79,80,32,65,84,32,82,69,83,84,84,79,79,32,76,79,87,79,70,32,57,54};
static const uint2 PH_LBL_RANGE[16]={uint2(0,13),uint2(13,4),uint2(17,12),uint2(29,8),uint2(37,6),uint2(43,4),uint2(47,1),uint2(48,29),uint2(77,11),uint2(88,8),uint2(96,5),uint2(101,1),uint2(102,10),uint2(112,18),uint2(130,7),uint2(137,5)};
float phLabelWidth(uint id,float s){return (float)PH_LBL_RANGE[id].y*SUI3_ADVANCE*s;}
float phLabel(float2 P,float2 anchor,float s,uint id){
 uint2 r=PH_LBL_RANGE[id];if(sui3RunMiss(P,anchor,s,(int)r.y))return 0;
 int k=(int)floor((P.x-anchor.x)/(SUI3_ADVANCE*s));if(k<0||k>=(int)r.y)return 0;
 float cov=sui3Glyph(P,anchor+float2((float)k*SUI3_ADVANCE*s,0),s,(int)PH_LBL_CH[r.x+(uint)k]);
 if(k>0)cov=max(cov,sui3Glyph(P,anchor+float2((float)(k-1)*SUI3_ADVANCE*s,0),s,(int)PH_LBL_CH[r.x+(uint)k-1]));
 return cov;}
#endif
