#ifndef MICRO_SEQUENCER_UI_GENERATED_HLSLI
#define MICRO_SEQUENCER_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: f4862fdcfcb02a14199f46c58623fb1faf2202bc81b0ee66fff8e992b6aeb1f4
static const uint UI_CONTROL_COUNT = 9u;
static const uint UI_LABEL_COUNT = 9u;
static const uint4 UI_MANIFEST_HASH = uint4(0xf4862fdcu, 0xfcb02a14u, 0x199f46c5u, 0x8623fb1fu);

static const uint UI_INDEX_RATE = 0u;
static const float4 UI_RECT_RATE = float4(0.555, 0.15, 0.955, 0.325);
static const uint UI_INDEX_STEP_1 = 1u;
static const float4 UI_RECT_STEP_1 = float4(0.045, 0.47, 0.145, 0.88);
static const uint UI_INDEX_STEP_2 = 2u;
static const float4 UI_RECT_STEP_2 = float4(0.159, 0.47, 0.259, 0.88);
static const uint UI_INDEX_STEP_3 = 3u;
static const float4 UI_RECT_STEP_3 = float4(0.273, 0.47, 0.373, 0.88);
static const uint UI_INDEX_STEP_4 = 4u;
static const float4 UI_RECT_STEP_4 = float4(0.387, 0.47, 0.487, 0.88);
static const uint UI_INDEX_STEP_5 = 5u;
static const float4 UI_RECT_STEP_5 = float4(0.501, 0.47, 0.601, 0.88);
static const uint UI_INDEX_STEP_6 = 6u;
static const float4 UI_RECT_STEP_6 = float4(0.615, 0.47, 0.715, 0.88);
static const uint UI_INDEX_STEP_7 = 7u;
static const float4 UI_RECT_STEP_7 = float4(0.729, 0.47, 0.829, 0.88);
static const uint UI_INDEX_STEP_8 = 8u;
static const float4 UI_RECT_STEP_8 = float4(0.843, 0.47, 0.943, 0.88);

static const uint UI_LABEL_CONTROL_RATE = 0u;
static const uint UI_LABEL_CONTROL_STEP_1 = 1u;
static const uint UI_LABEL_CONTROL_STEP_2 = 2u;
static const uint UI_LABEL_CONTROL_STEP_3 = 3u;
static const uint UI_LABEL_CONTROL_STEP_4 = 4u;
static const uint UI_LABEL_CONTROL_STEP_5 = 5u;
static const uint UI_LABEL_CONTROL_STEP_6 = 6u;
static const uint UI_LABEL_CONTROL_STEP_7 = 7u;
static const uint UI_LABEL_CONTROL_STEP_8 = 8u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 4;
    if (labelId == 1u) return 6;
    if (labelId == 2u) return 6;
    if (labelId == 3u) return 6;
    if (labelId == 4u) return 6;
    if (labelId == 5u) return 6;
    if (labelId == 6u) return 6;
    if (labelId == 7u) return 6;
    if (labelId == 8u) return 6;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[4] = { 82, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[6] = { 83, 116, 101, 112, 32, 49 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[6] = { 83, 116, 101, 112, 32, 50 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[6] = { 83, 116, 101, 112, 32, 51 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[6] = { 83, 116, 101, 112, 32, 52 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[6] = { 83, 116, 101, 112, 32, 53 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[6] = { 83, 116, 101, 112, 32, 54 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[6] = { 83, 116, 101, 112, 32, 55 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[6] = { 83, 116, 101, 112, 32, 56 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
