#ifndef INTERACTIVE_FACADE_COMPOSER_UI_GENERATED_HLSLI
#define INTERACTIVE_FACADE_COMPOSER_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 599f1c5e4d4464b572c9a1fa3fc85c62a8a2bf50b53e335f3632528c18132c94
static const uint UI_CONTROL_COUNT = 2u;
static const uint UI_LABEL_COUNT = 8u;
static const uint4 UI_MANIFEST_HASH = uint4(0x599f1c5eu, 0x4d4464b5u, 0x72c9a1fau, 0x3fc85c62u);

static const uint UI_INDEX_RESET = 0u;
static const float4 UI_RECT_RESET = float4(0.79, 0.032, 0.875, 0.078);
static const uint UI_INDEX_RESET_ALL = 1u;
static const float4 UI_RECT_RESET_ALL = float4(0.882, 0.032, 0.97, 0.078);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_RHYTHM = 1u;
static const uint UI_LABEL_FEATURE = 2u;
static const uint UI_LABEL_ELEVATION = 3u;
static const uint UI_LABEL_RESET = 4u;
static const uint UI_LABEL_RESET_ALL = 5u;
static const uint UI_LABEL_CONTROL_RESET = 6u;
static const uint UI_LABEL_CONTROL_RESET_ALL = 7u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 15;
    if (labelId == 1u) return 6;
    if (labelId == 2u) return 7;
    if (labelId == 3u) return 35;
    if (labelId == 4u) return 3;
    if (labelId == 5u) return 7;
    if (labelId == 6u) return 14;
    if (labelId == 7u) return 9;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[15] = { 70, 65, 67, 65, 68, 69, 32, 67, 79, 77, 80, 79, 83, 69, 82 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[6] = { 82, 72, 89, 84, 72, 77 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[7] = { 70, 69, 65, 84, 85, 82, 69 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[35] = { 76, 73, 86, 69, 32, 69, 76, 69, 86, 65, 84, 73, 79, 78, 32, 47, 32, 83, 84, 82, 85, 67, 84, 85, 82, 65, 76, 32, 87, 73, 78, 68, 79, 87, 83 };
        return characterIndex >= 0 && characterIndex < 35 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[3] = { 82, 83, 84 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[7] = { 82, 83, 84, 32, 65, 76, 76 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[14] = { 82, 101, 115, 101, 116, 32, 83, 101, 108, 101, 99, 116, 101, 100 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[9] = { 82, 101, 115, 101, 116, 32, 65, 108, 108 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
