// TP_Plan / plan.hlsl — the plan authority for tessera_pool.
//
// One node decides the tank, the lining, the palette, the light and every ripple source.
// TP_Sim, TP_Caustics and TP_Render all read those records and none of them re-decides
// anything: there is exactly one answer to "how deep is the water" or "where is that ripple".
//
// Single-threaded on purpose. 25 records is nothing, the layout is sequential, and the
// viewport event queue has to be reduced in order.
//
// Regeneration is SIGNATURE-DRIVEN and covers the SOURCES ONLY. Tank, light and palette are
// republished in place every cook, so changing the water depth or the grout colour never costs
// the user a hand-arranged set of ripples. Shader edits are invisible to the signature — bump
// PLAN_VERSION when the generation code changes or the buffer keeps serving the old plan.
#include "../_shared/tessera.hlsli"
#include "layout.hlsli"

RWStructuredBuffer<TpRec> Plan : register(u0);

// Bump this whenever the generation code changes. The signature is built from PARAMETERS, and
// a shader edit changes none of them — without a version bump the persistent buffer keeps
// serving records generated by the old code and the edit looks like it did nothing.
#define PLAN_VERSION 1.3

#define SEP_MIN   0.42      // minimum footprint separation between two sources
#define MARGIN    0.11      // keep sources this far inside the footprint edge
#define TARGET_E  1.2630    // the transcription's total wave energy, sqrt(sum amp^2)

// ---------------------------------------------------------------------------
// THE REFERENCE, TRANSCRIBED.
//
// Read off the photograph and converted into footprint space (-1..1 across the interior,
// +x right, +z toward the viewer). Four sources carry the whole surface:
//
//   0  the dominant concentric ring system, far side and right of centre. A repeating DROP.
//      The reference's steady ring train is what a continuous EMITTER makes, and that is what
//      this was — but a continuous emitter never stops, so the tank can never come to rest, and
//      a tank of water that cannot calm down is not water. A drop rings out and decays, and
//      pressing M on this source restores the emitter for anyone who wants the fixed train.
//   1  the long smooth swell rolling through the near-left quarter. Also a drop now, and for
//      the same reason: a swell is a sustained driver too.
//   2  a secondary ring set left of centre, weaker and slower.
//   3  a small drop far right, near the corner, that supplies the fine cross-hatched
//      interference along the right wall.
// ---------------------------------------------------------------------------
static const float2 REF_F[4]   = { float2( 0.300, -0.220), float2(-0.550,  0.420),
                                   float2(-0.340, -0.060), float2( 0.620,  0.520) };
static const float  REF_K[4]   = { KIND_DROP, KIND_DROP, KIND_DROP, KIND_DROP };
static const float  REF_AMP[4] = { 1.000, 0.550, 0.450, 0.300 };
// Drop periods must be LONG relative to the decay time or the tank is re-excited before it can
// quieten and never rests. At a damping e-fold near two seconds these leave several seconds of
// genuine calm between impacts, which is what makes the water read as water.
static const float  REF_PER[4] = { 9.000, 15.000, 6.500, 11.000 };   // seconds between drops
static const float  REF_WAV[4] = { 0.150, 0.230, 0.105, 0.082 };
static const float  REF_ANG[4] = { 0.000, 0.620, 0.000, 0.000 };
static const float  REF_RAD[4] = { 0.055, 0.180, 0.048, 0.038 };

// working set, single thread
static float2 gF[16];
static float  gK[16];
static float  gAmp[16];
static float  gPer[16];
static float  gWav[16];
static float  gAng[16];
static float  gRad[16];
static uint   gN = 4u;

// A descending amplitude ladder. The hierarchy is imposed BY CONSTRUCTION rather than hoped
// for: every seed keeps one dominant source and a tail of supports, which is what stops a
// re-roll reading as four equal puddles instead of a composition.
float ladderAmp(uint i, float s)
{
    float base = pow(0.72, (float)i);
    return base * lerp(0.90, 1.12, tpRnd2(i * 31u + 7u, s));
}

// Stratified footprint draw: a jittered 4x4 lattice, visited in a hash-permuted order so
// consecutive sources do not march along a row.
float2 stratum(uint i, float s)
{
    uint cell = (tpHashU(i * 2654435761u ^ asuint(s + 1.0)) % 16u);
    float cx = ((float)(cell % 4u) + 0.5) * 0.5 - 1.0;
    float cz = ((float)(cell / 4u) + 0.5) * 0.5 - 1.0;
    return float2(cx + (tpRnd2(i * 17u + 3u, s) - 0.5) * 0.40,
                  cz + (tpRnd2(i * 17u + 4u, s) - 0.5) * 0.40);
}

void buildSources(float s)
{
    gN = (uint)clamp((float)source_count, 1.0, 16.0);
    int arr = (int)arrangement;

    for (uint i = 0u; i < 16u; i++)
    {
        float fi = (float)i;

        if (arr == 0)
        {
            // Single Drop — the transcription, extended along a golden-angle spiral around the
            // primary for any source past the four the reference actually shows.
            if (i < 4u)
            {
                gF[i] = REF_F[i]; gK[i] = REF_K[i]; gAmp[i] = REF_AMP[i];
                gPer[i] = REF_PER[i]; gWav[i] = REF_WAV[i]; gAng[i] = REF_ANG[i]; gRad[i] = REF_RAD[i];
            }
            else
            {
                float a = fi * 2.39996;
                float r = 0.30 + 0.10 * (fi - 3.0);
                gF[i] = REF_F[0] + float2(cos(a), sin(a)) * r;
                gK[i] = KIND_DROP; gAmp[i] = ladderAmp(i, s);
                gPer[i] = lerp(1.8, 5.4, tpRnd2(i * 11u, s)); gWav[i] = lerp(0.06, 0.11, tpRnd2(i * 13u, s));
                gAng[i] = 0.0; gRad[i] = lerp(0.030, 0.055, tpRnd2(i * 19u, s));
            }
        }
        else if (arr == 1)
        {
            // Rain — every source a drop, spread across the whole footprint, periods spread so
            // the impacts never fall into lockstep.
            gF[i] = stratum(i, s + 41.0);
            gK[i] = KIND_DROP;
            gAmp[i] = ladderAmp(i, s) * 0.82;
            gPer[i] = lerp(1.3, 5.6, tpRnd2(i * 23u + 5u, s));
            gWav[i] = lerp(0.055, 0.115, tpRnd2(i * 29u, s));
            gAng[i] = 0.0;
            gRad[i] = lerp(0.026, 0.052, tpRnd2(i * 37u, s));
        }
        else if (arr == 2)
        {
            // Corner Swell — two long swells launched from adjacent corners, crossing. The
            // interference lattice IS the composition here, so the drops stay small.
            if (i < 2u)
            {
                float sgn = (i == 0u) ? -1.0 : 1.0;
                gF[i] = float2(sgn * 0.74, (i == 0u) ? 0.66 : -0.70);
                gK[i] = KIND_SWELL;
                gAmp[i] = (i == 0u) ? 1.00 : 0.78;
                gPer[i] = lerp(0.22, 0.40, tpRnd2(i * 7u, s));
                gWav[i] = lerp(0.40, 0.62, tpRnd2(i * 9u, s));
                gAng[i] = (i == 0u) ? -0.72 : 2.36;
                gRad[i] = 0.20;
            }
            else
            {
                gF[i] = stratum(i, s + 77.0) * 0.8;
                gK[i] = KIND_DROP; gAmp[i] = ladderAmp(i, s) * 0.55;
                gPer[i] = lerp(2.2, 5.0, tpRnd2(i * 43u, s)); gWav[i] = lerp(0.07, 0.12, tpRnd2(i * 47u, s));
                gAng[i] = 0.0; gRad[i] = 0.042;
            }
        }
        else
        {
            // Lattice — emitters on a regular grid sharing one frequency, so the surface fills
            // with a standing interference figure instead of travelling rings.
            uint k = max(2u, (uint)ceil(sqrt((float)gN)));
            uint cx = i % k, cz = i / k;
            gF[i] = float2(((float)cx + 0.5) / (float)k * 2.0 - 1.0,
                           ((float)cz + 0.5) / (float)k * 2.0 - 1.0) * 0.82;
            gK[i] = KIND_EMIT;
            gAmp[i] = ladderAmp(i, s) * 0.85 + 0.25;
            gPer[i] = lerp(0.85, 1.05, tpRnd2(i * 53u, s));   // unused: lattice emitters are wavelength-driven
            gWav[i] = lerp(0.10, 0.15, tpRnd2(i * 59u, s));
            gAng[i] = 0.0;
            gRad[i] = 0.050;
        }
    }

    // --- variation: lerp each source toward a free stratified draw. Continuous, and exactly
    // the transcription at 0.
    float v = saturate(variation);
    if (v > 0.0)
    {
        for (uint j = 0u; j < 16u; j++)
        {
            float2 free = stratum(j, s);
            gF[j] = lerp(gF[j], free, v);
            gAmp[j] = lerp(gAmp[j], ladderAmp(j, s), v);
            gWav[j] = lerp(gWav[j], lerp(0.055, 0.30, tpRnd2(j * 61u, s)), v * 0.7);
            gPer[j] = lerp(gPer[j], lerp(0.9, 5.2, tpRnd2(j * 67u, s)), v * 0.7);
            gAng[j] = lerp(gAng[j], tpRnd2(j * 71u, s) * 6.2832, v);
        }
    }

    for (uint p = 0u; p < 16u; p++) gF[p] *= max(spread, 0.05);

    // --- GUARANTEES. Gated on variation so the transcription is never nudged off its
    // transcribed coordinates by a correction it does not need.
    if (v > 0.0)
    {
        float lim = 1.0 - MARGIN;

        // separation: three relaxation sweeps. Without this a draw regularly puts two sources
        // inside one wavelength of each other, which does not read as two sources at all.
        for (uint sweep = 0u; sweep < 3u; sweep++)
        {
            for (uint a = 0u; a < gN; a++)
            {
                for (uint b = a + 1u; b < gN; b++)
                {
                    float2 d = gF[b] - gF[a];
                    float l = length(d);
                    if (l < SEP_MIN)
                    {
                        float2 dir = (l > 1e-4) ? d / l : float2(1.0, 0.0);
                        float push = (SEP_MIN - l) * 0.5;
                        gF[a] -= dir * push;
                        gF[b] += dir * push;
                    }
                }
            }
            for (uint c = 0u; c < gN; c++) gF[c] = clamp(gF[c], -lim, lim);
        }

        // fit: one uniform translation so the active cluster sits where the composition wants
        // it rather than wherever the draw happened to land. Slightly right of and beyond
        // centre, which is where the reference puts its ring system.
        float2 cen = float2(0.0, 0.0);
        for (uint m = 0u; m < gN; m++) cen += gF[m];
        cen /= (float)gN;
        float2 shift = (float2(0.06, -0.08) - cen) * 0.85;
        for (uint q = 0u; q < gN; q++) gF[q] = clamp(gF[q] + shift, -lim, lim);
    }

    // --- energy normalisation. Every seed injects the SAME total wave energy as the
    // reference, so no draw can come out flat and none can come out blown past the rim. At the
    // reference settings this is exactly a no-op, which is what keeps variation = 0 honest.
    float e = 0.0;
    for (uint n = 0u; n < gN; n++) e += gAmp[n] * gAmp[n];
    e = sqrt(max(e, 1e-6));
    float g = TARGET_E / e;
    for (uint r = 0u; r < gN; r++) gAmp[r] *= g;

    // --- commit
    for (uint w = 0u; w < TP_SRCS; w++)
    {
        TpRec rec = (TpRec)0;
        bool live = (w < gN);
        rec.pos    = float3(gF[w].x, 0.0, gF[w].y);
        rec.dims   = float3(gRad[w], 0.0, 0.0);
        rec.role   = ROLE_SRC;
        rec.kind   = gK[w];
        rec.tint   = float3(0.55, 0.80, 0.95);
        rec.seed   = s * 3.7 + (float)w * 17.13;
        rec.p0     = gAmp[w];
        rec.p1     = gPer[w];
        rec.p2     = gWav[w];
        rec.p3     = gAng[w];
        rec.flags  = 0.0;
        rec.active = live ? 1.0 : 0.0;
        Plan[TP_SRC_0 + w] = rec;
    }
}

// ---------------------------------------------------------------------------
// Appearance, republished every cook onto whatever records exist.
// ---------------------------------------------------------------------------
void refreshTank()
{
    int b = (int)basin;
    float mx = (b == 1) ? 1.35 : ((b == 2) ? 0.78 : ((b == 3) ? 1.20 : 1.00));
    float mz = (b == 1) ? 0.80 : ((b == 2) ? 0.78 : ((b == 3) ? 1.20 : 1.00));
    float md = (b == 1) ? 0.82 : ((b == 2) ? 1.65 : ((b == 3) ? 0.52 : 1.00));

    TpRec t = (TpRec)0;
    t.pos    = float3((float)tiling, tile_variance, tile_gloss);
    t.dims   = float3(mx * basin_scale, water_depth * md, mz * basin_scale);
    t.role   = ROLE_TANK;
    t.kind   = 0.0;
    t.tint   = grout_color;
    t.seed   = tile_seed;
    t.p0     = glass_thick;
    t.p1     = freeboard;
    t.p2     = tile_pitch;
    t.p3     = grout_width;
    t.active = 1.0;
    Plan[TP_TANK] = t;
}

void refreshLight()
{
    float az = radians(sun_azimuth);
    float el = radians(clamp(sun_elev, 3.0, 89.0));
    TpRec l = (TpRec)0;
    l.pos    = normalize(float3(cos(el) * sin(az), sin(el), cos(el) * cos(az)));
    l.dims   = float3(0, 0, 0);
    l.role   = ROLE_LIGHT;
    l.tint   = sun_color;
    l.p0     = sun_intensity;
    l.p1     = sky_level;
    l.p2     = caustic_gain;
    l.p3     = spec_power;
    l.active = 1.0;
    Plan[TP_LIGHT] = l;
}

void refreshPalette(float palSalt)
{
    float3 src[6] = { pal_a, pal_b, pal_c, pal_d, pal_e, pal_f };
    for (uint i = 0u; i < TP_PALS; i++)
    {
        float3 c = src[i];

        // A palette re-roll must stay INSIDE the authored palette, not wander off it: the
        // swatches shuffle position and shift value, but nobody invents a new hue. That keeps
        // every re-roll a plausible tile sheet instead of a random colour set.
        if (palSalt > 0.5)
        {
            uint j = tpHashU(i * 2654435761u ^ asuint(palSalt)) % 6u;
            c = lerp(src[i], src[j], 0.55);
            c *= lerp(0.80, 1.22, tpRnd2(i * 83u, palSalt));
        }

        TpRec r = (TpRec)0;
        r.pos    = float3(0, 0, 0);
        r.role   = ROLE_PAL;
        r.tint   = saturate(c);
        r.seed   = palSalt;
        r.p0     = 1.0;
        r.active = 1.0;
        Plan[TP_PAL_0 + i] = r;
    }
}

// ---------------------------------------------------------------------------
// Pick, in exactly the space the canvas draws in. Smallest hit wins so a small drop resting
// inside a big swell's ring stays reachable.
// ---------------------------------------------------------------------------
uint pickSource(float2 foot, TpLayout L, TpRec tank)
{
    uint best = 0u;
    float bestR = 1e9;
    for (uint i = 0u; i < TP_SRCS; i++)
    {
        TpRec r = Plan[TP_SRC_0 + i];
        float rad = tpSrcPickRadius(L, r, tank) / max(tank.dims.x, 1e-3);
        float d = length(foot - float2(r.pos.x, r.pos.z));
        if (r.active > 0.5 && d < rad * 1.9 && rad < bestR) { bestR = rad; best = TP_SRC_0 + i + 1u; }
    }
    return best;
}

[numthreads(1, 1, 1)]
void main(uint3 DTid : SV_DispatchThreadID)
{
    TpRec hdr = Plan[TP_HEADER];
    float initFlag = hdr.tint.x;
    float salt     = hdr.seed;
    float palSalt  = hdr.p2;
    float sel      = hdr.pos.y;      // selected buffer index + 1, 0 = nothing selected
    float dragOn   = hdr.dims.x;
    float2 grab    = float2(hdr.dims.y, hdr.dims.z);

    // The tank must exist before anything can be picked against it, and it is pure
    // appearance, so it is refreshed first and unconditionally.
    refreshTank();
    refreshLight();

    TpRec tank = Plan[TP_TANK];
    TpLayout L = tpLayout(_Resolution.xy, tank);

    uint n = min((uint)_ViewportEventCount, 64u);

    // --- keys. R and P change salts, so they land BEFORE the signature test or the rebuild
    // they ask for is immediately overwritten by the next cook's unchanged signature.
    for (uint e = 0u; e < n; e++)
    {
        ViewportEvent ev = _ViewportEvents[e];
        if (ev.type == 4u && ev.phase == 1u)
        {
            uint c = (uint)ev.code;
            if (c == 18u) salt += 1.0;                                    // R  reseed the layout
            else if (c == 16u) palSalt += 1.0;                            // P  re-roll the palette
            else if (c == 3u) sel = 0.0;                                  // C  clear selection
            else if (sel > 0.5)
            {
                uint idx = (uint)(sel - 1.0);
                TpRec r = Plan[idx];
                uint fl = (uint)r.flags;
                bool touched = true;

                if (c == 13u)                                             // M  cycle kind
                    r.kind = fmod(r.kind + 1.0, 3.0);
                else if (c == 7u)                                         // G  stronger
                    r.p0 = min(r.p0 * 1.15, 4.0);
                else if (c == 8u)                                         // H  weaker
                    r.p0 = max(r.p0 * 0.87, 0.02);
                else if (c == 1u)                                         // A  longer wavelength
                    r.p2 = min(r.p2 * 1.12, 0.60);
                else if (c == 26u)                                        // Z  shorter wavelength
                    r.p2 = max(r.p2 * 0.893, 0.035);
                else if (c == 24u)                                        // X  toggle on/off
                    r.active = (r.active > 0.5) ? 0.0 : 1.0;
                else if (c == 14u)                                        // N  re-roll this source
                {
                    r.seed += 9.31;
                    r.p1 = lerp(0.9, 5.2, tpRnd(r.seed, 2.0));
                    r.p2 = lerp(0.055, 0.28, tpRnd(r.seed, 3.0));
                    r.p3 = tpRnd(r.seed, 4.0) * 6.2832;
                    r.dims.x = lerp(0.026, 0.19, tpRnd(r.seed, 5.0));
                }
                else touched = false;

                if (touched) r.flags = (float)(fl | F_EDITED);
                Plan[idx] = r;
            }
        }
    }

    // Only STRUCTURAL parameters are in the signature. Tank, lining, palette and light are all
    // out of it, so tuning the water depth or the grout colour never wipes hand-placed ripples.
    float sig = seed * 7.31
              + (float)arrangement * 137.7
              + (float)source_count * 11.3
              + spread * 53.1
              + variation * 211.9
              + salt * 101.3
              + PLAN_VERSION * 911.7;

    if (initFlag < 0.5 || abs(sig - hdr.pos.x) > 1e-4)
    {
        buildSources(seed + salt * 3.19);
        sel = 0.0;
        dragOn = 0.0;
    }

    refreshPalette(palSalt);

    // --- pointer. Select and drag share pickSource() and footprint space with the canvas.
    for (uint e2 = 0u; e2 < n; e2++)
    {
        ViewportEvent ev = _ViewportEvents[e2];
        if (ev.type == 5u)
        {
            float2 px = ev.position * _Resolution.xy;
            bool inPlan = tpInPlanStrip(L, px);
            float2 foot = tpWorldToFoot(tpPxToPlan(L, px), tank);

            if (ev.code == 1u && ev.phase == 7u)
            {
                if (inPlan) sel = (float)pickSource(foot, L, tank);
            }
            else if (ev.code == 3u)
            {
                if (ev.phase == 5u)
                {
                    if (inPlan)
                    {
                        uint hit = pickSource(foot, L, tank);
                        sel = (float)hit;
                        if (hit != 0u) { dragOn = 1.0; grab = float2(Plan[hit - 1u].pos.x, Plan[hit - 1u].pos.z) - foot; }
                    }
                }
                else if (ev.phase == 6u && dragOn > 0.5 && sel > 0.5)
                {
                    uint idx = (uint)(sel - 1.0);
                    TpRec r = Plan[idx];
                    float2 f = clamp(foot + grab, -1.30, 1.30);
                    r.pos.x = f.x; r.pos.z = f.y;
                    r.flags = (float)(((uint)r.flags) | F_EDITED);
                    Plan[idx] = r;
                }
                else { dragOn = 0.0; }
            }
        }
    }

    // Selection is derived from the ONE stored index. Never mirrored onto records and then
    // kept in sync — that is two sources of truth waiting to disagree.
    uint live = 0u;
    float peakAmp = 0.0;
    float2 cen = float2(0, 0);
    for (uint i2 = 0u; i2 < TP_SRCS; i2++)
    {
        TpRec r = Plan[TP_SRC_0 + i2];
        uint f = (uint)r.flags;
        f = (sel > 0.5 && (uint)(sel - 1.0) == TP_SRC_0 + i2) ? (f | F_SELECTED) : (f & ~F_SELECTED);
        r.flags = (float)f;
        Plan[TP_SRC_0 + i2] = r;
        if (r.active > 0.5) { live++; peakAmp = max(peakAmp, r.p0); cen += float2(r.pos.x, r.pos.z); }
    }
    if (live > 0u) cen /= (float)live;

    hdr.pos    = float3(sig, sel, 0.0);
    hdr.dims   = float3(dragOn, grab.x, grab.y);
    hdr.role   = ROLE_HEADER;
    hdr.kind   = 0.0;
    hdr.tint   = float3(1.0, (float)live, peakAmp);
    hdr.seed   = salt;
    hdr.p0     = cen.x;
    hdr.p1     = cen.y;
    hdr.p2     = palSalt;
    hdr.p3     = 0.0;
    hdr.flags  = 0.0;
    hdr.active = 1.0;
    Plan[TP_HEADER] = hdr;
}
