#ifndef AV_0723_LFO_KIT_UI_GENERATED_HLSLI
#define AV_0723_LFO_KIT_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 97d0dda94f74d7a1cd93e7ad09f3c5af1a0e6962917a9c4a44f2cd951f1e27a3
static const uint UI_CONTROL_COUNT = 3u;
static const uint UI_LABEL_COUNT = 3u;
static const uint4 UI_MANIFEST_HASH = uint4(0x97d0dda9u, 0x4f74d7a1u, 0xcd93e7adu, 0x09f3c5afu);

static const uint UI_INDEX_TRANSPORT_RUN = 0u;
static const float4 UI_RECT_TRANSPORT_RUN = float4(0.045, 0.865, 0.125, 0.952);
static const uint UI_INDEX_RESET_PHASE = 1u;
static const float4 UI_RECT_RESET_PHASE = float4(0.135, 0.865, 0.215, 0.952);
static const uint UI_INDEX_SCRUB_PHASE = 2u;
static const float4 UI_RECT_SCRUB_PHASE = float4(0.245, 0.865, 0.945, 0.952);

static const uint UI_LABEL_CONTROL_TRANSPORT_RUN = 0u;
static const uint UI_LABEL_CONTROL_RESET_PHASE = 1u;
static const uint UI_LABEL_CONTROL_SCRUB_PHASE = 2u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 3;
    if (labelId == 1u) return 5;
    if (labelId == 2u) return 5;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[3] = { 82, 117, 110 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[5] = { 82, 101, 115, 101, 116 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[5] = { 80, 104, 97, 115, 101 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
