// Generated by tools/phage_labels.py. Edit the generator, not this file.
#ifndef PH_LABELS_HLSLI
#define PH_LABELS_HLSLI
static const uint PH_LBL_CH[182]={80,72,65,71,69,32,47,32,80,82,79,71,82,65,77,77,69,82,32,83,72,69,69,84,80,65,78,84,73,76,84,76,69,86,69,76,82,73,78,71,32,47,32,80,76,65,84,69,67,79,76,79,85,82,67,79,76,79,85,82,32,50,77,79,86,69,32,76,65,78,69,67,72,65,83,69,32,76,65,78,69,67,79,76,79,85,82,32,76,65,78,69,80,65,78,32,83,73,90,69,84,73,76,84,32,83,73,90,69,83,80,82,69,65,68,87,73,68,84,72,79,70,70,83,69,84,68,73,82,69,67,84,73,79,78,76,79,79,75,79,82,68,69,82,77,79,86,69,82,83,83,84,82,79,66,69,83,66,65,82,83,65,88,69,83,67,79,77,77,73,84,77,65,83,84,69,82,80,73,84,67,72};
static const uint2 PH_LBL_RANGE[25]={uint2(0,24),uint2(24,3),uint2(27,4),uint2(31,5),uint2(36,12),uint2(48,6),uint2(54,8),uint2(62,9),uint2(71,10),uint2(81,11),uint2(92,8),uint2(100,9),uint2(109,6),uint2(115,5),uint2(120,6),uint2(126,9),uint2(135,4),uint2(139,5),uint2(144,6),uint2(150,7),uint2(157,4),uint2(161,4),uint2(165,6),uint2(171,6),uint2(177,5)};
float phLabelWidth(uint id,float s){return (float)PH_LBL_RANGE[id].y*SUI3_ADVANCE*s;}
float phLabel(float2 P,float2 anchor,float s,uint id){
 uint2 r=PH_LBL_RANGE[id];if(sui3RunMiss(P,anchor,s,(int)r.y))return 0;
 int k=(int)floor((P.x-anchor.x)/(SUI3_ADVANCE*s));if(k<0||k>=(int)r.y)return 0;
 float cov=sui3Glyph(P,anchor+float2((float)k*SUI3_ADVANCE*s,0),s,(int)PH_LBL_CH[r.x+(uint)k]);
 if(k>0)cov=max(cov,sui3Glyph(P,anchor+float2((float)(k-1)*SUI3_ADVANCE*s,0),s,(int)PH_LBL_CH[r.x+(uint)k-1]));
 return cov;}
#endif
