#ifndef STRATA_COMPOSITION_BUS_UI_GENERATED_HLSLI
#define STRATA_COMPOSITION_BUS_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 9bcf4c957b086d73f86d1d971e5131086ee5c03445232e49bde534ec523fd825
static const uint UI_CONTROL_COUNT = 0u;
static const uint UI_LABEL_COUNT = 0u;
static const uint4 UI_MANIFEST_HASH = uint4(0x9bcf4c95u, 0x7b086d73u, 0xf86d1d97u, 0x1e513108u);



int uiLabelLength(uint labelId) {
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    return 32;
}

#endif
