#ifndef GENERATION_CONTROLLER_UI_GENERATED_HLSLI
#define GENERATION_CONTROLLER_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: f48ff4dab25c7889ec0b5f4456090e08d8e589d0be100e72248321e02b134f45
static const uint UI_CONTROL_COUNT = 7u;
static const uint UI_LABEL_COUNT = 20u;
static const uint4 UI_MANIFEST_HASH = uint4(0xf48ff4dau, 0xb25c7889u, 0xec0b5f44u, 0x56090e08u);

static const uint UI_INDEX_MODE = 0u;
static const float4 UI_RECT_MODE = float4(0.02, 0.03, 0.36, 0.14);
static const uint UI_INDEX_TRANSPORT = 1u;
static const float4 UI_RECT_TRANSPORT = float4(0.38, 0.03, 0.49, 0.14);
static const uint UI_INDEX_LINKED = 2u;
static const float4 UI_RECT_LINKED = float4(0.51, 0.03, 0.64, 0.14);
static const uint UI_INDEX_GENERATE = 3u;
static const float4 UI_RECT_GENERATE = float4(0.66, 0.03, 0.8, 0.14);
static const uint UI_INDEX_NEXT = 4u;
static const float4 UI_RECT_NEXT = float4(0.82, 0.03, 0.98, 0.14);
static const uint UI_INDEX_PROMPT_RATE = 5u;
static const float4 UI_RECT_PROMPT_RATE = float4(0.05, 0.27, 0.47, 0.4);
static const uint UI_INDEX_STAMP_SPEED = 6u;
static const float4 UI_RECT_STAMP_SPEED = float4(0.53, 0.27, 0.95, 0.4);

static const uint UI_LABEL_MANUAL = 0u;
static const uint UI_LABEL_INTERVAL = 1u;
static const uint UI_LABEL_CONTINUOUS = 2u;
static const uint UI_LABEL_RUN = 3u;
static const uint UI_LABEL_LINKED = 4u;
static const uint UI_LABEL_GENERATE = 5u;
static const uint UI_LABEL_NEXT = 6u;
static const uint UI_LABEL_PROMPT = 7u;
static const uint UI_LABEL_CYCLE = 8u;
static const uint UI_LABEL_HELD = 9u;
static const uint UI_LABEL_GENERATING = 10u;
static const uint UI_LABEL_PROMPT_RATE = 11u;
static const uint UI_LABEL_STAMP_SPEED = 12u;
static const uint UI_LABEL_CONTROL_MODE = 13u;
static const uint UI_LABEL_CONTROL_TRANSPORT = 14u;
static const uint UI_LABEL_CONTROL_LINKED = 15u;
static const uint UI_LABEL_CONTROL_GENERATE = 16u;
static const uint UI_LABEL_CONTROL_NEXT = 17u;
static const uint UI_LABEL_CONTROL_PROMPT_RATE = 18u;
static const uint UI_LABEL_CONTROL_STAMP_SPEED = 19u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 6;
    if (labelId == 1u) return 8;
    if (labelId == 2u) return 10;
    if (labelId == 3u) return 3;
    if (labelId == 4u) return 6;
    if (labelId == 5u) return 8;
    if (labelId == 6u) return 11;
    if (labelId == 7u) return 6;
    if (labelId == 8u) return 5;
    if (labelId == 9u) return 4;
    if (labelId == 10u) return 10;
    if (labelId == 11u) return 11;
    if (labelId == 12u) return 11;
    if (labelId == 13u) return 4;
    if (labelId == 14u) return 3;
    if (labelId == 15u) return 6;
    if (labelId == 16u) return 8;
    if (labelId == 17u) return 11;
    if (labelId == 18u) return 11;
    if (labelId == 19u) return 11;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[6] = { 77, 65, 78, 85, 65, 76 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[8] = { 73, 78, 84, 69, 82, 86, 65, 76 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[10] = { 67, 79, 78, 84, 73, 78, 85, 79, 85, 83 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[3] = { 82, 85, 78 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[6] = { 76, 73, 78, 75, 69, 68 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[8] = { 71, 69, 78, 69, 82, 65, 84, 69 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[11] = { 78, 69, 88, 84, 32, 80, 82, 79, 77, 80, 84 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[6] = { 80, 82, 79, 77, 80, 84 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[5] = { 67, 89, 67, 76, 69 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[4] = { 72, 69, 76, 68 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[10] = { 71, 69, 78, 69, 82, 65, 84, 73, 78, 71 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[11] = { 80, 82, 79, 77, 80, 84, 32, 82, 65, 84, 69 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 12u) {
        int codes[11] = { 83, 84, 65, 77, 80, 32, 83, 80, 69, 69, 68 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 13u) {
        int codes[4] = { 77, 111, 100, 101 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 14u) {
        int codes[3] = { 82, 117, 110 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 15u) {
        int codes[6] = { 76, 105, 110, 107, 101, 100 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 16u) {
        int codes[8] = { 71, 101, 110, 101, 114, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 17u) {
        int codes[11] = { 78, 101, 120, 116, 32, 80, 114, 111, 109, 112, 116 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 18u) {
        int codes[11] = { 80, 114, 111, 109, 112, 116, 32, 82, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 19u) {
        int codes[11] = { 83, 116, 97, 109, 112, 32, 83, 112, 101, 101, 100 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
