#ifndef KLANGRIG___DESK_UI_GENERATED_HLSLI
#define KLANGRIG___DESK_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 224fb0bf95b89755a7ad1406fa3895b85a18601f6578ffd6c858105884b1f815
static const uint UI_CONTROL_COUNT = 85u;
static const uint UI_LABEL_COUNT = 85u;
static const uint4 UI_MANIFEST_HASH = uint4(0x224fb0bfu, 0x95b89755u, 0xa7ad1406u, 0xfa3895b8u);

static const uint UI_INDEX_TAP = 0u;
static const float4 UI_RECT_TAP = float4(0.0125, 0.02778, 0.09375, 0.125);
static const uint UI_INDEX_PLAY = 1u;
static const float4 UI_RECT_PLAY = float4(0.0975, 0.02778, 0.17875, 0.125);
static const uint UI_INDEX_STOP = 2u;
static const float4 UI_RECT_STOP = float4(0.1825, 0.02778, 0.26375, 0.125);
static const uint UI_INDEX_SYNC = 3u;
static const float4 UI_RECT_SYNC = float4(0.2675, 0.02778, 0.34875, 0.125);
static const uint UI_INDEX_BPM = 4u;
static const float4 UI_RECT_BPM = float4(0.365, 0.02778, 0.54, 0.125);
static const uint UI_INDEX_BEAT = 5u;
static const float4 UI_RECT_BEAT = float4(0.54, 0.02778, 0.7025, 0.125);
static const uint UI_INDEX_BLACKOUT = 6u;
static const float4 UI_RECT_BLACKOUT = float4(0.77125, 0.02778, 0.8775, 0.125);
static const uint UI_INDEX_STROBE = 7u;
static const float4 UI_RECT_STROBE = float4(0.88125, 0.02778, 0.9875, 0.125);
static const uint UI_INDEX_HEAD_COMPLETE = 8u;
static const float4 UI_RECT_HEAD_COMPLETE = float4(0.0125, 0.16667, 0.49062, 0.20278);
static const uint UI_INDEX_COMPLETE_1 = 9u;
static const float4 UI_RECT_COMPLETE_1 = float4(0.0125, 0.21111, 0.06898, 0.28889);
static const uint UI_INDEX_COMPLETE_2 = 10u;
static const float4 UI_RECT_COMPLETE_2 = float4(0.07273, 0.21111, 0.12922, 0.28889);
static const uint UI_INDEX_COMPLETE_3 = 11u;
static const float4 UI_RECT_COMPLETE_3 = float4(0.13297, 0.21111, 0.18945, 0.28889);
static const uint UI_INDEX_COMPLETE_4 = 12u;
static const float4 UI_RECT_COMPLETE_4 = float4(0.1932, 0.21111, 0.24969, 0.28889);
static const uint UI_INDEX_COMPLETE_5 = 13u;
static const float4 UI_RECT_COMPLETE_5 = float4(0.25344, 0.21111, 0.30992, 0.28889);
static const uint UI_INDEX_COMPLETE_6 = 14u;
static const float4 UI_RECT_COMPLETE_6 = float4(0.31367, 0.21111, 0.37016, 0.28889);
static const uint UI_INDEX_COMPLETE_7 = 15u;
static const float4 UI_RECT_COMPLETE_7 = float4(0.37391, 0.21111, 0.43039, 0.28889);
static const uint UI_INDEX_COMPLETE_8 = 16u;
static const float4 UI_RECT_COMPLETE_8 = float4(0.43414, 0.21111, 0.49062, 0.28889);
static const uint UI_INDEX_COMPLETE_9 = 17u;
static const float4 UI_RECT_COMPLETE_9 = float4(0.0125, 0.29722, 0.06898, 0.375);
static const uint UI_INDEX_COMPLETE_10 = 18u;
static const float4 UI_RECT_COMPLETE_10 = float4(0.07273, 0.29722, 0.12922, 0.375);
static const uint UI_INDEX_COMPLETE_11 = 19u;
static const float4 UI_RECT_COMPLETE_11 = float4(0.13297, 0.29722, 0.18945, 0.375);
static const uint UI_INDEX_COMPLETE_12 = 20u;
static const float4 UI_RECT_COMPLETE_12 = float4(0.1932, 0.29722, 0.24969, 0.375);
static const uint UI_INDEX_COMPLETE_13 = 21u;
static const float4 UI_RECT_COMPLETE_13 = float4(0.25344, 0.29722, 0.30992, 0.375);
static const uint UI_INDEX_COMPLETE_14 = 22u;
static const float4 UI_RECT_COMPLETE_14 = float4(0.31367, 0.29722, 0.37016, 0.375);
static const uint UI_INDEX_COMPLETE_15 = 23u;
static const float4 UI_RECT_COMPLETE_15 = float4(0.37391, 0.29722, 0.43039, 0.375);
static const uint UI_INDEX_COMPLETE_16 = 24u;
static const float4 UI_RECT_COMPLETE_16 = float4(0.43414, 0.29722, 0.49062, 0.375);
static const uint UI_INDEX_HEAD_STATIC = 25u;
static const float4 UI_RECT_HEAD_STATIC = float4(0.50938, 0.16667, 0.9875, 0.20278);
static const uint UI_INDEX_STATIC_1 = 26u;
static const float4 UI_RECT_STATIC_1 = float4(0.50938, 0.21111, 0.56586, 0.28889);
static const uint UI_INDEX_STATIC_2 = 27u;
static const float4 UI_RECT_STATIC_2 = float4(0.56961, 0.21111, 0.62609, 0.28889);
static const uint UI_INDEX_STATIC_3 = 28u;
static const float4 UI_RECT_STATIC_3 = float4(0.62984, 0.21111, 0.68633, 0.28889);
static const uint UI_INDEX_STATIC_4 = 29u;
static const float4 UI_RECT_STATIC_4 = float4(0.69008, 0.21111, 0.74656, 0.28889);
static const uint UI_INDEX_STATIC_5 = 30u;
static const float4 UI_RECT_STATIC_5 = float4(0.75031, 0.21111, 0.8068, 0.28889);
static const uint UI_INDEX_STATIC_6 = 31u;
static const float4 UI_RECT_STATIC_6 = float4(0.81055, 0.21111, 0.86703, 0.28889);
static const uint UI_INDEX_STATIC_7 = 32u;
static const float4 UI_RECT_STATIC_7 = float4(0.87078, 0.21111, 0.92727, 0.28889);
static const uint UI_INDEX_STATIC_8 = 33u;
static const float4 UI_RECT_STATIC_8 = float4(0.93102, 0.21111, 0.9875, 0.28889);
static const uint UI_INDEX_STATIC_9 = 34u;
static const float4 UI_RECT_STATIC_9 = float4(0.50938, 0.29722, 0.56586, 0.375);
static const uint UI_INDEX_STATIC_10 = 35u;
static const float4 UI_RECT_STATIC_10 = float4(0.56961, 0.29722, 0.62609, 0.375);
static const uint UI_INDEX_STATIC_11 = 36u;
static const float4 UI_RECT_STATIC_11 = float4(0.62984, 0.29722, 0.68633, 0.375);
static const uint UI_INDEX_STATIC_12 = 37u;
static const float4 UI_RECT_STATIC_12 = float4(0.69008, 0.29722, 0.74656, 0.375);
static const uint UI_INDEX_STATIC_13 = 38u;
static const float4 UI_RECT_STATIC_13 = float4(0.75031, 0.29722, 0.8068, 0.375);
static const uint UI_INDEX_STATIC_14 = 39u;
static const float4 UI_RECT_STATIC_14 = float4(0.81055, 0.29722, 0.86703, 0.375);
static const uint UI_INDEX_STATIC_15 = 40u;
static const float4 UI_RECT_STATIC_15 = float4(0.87078, 0.29722, 0.92727, 0.375);
static const uint UI_INDEX_STATIC_16 = 41u;
static const float4 UI_RECT_STATIC_16 = float4(0.93102, 0.29722, 0.9875, 0.375);
static const uint UI_INDEX_HEAD_EFFECTS = 42u;
static const float4 UI_RECT_HEAD_EFFECTS = float4(0.0125, 0.41667, 0.49062, 0.45278);
static const uint UI_INDEX_EFFECTS_1 = 43u;
static const float4 UI_RECT_EFFECTS_1 = float4(0.0125, 0.46111, 0.06898, 0.53889);
static const uint UI_INDEX_EFFECTS_2 = 44u;
static const float4 UI_RECT_EFFECTS_2 = float4(0.07273, 0.46111, 0.12922, 0.53889);
static const uint UI_INDEX_EFFECTS_3 = 45u;
static const float4 UI_RECT_EFFECTS_3 = float4(0.13297, 0.46111, 0.18945, 0.53889);
static const uint UI_INDEX_EFFECTS_4 = 46u;
static const float4 UI_RECT_EFFECTS_4 = float4(0.1932, 0.46111, 0.24969, 0.53889);
static const uint UI_INDEX_EFFECTS_5 = 47u;
static const float4 UI_RECT_EFFECTS_5 = float4(0.25344, 0.46111, 0.30992, 0.53889);
static const uint UI_INDEX_EFFECTS_6 = 48u;
static const float4 UI_RECT_EFFECTS_6 = float4(0.31367, 0.46111, 0.37016, 0.53889);
static const uint UI_INDEX_EFFECTS_7 = 49u;
static const float4 UI_RECT_EFFECTS_7 = float4(0.37391, 0.46111, 0.43039, 0.53889);
static const uint UI_INDEX_EFFECTS_8 = 50u;
static const float4 UI_RECT_EFFECTS_8 = float4(0.43414, 0.46111, 0.49062, 0.53889);
static const uint UI_INDEX_EFFECTS_9 = 51u;
static const float4 UI_RECT_EFFECTS_9 = float4(0.0125, 0.54722, 0.06898, 0.625);
static const uint UI_INDEX_EFFECTS_10 = 52u;
static const float4 UI_RECT_EFFECTS_10 = float4(0.07273, 0.54722, 0.12922, 0.625);
static const uint UI_INDEX_EFFECTS_11 = 53u;
static const float4 UI_RECT_EFFECTS_11 = float4(0.13297, 0.54722, 0.18945, 0.625);
static const uint UI_INDEX_EFFECTS_12 = 54u;
static const float4 UI_RECT_EFFECTS_12 = float4(0.1932, 0.54722, 0.24969, 0.625);
static const uint UI_INDEX_EFFECTS_13 = 55u;
static const float4 UI_RECT_EFFECTS_13 = float4(0.25344, 0.54722, 0.30992, 0.625);
static const uint UI_INDEX_EFFECTS_14 = 56u;
static const float4 UI_RECT_EFFECTS_14 = float4(0.31367, 0.54722, 0.37016, 0.625);
static const uint UI_INDEX_EFFECTS_15 = 57u;
static const float4 UI_RECT_EFFECTS_15 = float4(0.37391, 0.54722, 0.43039, 0.625);
static const uint UI_INDEX_EFFECTS_16 = 58u;
static const float4 UI_RECT_EFFECTS_16 = float4(0.43414, 0.54722, 0.49062, 0.625);
static const uint UI_INDEX_HEAD_COLOR = 59u;
static const float4 UI_RECT_HEAD_COLOR = float4(0.50938, 0.41667, 0.9875, 0.45278);
static const uint UI_INDEX_COLOR_1 = 60u;
static const float4 UI_RECT_COLOR_1 = float4(0.50938, 0.46111, 0.56586, 0.53889);
static const uint UI_INDEX_COLOR_2 = 61u;
static const float4 UI_RECT_COLOR_2 = float4(0.56961, 0.46111, 0.62609, 0.53889);
static const uint UI_INDEX_COLOR_3 = 62u;
static const float4 UI_RECT_COLOR_3 = float4(0.62984, 0.46111, 0.68633, 0.53889);
static const uint UI_INDEX_COLOR_4 = 63u;
static const float4 UI_RECT_COLOR_4 = float4(0.69008, 0.46111, 0.74656, 0.53889);
static const uint UI_INDEX_COLOR_5 = 64u;
static const float4 UI_RECT_COLOR_5 = float4(0.75031, 0.46111, 0.8068, 0.53889);
static const uint UI_INDEX_COLOR_6 = 65u;
static const float4 UI_RECT_COLOR_6 = float4(0.81055, 0.46111, 0.86703, 0.53889);
static const uint UI_INDEX_COLOR_7 = 66u;
static const float4 UI_RECT_COLOR_7 = float4(0.87078, 0.46111, 0.92727, 0.53889);
static const uint UI_INDEX_COLOR_8 = 67u;
static const float4 UI_RECT_COLOR_8 = float4(0.93102, 0.46111, 0.9875, 0.53889);
static const uint UI_INDEX_COLOR_9 = 68u;
static const float4 UI_RECT_COLOR_9 = float4(0.50938, 0.54722, 0.56586, 0.625);
static const uint UI_INDEX_COLOR_10 = 69u;
static const float4 UI_RECT_COLOR_10 = float4(0.56961, 0.54722, 0.62609, 0.625);
static const uint UI_INDEX_COLOR_11 = 70u;
static const float4 UI_RECT_COLOR_11 = float4(0.62984, 0.54722, 0.68633, 0.625);
static const uint UI_INDEX_COLOR_12 = 71u;
static const float4 UI_RECT_COLOR_12 = float4(0.69008, 0.54722, 0.74656, 0.625);
static const uint UI_INDEX_COLOR_13 = 72u;
static const float4 UI_RECT_COLOR_13 = float4(0.75031, 0.54722, 0.8068, 0.625);
static const uint UI_INDEX_COLOR_14 = 73u;
static const float4 UI_RECT_COLOR_14 = float4(0.81055, 0.54722, 0.86703, 0.625);
static const uint UI_INDEX_COLOR_15 = 74u;
static const float4 UI_RECT_COLOR_15 = float4(0.87078, 0.54722, 0.92727, 0.625);
static const uint UI_INDEX_COLOR_16 = 75u;
static const float4 UI_RECT_COLOR_16 = float4(0.93102, 0.54722, 0.9875, 0.625);
static const uint UI_INDEX_HEAD_CAMERA = 76u;
static const float4 UI_RECT_HEAD_CAMERA = float4(0.0125, 0.68056, 0.3625, 0.71667);
static const uint UI_INDEX_CAM_UP = 77u;
static const float4 UI_RECT_CAM_UP = float4(0.07625, 0.725, 0.13625, 0.79722);
static const uint UI_INDEX_CAM_LEFT = 78u;
static const float4 UI_RECT_CAM_LEFT = float4(0.0125, 0.80556, 0.0725, 0.87778);
static const uint UI_INDEX_CAM_DOWN = 79u;
static const float4 UI_RECT_CAM_DOWN = float4(0.07625, 0.80556, 0.13625, 0.87778);
static const uint UI_INDEX_CAM_RIGHT = 80u;
static const float4 UI_RECT_CAM_RIGHT = float4(0.14, 0.80556, 0.2, 0.87778);
static const uint UI_INDEX_CAM_IN = 81u;
static const float4 UI_RECT_CAM_IN = float4(0.2675, 0.725, 0.3275, 0.79722);
static const uint UI_INDEX_CAM_OUT = 82u;
static const float4 UI_RECT_CAM_OUT = float4(0.2675, 0.80556, 0.3275, 0.87778);
static const uint UI_INDEX_CAM_HOME = 83u;
static const float4 UI_RECT_CAM_HOME = float4(0.33125, 0.725, 0.39125, 0.79722);
static const uint UI_INDEX_STATUS = 84u;
static const float4 UI_RECT_STATUS = float4(0.41625, 0.725, 0.9875, 0.87778);

static const uint UI_LABEL_CONTROL_TAP = 0u;
static const uint UI_LABEL_CONTROL_PLAY = 1u;
static const uint UI_LABEL_CONTROL_STOP = 2u;
static const uint UI_LABEL_CONTROL_SYNC = 3u;
static const uint UI_LABEL_CONTROL_BPM = 4u;
static const uint UI_LABEL_CONTROL_BEAT = 5u;
static const uint UI_LABEL_CONTROL_BLACKOUT = 6u;
static const uint UI_LABEL_CONTROL_STROBE = 7u;
static const uint UI_LABEL_CONTROL_HEAD_COMPLETE = 8u;
static const uint UI_LABEL_CONTROL_COMPLETE_1 = 9u;
static const uint UI_LABEL_CONTROL_COMPLETE_2 = 10u;
static const uint UI_LABEL_CONTROL_COMPLETE_3 = 11u;
static const uint UI_LABEL_CONTROL_COMPLETE_4 = 12u;
static const uint UI_LABEL_CONTROL_COMPLETE_5 = 13u;
static const uint UI_LABEL_CONTROL_COMPLETE_6 = 14u;
static const uint UI_LABEL_CONTROL_COMPLETE_7 = 15u;
static const uint UI_LABEL_CONTROL_COMPLETE_8 = 16u;
static const uint UI_LABEL_CONTROL_COMPLETE_9 = 17u;
static const uint UI_LABEL_CONTROL_COMPLETE_10 = 18u;
static const uint UI_LABEL_CONTROL_COMPLETE_11 = 19u;
static const uint UI_LABEL_CONTROL_COMPLETE_12 = 20u;
static const uint UI_LABEL_CONTROL_COMPLETE_13 = 21u;
static const uint UI_LABEL_CONTROL_COMPLETE_14 = 22u;
static const uint UI_LABEL_CONTROL_COMPLETE_15 = 23u;
static const uint UI_LABEL_CONTROL_COMPLETE_16 = 24u;
static const uint UI_LABEL_CONTROL_HEAD_STATIC = 25u;
static const uint UI_LABEL_CONTROL_STATIC_1 = 26u;
static const uint UI_LABEL_CONTROL_STATIC_2 = 27u;
static const uint UI_LABEL_CONTROL_STATIC_3 = 28u;
static const uint UI_LABEL_CONTROL_STATIC_4 = 29u;
static const uint UI_LABEL_CONTROL_STATIC_5 = 30u;
static const uint UI_LABEL_CONTROL_STATIC_6 = 31u;
static const uint UI_LABEL_CONTROL_STATIC_7 = 32u;
static const uint UI_LABEL_CONTROL_STATIC_8 = 33u;
static const uint UI_LABEL_CONTROL_STATIC_9 = 34u;
static const uint UI_LABEL_CONTROL_STATIC_10 = 35u;
static const uint UI_LABEL_CONTROL_STATIC_11 = 36u;
static const uint UI_LABEL_CONTROL_STATIC_12 = 37u;
static const uint UI_LABEL_CONTROL_STATIC_13 = 38u;
static const uint UI_LABEL_CONTROL_STATIC_14 = 39u;
static const uint UI_LABEL_CONTROL_STATIC_15 = 40u;
static const uint UI_LABEL_CONTROL_STATIC_16 = 41u;
static const uint UI_LABEL_CONTROL_HEAD_EFFECTS = 42u;
static const uint UI_LABEL_CONTROL_EFFECTS_1 = 43u;
static const uint UI_LABEL_CONTROL_EFFECTS_2 = 44u;
static const uint UI_LABEL_CONTROL_EFFECTS_3 = 45u;
static const uint UI_LABEL_CONTROL_EFFECTS_4 = 46u;
static const uint UI_LABEL_CONTROL_EFFECTS_5 = 47u;
static const uint UI_LABEL_CONTROL_EFFECTS_6 = 48u;
static const uint UI_LABEL_CONTROL_EFFECTS_7 = 49u;
static const uint UI_LABEL_CONTROL_EFFECTS_8 = 50u;
static const uint UI_LABEL_CONTROL_EFFECTS_9 = 51u;
static const uint UI_LABEL_CONTROL_EFFECTS_10 = 52u;
static const uint UI_LABEL_CONTROL_EFFECTS_11 = 53u;
static const uint UI_LABEL_CONTROL_EFFECTS_12 = 54u;
static const uint UI_LABEL_CONTROL_EFFECTS_13 = 55u;
static const uint UI_LABEL_CONTROL_EFFECTS_14 = 56u;
static const uint UI_LABEL_CONTROL_EFFECTS_15 = 57u;
static const uint UI_LABEL_CONTROL_EFFECTS_16 = 58u;
static const uint UI_LABEL_CONTROL_HEAD_COLOR = 59u;
static const uint UI_LABEL_CONTROL_COLOR_1 = 60u;
static const uint UI_LABEL_CONTROL_COLOR_2 = 61u;
static const uint UI_LABEL_CONTROL_COLOR_3 = 62u;
static const uint UI_LABEL_CONTROL_COLOR_4 = 63u;
static const uint UI_LABEL_CONTROL_COLOR_5 = 64u;
static const uint UI_LABEL_CONTROL_COLOR_6 = 65u;
static const uint UI_LABEL_CONTROL_COLOR_7 = 66u;
static const uint UI_LABEL_CONTROL_COLOR_8 = 67u;
static const uint UI_LABEL_CONTROL_COLOR_9 = 68u;
static const uint UI_LABEL_CONTROL_COLOR_10 = 69u;
static const uint UI_LABEL_CONTROL_COLOR_11 = 70u;
static const uint UI_LABEL_CONTROL_COLOR_12 = 71u;
static const uint UI_LABEL_CONTROL_COLOR_13 = 72u;
static const uint UI_LABEL_CONTROL_COLOR_14 = 73u;
static const uint UI_LABEL_CONTROL_COLOR_15 = 74u;
static const uint UI_LABEL_CONTROL_COLOR_16 = 75u;
static const uint UI_LABEL_CONTROL_HEAD_CAMERA = 76u;
static const uint UI_LABEL_CONTROL_CAM_UP = 77u;
static const uint UI_LABEL_CONTROL_CAM_LEFT = 78u;
static const uint UI_LABEL_CONTROL_CAM_DOWN = 79u;
static const uint UI_LABEL_CONTROL_CAM_RIGHT = 80u;
static const uint UI_LABEL_CONTROL_CAM_IN = 81u;
static const uint UI_LABEL_CONTROL_CAM_OUT = 82u;
static const uint UI_LABEL_CONTROL_CAM_HOME = 83u;
static const uint UI_LABEL_CONTROL_STATUS = 84u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 3;
    if (labelId == 1u) return 4;
    if (labelId == 2u) return 4;
    if (labelId == 3u) return 4;
    if (labelId == 4u) return 9;
    if (labelId == 5u) return 12;
    if (labelId == 6u) return 8;
    if (labelId == 7u) return 6;
    if (labelId == 8u) return 10;
    if (labelId == 9u) return 2;
    if (labelId == 10u) return 2;
    if (labelId == 11u) return 2;
    if (labelId == 12u) return 2;
    if (labelId == 13u) return 2;
    if (labelId == 14u) return 2;
    if (labelId == 15u) return 2;
    if (labelId == 16u) return 2;
    if (labelId == 17u) return 2;
    if (labelId == 18u) return 2;
    if (labelId == 19u) return 2;
    if (labelId == 20u) return 2;
    if (labelId == 21u) return 2;
    if (labelId == 22u) return 2;
    if (labelId == 23u) return 2;
    if (labelId == 24u) return 2;
    if (labelId == 25u) return 6;
    if (labelId == 26u) return 9;
    if (labelId == 27u) return 5;
    if (labelId == 28u) return 5;
    if (labelId == 29u) return 8;
    if (labelId == 30u) return 7;
    if (labelId == 31u) return 7;
    if (labelId == 32u) return 5;
    if (labelId == 33u) return 4;
    if (labelId == 34u) return 5;
    if (labelId == 35u) return 8;
    if (labelId == 36u) return 9;
    if (labelId == 37u) return 8;
    if (labelId == 38u) return 7;
    if (labelId == 39u) return 5;
    if (labelId == 40u) return 6;
    if (labelId == 41u) return 6;
    if (labelId == 42u) return 7;
    if (labelId == 43u) return 5;
    if (labelId == 44u) return 6;
    if (labelId == 45u) return 9;
    if (labelId == 46u) return 5;
    if (labelId == 47u) return 4;
    if (labelId == 48u) return 10;
    if (labelId == 49u) return 5;
    if (labelId == 50u) return 4;
    if (labelId == 51u) return 4;
    if (labelId == 52u) return 7;
    if (labelId == 53u) return 6;
    if (labelId == 54u) return 7;
    if (labelId == 55u) return 7;
    if (labelId == 56u) return 4;
    if (labelId == 57u) return 4;
    if (labelId == 58u) return 5;
    if (labelId == 59u) return 5;
    if (labelId == 60u) return 5;
    if (labelId == 61u) return 4;
    if (labelId == 62u) return 3;
    if (labelId == 63u) return 6;
    if (labelId == 64u) return 4;
    if (labelId == 65u) return 5;
    if (labelId == 66u) return 4;
    if (labelId == 67u) return 4;
    if (labelId == 68u) return 2;
    if (labelId == 69u) return 7;
    if (labelId == 70u) return 4;
    if (labelId == 71u) return 4;
    if (labelId == 72u) return 5;
    if (labelId == 73u) return 5;
    if (labelId == 74u) return 4;
    if (labelId == 75u) return 3;
    if (labelId == 76u) return 6;
    if (labelId == 77u) return 2;
    if (labelId == 78u) return 1;
    if (labelId == 79u) return 4;
    if (labelId == 80u) return 1;
    if (labelId == 81u) return 2;
    if (labelId == 82u) return 3;
    if (labelId == 83u) return 4;
    if (labelId == 84u) return 10;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[3] = { 84, 65, 80 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[4] = { 80, 76, 65, 89 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[4] = { 83, 84, 79, 80 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[4] = { 83, 89, 78, 67 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[9] = { 45, 45, 45, 46, 45, 32, 66, 80, 77 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[12] = { 66, 65, 82, 32, 45, 32, 66, 69, 65, 84, 32, 45 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[8] = { 66, 76, 65, 67, 75, 79, 85, 84 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[6] = { 83, 84, 82, 79, 66, 69 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[10] = { 70, 85, 76, 76, 32, 76, 79, 79, 75, 83 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[2] = { 48, 49 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[2] = { 48, 50 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[2] = { 48, 51 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 12u) {
        int codes[2] = { 48, 52 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 13u) {
        int codes[2] = { 48, 53 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 14u) {
        int codes[2] = { 48, 54 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 15u) {
        int codes[2] = { 48, 55 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 16u) {
        int codes[2] = { 48, 56 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 17u) {
        int codes[2] = { 48, 57 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 18u) {
        int codes[2] = { 49, 48 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 19u) {
        int codes[2] = { 49, 49 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 20u) {
        int codes[2] = { 49, 50 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 21u) {
        int codes[2] = { 49, 51 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 22u) {
        int codes[2] = { 49, 52 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 23u) {
        int codes[2] = { 49, 53 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 24u) {
        int codes[2] = { 49, 54 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 25u) {
        int codes[6] = { 83, 84, 65, 84, 73, 67 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 26u) {
        int codes[9] = { 82, 69, 70, 69, 82, 69, 78, 67, 69 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 27u) {
        int codes[5] = { 70, 82, 79, 78, 84 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 28u) {
        int codes[5] = { 72, 69, 76, 73, 88 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 29u) {
        int codes[8] = { 83, 85, 78, 66, 85, 82, 83, 84 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 30u) {
        int codes[7] = { 78, 69, 69, 68, 76, 69, 83 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 31u) {
        int codes[7] = { 86, 45, 71, 65, 84, 69, 83 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 32u) {
        int codes[5] = { 87, 69, 65, 86, 69 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 33u) {
        int codes[4] = { 67, 65, 71, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 34u) {
        int codes[5] = { 82, 73, 78, 71, 83 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 35u) {
        int codes[8] = { 80, 73, 78, 80, 79, 73, 78, 84 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 36u) {
        int codes[9] = { 67, 65, 84, 72, 69, 68, 82, 65, 76 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 37u) {
        int codes[8] = { 66, 76, 73, 78, 68, 69, 82, 83 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 38u) {
        int codes[7] = { 72, 79, 82, 73, 90, 79, 78 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 39u) {
        int codes[5] = { 80, 82, 73, 83, 77 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 40u) {
        int codes[6] = { 83, 72, 65, 82, 68, 83 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 41u) {
        int codes[6] = { 88, 45, 70, 73, 82, 69 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 42u) {
        int codes[7] = { 69, 70, 70, 69, 67, 84, 83 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 43u) {
        int codes[5] = { 67, 72, 65, 83, 69 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 44u) {
        int codes[6] = { 70, 88, 32, 79, 70, 70 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 45u) {
        int codes[9] = { 76, 45, 83, 67, 65, 84, 84, 69, 82 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 46u) {
        int codes[5] = { 67, 79, 77, 66, 79 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 47u) {
        int codes[4] = { 73, 82, 73, 83 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 48u) {
        int codes[10] = { 67, 82, 73, 83, 83, 67, 82, 79, 83, 83 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 49u) {
        int codes[5] = { 82, 79, 84, 79, 82 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 50u) {
        int codes[4] = { 82, 73, 79, 84 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 51u) {
        int codes[4] = { 65, 82, 67, 72 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 52u) {
        int codes[7] = { 66, 65, 89, 32, 72, 79, 80 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 53u) {
        int codes[6] = { 90, 73, 80, 80, 69, 82 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 54u) {
        int codes[7] = { 83, 72, 65, 84, 84, 69, 82 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 55u) {
        int codes[7] = { 67, 85, 82, 84, 65, 73, 78 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 56u) {
        int codes[4] = { 87, 65, 82, 80 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 57u) {
        int codes[4] = { 82, 65, 73, 78 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 58u) {
        int codes[5] = { 83, 84, 79, 82, 77 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 59u) {
        int codes[5] = { 67, 79, 76, 79, 82 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 60u) {
        int codes[5] = { 87, 72, 73, 84, 69 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 61u) {
        int codes[4] = { 67, 89, 65, 78 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 62u) {
        int codes[3] = { 82, 69, 68 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 63u) {
        int codes[6] = { 79, 82, 65, 78, 71, 69 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 64u) {
        int codes[4] = { 71, 79, 76, 68 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 65u) {
        int codes[5] = { 71, 82, 69, 69, 78 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 66u) {
        int codes[4] = { 65, 81, 85, 65 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 67u) {
        int codes[4] = { 66, 76, 85, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 68u) {
        int codes[2] = { 85, 86 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 69u) {
        int codes[7] = { 77, 65, 71, 69, 78, 84, 65 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 70u) {
        int codes[4] = { 80, 73, 78, 75 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 71u) {
        int codes[4] = { 87, 65, 82, 77 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 72u) {
        int codes[5] = { 83, 80, 47, 87, 71 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 73u) {
        int codes[5] = { 85, 80, 47, 76, 79 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 74u) {
        int codes[4] = { 66, 65, 89, 83 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 75u) {
        int codes[3] = { 65, 76, 84 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 76u) {
        int codes[6] = { 67, 65, 77, 69, 82, 65 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 77u) {
        int codes[2] = { 85, 80 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 78u) {
        int codes[1] = { 60 };
        return characterIndex >= 0 && characterIndex < 1 ? codes[characterIndex] : 32;
    }
    if (labelId == 79u) {
        int codes[4] = { 68, 79, 87, 78 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 80u) {
        int codes[1] = { 62 };
        return characterIndex >= 0 && characterIndex < 1 ? codes[characterIndex] : 32;
    }
    if (labelId == 81u) {
        int codes[2] = { 73, 78 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 82u) {
        int codes[3] = { 79, 85, 84 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 83u) {
        int codes[4] = { 72, 79, 77, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 84u) {
        int codes[10] = { 68, 69, 83, 75, 32, 82, 69, 65, 68, 89 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
