#ifndef SCIENTIFIC_PERFORMANCE_DECK_UI_GENERATED_HLSLI
#define SCIENTIFIC_PERFORMANCE_DECK_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: cfc26a9533a2f608de00b9f5cdd8a31e232be02a35690593920d97047131b979
static const uint UI_CONTROL_COUNT = 4u;
static const uint UI_LABEL_COUNT = 24u;
static const uint4 UI_MANIFEST_HASH = uint4(0xcfc26a95u, 0x33a2f608u, 0xde00b9f5u, 0xcdd8a31eu);

static const uint UI_INDEX_OBSERVE = 0u;
static const float4 UI_RECT_OBSERVE = float4(0.545, 0.012, 0.635, 0.061);
static const uint UI_INDEX_SURGE = 1u;
static const float4 UI_RECT_SURGE = float4(0.645, 0.012, 0.72, 0.061);
static const uint UI_INDEX_ARCHIVE = 2u;
static const float4 UI_RECT_ARCHIVE = float4(0.73, 0.012, 0.82, 0.061);
static const uint UI_INDEX_BALANCED = 3u;
static const float4 UI_RECT_BALANCED = float4(0.83, 0.012, 0.95, 0.061);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_KEYS = 1u;
static const uint UI_LABEL_ENERGY = 2u;
static const uint UI_LABEL_ENERGY_AXES = 3u;
static const uint UI_LABEL_STRUCTURE = 4u;
static const uint UI_LABEL_STRUCTURE_AXES = 5u;
static const uint UI_LABEL_MEMORY = 6u;
static const uint UI_LABEL_MEMORY_AXES = 7u;
static const uint UI_LABEL_EN = 8u;
static const uint UI_LABEL_WP = 9u;
static const uint UI_LABEL_TP = 10u;
static const uint UI_LABEL_RF = 11u;
static const uint UI_LABEL_MM = 12u;
static const uint UI_LABEL_AR = 13u;
static const uint UI_LABEL_HERO = 14u;
static const uint UI_LABEL_PERF = 15u;
static const uint UI_LABEL_OBSERVE = 16u;
static const uint UI_LABEL_SURGE = 17u;
static const uint UI_LABEL_ARCHIVE = 18u;
static const uint UI_LABEL_BALANCED = 19u;
static const uint UI_LABEL_CONTROL_OBSERVE = 20u;
static const uint UI_LABEL_CONTROL_SURGE = 21u;
static const uint UI_LABEL_CONTROL_ARCHIVE = 22u;
static const uint UI_LABEL_CONTROL_BALANCED = 23u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 38;
    if (labelId == 1u) return 21;
    if (labelId == 2u) return 6;
    if (labelId == 3u) return 13;
    if (labelId == 4u) return 9;
    if (labelId == 5u) return 17;
    if (labelId == 6u) return 6;
    if (labelId == 7u) return 18;
    if (labelId == 8u) return 2;
    if (labelId == 9u) return 2;
    if (labelId == 10u) return 2;
    if (labelId == 11u) return 2;
    if (labelId == 12u) return 2;
    if (labelId == 13u) return 2;
    if (labelId == 14u) return 4;
    if (labelId == 15u) return 4;
    if (labelId == 16u) return 7;
    if (labelId == 17u) return 5;
    if (labelId == 18u) return 7;
    if (labelId == 19u) return 8;
    if (labelId == 20u) return 12;
    if (labelId == 21u) return 10;
    if (labelId == 22u) return 12;
    if (labelId == 23u) return 13;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[38] = { 83, 67, 73, 69, 78, 84, 73, 70, 73, 67, 32, 79, 82, 71, 65, 78, 73, 83, 77, 32, 47, 32, 80, 69, 82, 70, 79, 82, 77, 65, 78, 67, 69, 32, 68, 69, 67, 75 };
        return characterIndex >= 0 && characterIndex < 38 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[21] = { 81, 32, 47, 32, 87, 32, 47, 32, 69, 32, 47, 32, 82, 32, 80, 82, 69, 83, 69, 84, 83 };
        return characterIndex >= 0 && characterIndex < 21 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[6] = { 69, 78, 69, 82, 71, 89 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[13] = { 83, 73, 71, 78, 65, 76, 32, 47, 32, 87, 65, 82, 80 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[9] = { 83, 84, 82, 85, 67, 84, 85, 82, 69 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[17] = { 84, 79, 80, 79, 76, 79, 71, 89, 32, 47, 32, 82, 69, 76, 73, 69, 70 };
        return characterIndex >= 0 && characterIndex < 17 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[6] = { 77, 69, 77, 79, 82, 89 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[18] = { 70, 73, 76, 65, 77, 69, 78, 84, 32, 47, 32, 65, 82, 67, 72, 73, 86, 69 };
        return characterIndex >= 0 && characterIndex < 18 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[2] = { 69, 78 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[2] = { 87, 80 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[2] = { 84, 80 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[2] = { 82, 70 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 12u) {
        int codes[2] = { 77, 77 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 13u) {
        int codes[2] = { 65, 82 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 14u) {
        int codes[4] = { 72, 69, 82, 79 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 15u) {
        int codes[4] = { 80, 69, 82, 70 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 16u) {
        int codes[7] = { 79, 66, 83, 69, 82, 86, 69 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 17u) {
        int codes[5] = { 83, 85, 82, 71, 69 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 18u) {
        int codes[7] = { 65, 82, 67, 72, 73, 86, 69 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 19u) {
        int codes[8] = { 66, 65, 76, 65, 78, 67, 69, 68 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 20u) {
        int codes[12] = { 79, 98, 115, 101, 114, 118, 101, 32, 76, 111, 111, 107 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 21u) {
        int codes[10] = { 83, 117, 114, 103, 101, 32, 76, 111, 111, 107 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 22u) {
        int codes[12] = { 65, 114, 99, 104, 105, 118, 101, 32, 76, 111, 111, 107 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 23u) {
        int codes[13] = { 66, 97, 108, 97, 110, 99, 101, 100, 32, 76, 111, 111, 107 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
