#ifndef STYLE_AUTHORITY_UI_GENERATED_HLSLI
#define STYLE_AUTHORITY_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 4da0969b7feffd5cf3dfc4f7c54713ede5b9a3271615e26df280e72c7d3904c5
static const uint UI_CONTROL_COUNT = 4u;
static const uint UI_LABEL_COUNT = 4u;
static const uint4 UI_MANIFEST_HASH = uint4(0x4da0969bu, 0x7feffd5cu, 0xf3dfc4f7u, 0xc54713edu);

static const uint UI_INDEX_PAD = 0u;
static const float4 UI_RECT_PAD = float4(0.015625, 0.120833, 0.559375, 0.315278);
static const uint UI_INDEX_RAIL = 1u;
static const float4 UI_RECT_RAIL = float4(0.015625, 0.341667, 0.520313, 0.388889);
static const uint UI_INDEX_TOGGLE = 2u;
static const float4 UI_RECT_TOGGLE = float4(0.015625, 0.415278, 0.073438, 0.4625);
static const uint UI_INDEX_BANK = 3u;
static const float4 UI_RECT_BANK = float4(0.092188, 0.415278, 0.559375, 0.4625);

static const uint UI_LABEL_CONTROL_PAD = 0u;
static const uint UI_LABEL_CONTROL_RAIL = 1u;
static const uint UI_LABEL_CONTROL_TOGGLE = 2u;
static const uint UI_LABEL_CONTROL_BANK = 3u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 3;
    if (labelId == 1u) return 4;
    if (labelId == 2u) return 5;
    if (labelId == 3u) return 4;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[3] = { 80, 65, 68 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[4] = { 82, 65, 73, 76 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[5] = { 83, 84, 65, 84, 69 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[4] = { 66, 65, 78, 75 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
