#ifndef PHASE_AUTHORITY_UI_GENERATED_HLSLI
#define PHASE_AUTHORITY_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 4f0e27a78e4808aada7601c0c2de3a149f03491c767e39a37f74967d9d2f22a5
static const uint UI_CONTROL_COUNT = 4u;
static const uint UI_LABEL_COUNT = 4u;
static const uint4 UI_MANIFEST_HASH = uint4(0x4f0e27a7u, 0x8e4808aau, 0xda7601c0u, 0xc2de3a14u);

static const uint UI_INDEX_PLAY = 0u;
static const float4 UI_RECT_PLAY = float4(0.055, 0.79, 0.205, 0.93);
static const uint UI_INDEX_RESET = 1u;
static const float4 UI_RECT_RESET = float4(0.225, 0.79, 0.375, 0.93);
static const uint UI_INDEX_SCRUB_MODE = 2u;
static const float4 UI_RECT_SCRUB_MODE = float4(0.395, 0.79, 0.585, 0.93);
static const uint UI_INDEX_SCRUB_PHASE = 3u;
static const float4 UI_RECT_SCRUB_PHASE = float4(0.61, 0.79, 0.945, 0.93);

static const uint UI_LABEL_CONTROL_PLAY = 0u;
static const uint UI_LABEL_CONTROL_RESET = 1u;
static const uint UI_LABEL_CONTROL_SCRUB_MODE = 2u;
static const uint UI_LABEL_CONTROL_SCRUB_PHASE = 3u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 4;
    if (labelId == 1u) return 5;
    if (labelId == 2u) return 5;
    if (labelId == 3u) return 8;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[4] = { 80, 108, 97, 121 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[5] = { 82, 101, 115, 101, 116 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[5] = { 83, 99, 114, 117, 98 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[8] = { 80, 111, 115, 105, 116, 105, 111, 110 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
