#ifndef LOOM_INTERACTION_SURFACE_UI_GENERATED_HLSLI
#define LOOM_INTERACTION_SURFACE_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 4346fcbc7ec575835a95640444e7a84b0fd40363681d4558686bd20192b337fc
static const uint UI_CONTROL_COUNT = 0u;
static const uint UI_LABEL_COUNT = 5u;
static const uint4 UI_MANIFEST_HASH = uint4(0x4346fcbcu, 0x7ec57583u, 0x5a956404u, 0x44e7a84bu);


static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_CORNERS = 1u;
static const uint UI_LABEL_BLOBS = 2u;
static const uint UI_LABEL_TOUCH = 3u;
static const uint UI_LABEL_LIVE = 4u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 11;
    if (labelId == 1u) return 7;
    if (labelId == 2u) return 5;
    if (labelId == 3u) return 11;
    if (labelId == 4u) return 4;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[11] = { 76, 79, 79, 77, 32, 83, 73, 71, 78, 65, 76 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[7] = { 67, 79, 82, 78, 69, 82, 83 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[5] = { 66, 76, 79, 66, 83 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[11] = { 84, 79, 85, 67, 72, 32, 70, 73, 69, 76, 68 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[4] = { 76, 73, 86, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
