#ifndef AXIOM_05___PRESSURE_DESK_UI_GENERATED_HLSLI
#define AXIOM_05___PRESSURE_DESK_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 24c633380388dad526d3d27a594318b0c4e3cce1afbc0391db6092f26c7a13a2
static const uint UI_CONTROL_COUNT = 4u;
static const uint UI_LABEL_COUNT = 15u;
static const uint4 UI_MANIFEST_HASH = uint4(0x24c63338u, 0x0388dad5u, 0x26d3d27au, 0x594318b0u);

static const uint UI_INDEX_PRESS_MODE = 0u;
static const float4 UI_RECT_PRESS_MODE = float4(0.77, 0.205, 0.965, 0.28);
static const uint UI_INDEX_SHEAR_MODE = 1u;
static const float4 UI_RECT_SHEAR_MODE = float4(0.77, 0.315, 0.965, 0.39);
static const uint UI_INDEX_VOID_MODE = 2u;
static const float4 UI_RECT_VOID_MODE = float4(0.77, 0.425, 0.965, 0.5);
static const uint UI_INDEX_CLEAR_FIELDS = 3u;
static const float4 UI_RECT_CLEAR_FIELDS = float4(0.77, 0.815, 0.965, 0.89);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_SUBTITLE = 1u;
static const uint UI_LABEL_PRESSURE = 2u;
static const uint UI_LABEL_SHEAR = 3u;
static const uint UI_LABEL_VOID = 4u;
static const uint UI_LABEL_CLEAR = 5u;
static const uint UI_LABEL_RADIUS = 6u;
static const uint UI_LABEL_FIELDS = 7u;
static const uint UI_LABEL_ENERGY = 8u;
static const uint UI_LABEL_KEYS = 9u;
static const uint UI_LABEL_LIVE = 10u;
static const uint UI_LABEL_CONTROL_PRESS_MODE = 11u;
static const uint UI_LABEL_CONTROL_SHEAR_MODE = 12u;
static const uint UI_LABEL_CONTROL_VOID_MODE = 13u;
static const uint UI_LABEL_CONTROL_CLEAR_FIELDS = 14u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 21;
    if (labelId == 1u) return 23;
    if (labelId == 2u) return 8;
    if (labelId == 3u) return 5;
    if (labelId == 4u) return 4;
    if (labelId == 5u) return 5;
    if (labelId == 6u) return 6;
    if (labelId == 7u) return 6;
    if (labelId == 8u) return 6;
    if (labelId == 9u) return 13;
    if (labelId == 10u) return 4;
    if (labelId == 11u) return 8;
    if (labelId == 12u) return 5;
    if (labelId == 13u) return 4;
    if (labelId == 14u) return 5;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[21] = { 65, 88, 73, 79, 77, 32, 47, 32, 80, 82, 69, 83, 83, 85, 82, 69, 32, 68, 69, 83, 75 };
        return characterIndex >= 0 && characterIndex < 21 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[23] = { 83, 80, 65, 84, 73, 65, 76, 32, 70, 79, 82, 67, 69, 32, 65, 85, 84, 72, 79, 82, 73, 78, 71 };
        return characterIndex >= 0 && characterIndex < 23 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[8] = { 80, 82, 69, 83, 83, 85, 82, 69 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[5] = { 83, 72, 69, 65, 82 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[4] = { 86, 79, 73, 68 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[5] = { 67, 76, 69, 65, 82 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[6] = { 82, 65, 68, 73, 85, 83 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[6] = { 70, 73, 69, 76, 68, 83 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[6] = { 69, 78, 69, 82, 71, 89 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[13] = { 80, 32, 47, 32, 83, 32, 47, 32, 86, 32, 47, 32, 88 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[4] = { 76, 73, 86, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[8] = { 80, 114, 101, 115, 115, 117, 114, 101 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 12u) {
        int codes[5] = { 83, 104, 101, 97, 114 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 13u) {
        int codes[4] = { 86, 111, 105, 100 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 14u) {
        int codes[5] = { 67, 108, 101, 97, 114 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
