// Generated by tools/phage_labels.py. Edit the generator, not this file.
#ifndef PH_LABELS_HLSLI
#define PH_LABELS_HLSLI
static const uint PH_LBL_CH[269]={80,72,65,71,69,32,47,32,67,79,78,83,84,82,85,67,84,73,79,78,32,80,76,65,78,80,76,65,78,83,69,67,84,73,79,78,32,84,72,82,79,85,71,72,32,76,69,71,65,85,68,73,69,78,67,69,68,82,65,71,32,70,69,69,84,32,73,78,32,80,76,65,78,44,32,75,78,69,69,83,32,73,78,32,83,69,67,84,73,79,78,46,32,32,49,45,54,32,76,69,71,32,32,83,32,83,89,77,77,69,84,82,89,32,32,82,32,82,69,83,69,84,32,32,69,83,67,32,67,76,69,65,82,83,89,77,32,79,78,83,89,77,32,79,70,70,85,80,80,69,82,76,79,87,69,82,82,69,65,67,72,79,85,84,32,79,70,32,82,69,65,67,72,75,78,69,69,32,66,69,76,79,87,32,72,73,80,70,69,69,84,32,67,76,65,83,72,83,84,65,78,67,69,82,69,70,69,82,69,78,67,69,83,80,73,68,69,82,77,65,78,84,73,83,67,82,65,66,77,79,86,69,82,83,83,84,82,79,66,69,83,66,65,82,83,77,72,69,65,68,32,67,76,69,65,82,65,78,67,69,69,68,73,84,69,68,37,68,74};
static const uint2 PH_LBL_RANGE[26]={uint2(0,25),uint2(25,4),uint2(29,19),uint2(48,8),uint2(56,77),uint2(133,6),uint2(139,7),uint2(146,5),uint2(151,5),uint2(156,5),uint2(161,12),uint2(173,14),uint2(187,10),uint2(197,6),uint2(203,9),uint2(212,6),uint2(218,6),uint2(224,4),uint2(228,6),uint2(234,7),uint2(241,4),uint2(245,1),uint2(246,14),uint2(260,6),uint2(266,1),uint2(267,2)};
float phLabelWidth(uint id,float s){return (float)PH_LBL_RANGE[id].y*SUI3_ADVANCE*s;}
float phLabel(float2 P,float2 anchor,float s,uint id){
 uint2 r=PH_LBL_RANGE[id];if(sui3RunMiss(P,anchor,s,(int)r.y))return 0;
 int k=(int)floor((P.x-anchor.x)/(SUI3_ADVANCE*s));if(k<0||k>=(int)r.y)return 0;
 float cov=sui3Glyph(P,anchor+float2((float)k*SUI3_ADVANCE*s,0),s,(int)PH_LBL_CH[r.x+(uint)k]);
 if(k>0)cov=max(cov,sui3Glyph(P,anchor+float2((float)(k-1)*SUI3_ADVANCE*s,0),s,(int)PH_LBL_CH[r.x+(uint)k-1]));
 return cov;}
#endif
