#ifndef MICRO_ENVELOPE_UI_GENERATED_HLSLI
#define MICRO_ENVELOPE_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 77364344d1c26812ec699f004e79a758c6b7fa118fa9ef0862165657cf480be4
static const uint UI_CONTROL_COUNT = 3u;
static const uint UI_LABEL_COUNT = 3u;
static const uint4 UI_MANIFEST_HASH = uint4(0x77364344u, 0xd1c26812u, 0xec699f00u, 0x4e79a758u);

static const uint UI_INDEX_GATE = 0u;
static const float4 UI_RECT_GATE = float4(0.55, 0.21, 0.95, 0.35);
static const uint UI_INDEX_ATTACK = 1u;
static const float4 UI_RECT_ATTACK = float4(0.55, 0.475, 0.95, 0.615);
static const uint UI_INDEX_RELEASE = 2u;
static const float4 UI_RECT_RELEASE = float4(0.55, 0.74, 0.95, 0.88);

static const uint UI_LABEL_CONTROL_GATE = 0u;
static const uint UI_LABEL_CONTROL_ATTACK = 1u;
static const uint UI_LABEL_CONTROL_RELEASE = 2u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 4;
    if (labelId == 1u) return 6;
    if (labelId == 2u) return 7;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[4] = { 71, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[6] = { 65, 116, 116, 97, 99, 107 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[7] = { 82, 101, 108, 101, 97, 115, 101 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
