#ifndef _3D_TRANSFORM_GIZMO_LAB_UI_GENERATED_HLSLI
#define _3D_TRANSFORM_GIZMO_LAB_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: b31f7fb55131440f2271e754a7b58493c1db167fe8432b3fe56e00030411407b
static const uint UI_CONTROL_COUNT = 4u;
static const uint UI_LABEL_COUNT = 10u;
static const uint4 UI_MANIFEST_HASH = uint4(0xb31f7fb5u, 0x5131440fu, 0x2271e754u, 0xa7b58493u);

static const uint UI_INDEX_TRANSLATE = 0u;
static const float4 UI_RECT_TRANSLATE = float4(0.285, 0.024, 0.394, 0.094);
static const uint UI_INDEX_ROTATE = 1u;
static const float4 UI_RECT_ROTATE = float4(0.406, 0.024, 0.502, 0.094);
static const uint UI_INDEX_SCALE = 2u;
static const float4 UI_RECT_SCALE = float4(0.515, 0.024, 0.602, 0.094);
static const uint UI_INDEX_LOCAL = 3u;
static const float4 UI_RECT_LOCAL = float4(0.617, 0.024, 0.731, 0.094);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_SELECTED = 1u;
static const uint UI_LABEL_MOVE = 2u;
static const uint UI_LABEL_ROTATE = 3u;
static const uint UI_LABEL_SCALE = 4u;
static const uint UI_LABEL_LOCAL = 5u;
static const uint UI_LABEL_CONTROL_TRANSLATE = 6u;
static const uint UI_LABEL_CONTROL_ROTATE = 7u;
static const uint UI_LABEL_CONTROL_SCALE = 8u;
static const uint UI_LABEL_CONTROL_LOCAL = 9u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 16;
    if (labelId == 1u) return 8;
    if (labelId == 2u) return 4;
    if (labelId == 3u) return 3;
    if (labelId == 4u) return 5;
    if (labelId == 5u) return 5;
    if (labelId == 6u) return 14;
    if (labelId == 7u) return 11;
    if (labelId == 8u) return 10;
    if (labelId == 9u) return 13;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[16] = { 84, 82, 65, 78, 83, 70, 79, 82, 77, 32, 76, 65, 66, 32, 51, 68 };
        return characterIndex >= 0 && characterIndex < 16 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[8] = { 83, 69, 76, 69, 67, 84, 69, 68 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[4] = { 77, 79, 86, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[3] = { 82, 79, 84 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[5] = { 83, 67, 65, 76, 69 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[5] = { 76, 79, 67, 65, 76 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[14] = { 84, 114, 97, 110, 115, 108, 97, 116, 101, 32, 77, 111, 100, 101 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[11] = { 82, 111, 116, 97, 116, 101, 32, 77, 111, 100, 101 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[10] = { 83, 99, 97, 108, 101, 32, 77, 111, 100, 101 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[13] = { 87, 111, 114, 108, 100, 32, 47, 32, 76, 111, 99, 97, 108 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
