#ifndef LIVING_ROOM_LIGHTING_DESK_UI_GENERATED_HLSLI
#define LIVING_ROOM_LIGHTING_DESK_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 1ed45d2a8e324a1e527746eb2e0ae82124eb9aa5cb0128cce2fae93db919c720
static const uint UI_CONTROL_COUNT = 4u;
static const uint UI_LABEL_COUNT = 15u;
static const uint4 UI_MANIFEST_HASH = uint4(0x1ed45d2au, 0x8e324a1eu, 0x527746ebu, 0x2e0ae821u);

static const uint UI_INDEX_DAYLIGHT = 0u;
static const float4 UI_RECT_DAYLIGHT = float4(0.692, 0.32, 0.948, 0.385);
static const uint UI_INDEX_PRACTICAL = 1u;
static const float4 UI_RECT_PRACTICAL = float4(0.692, 0.46, 0.948, 0.525);
static const uint UI_INDEX_AMBIENT = 2u;
static const float4 UI_RECT_AMBIENT = float4(0.692, 0.6, 0.948, 0.665);
static const uint UI_INDEX_SOFTNESS = 3u;
static const float4 UI_RECT_SOFTNESS = float4(0.692, 0.74, 0.948, 0.805);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_SUBTITLE = 1u;
static const uint UI_LABEL_CONTROLS = 2u;
static const uint UI_LABEL_DAYLIGHT = 3u;
static const uint UI_LABEL_PRACTICAL = 4u;
static const uint UI_LABEL_AMBIENT = 5u;
static const uint UI_LABEL_SOFTNESS = 6u;
static const uint UI_LABEL_LEGEND = 7u;
static const uint UI_LABEL_DAY = 8u;
static const uint UI_LABEL_LAMPS = 9u;
static const uint UI_LABEL_FILL = 10u;
static const uint UI_LABEL_CONTROL_DAYLIGHT = 11u;
static const uint UI_LABEL_CONTROL_PRACTICAL = 12u;
static const uint UI_LABEL_CONTROL_AMBIENT = 13u;
static const uint UI_LABEL_CONTROL_SOFTNESS = 14u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 13;
    if (labelId == 1u) return 49;
    if (labelId == 2u) return 17;
    if (labelId == 3u) return 15;
    if (labelId == 4u) return 15;
    if (labelId == 5u) return 12;
    if (labelId == 6u) return 15;
    if (labelId == 7u) return 11;
    if (labelId == 8u) return 3;
    if (labelId == 9u) return 5;
    if (labelId == 10u) return 4;
    if (labelId == 11u) return 15;
    if (labelId == 12u) return 15;
    if (labelId == 13u) return 12;
    if (labelId == 14u) return 15;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[13] = { 76, 73, 71, 72, 84, 73, 78, 71, 32, 68, 69, 83, 75 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[49] = { 54, 32, 76, 73, 86, 69, 32, 76, 73, 71, 72, 84, 32, 82, 69, 67, 79, 82, 68, 83, 32, 47, 32, 65, 82, 67, 72, 73, 84, 69, 67, 84, 85, 82, 69, 32, 43, 32, 70, 85, 82, 78, 73, 83, 72, 73, 78, 71, 83 };
        return characterIndex >= 0 && characterIndex < 49 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[17] = { 76, 73, 71, 72, 84, 73, 78, 71, 32, 67, 79, 78, 84, 82, 79, 76, 83 };
        return characterIndex >= 0 && characterIndex < 17 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[15] = { 87, 73, 78, 68, 79, 87, 32, 68, 65, 89, 76, 73, 71, 72, 84 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[15] = { 80, 82, 65, 67, 84, 73, 67, 65, 76, 32, 76, 65, 77, 80, 83 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[12] = { 65, 77, 66, 73, 69, 78, 84, 32, 70, 73, 76, 76 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[15] = { 83, 72, 65, 68, 79, 87, 32, 83, 79, 70, 84, 78, 69, 83, 83 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[11] = { 76, 73, 71, 72, 84, 32, 84, 89, 80, 69, 83 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[3] = { 68, 65, 89 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[5] = { 76, 65, 77, 80, 83 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[4] = { 70, 73, 76, 76 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[15] = { 87, 105, 110, 100, 111, 119, 32, 68, 97, 121, 108, 105, 103, 104, 116 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 12u) {
        int codes[15] = { 80, 114, 97, 99, 116, 105, 99, 97, 108, 32, 76, 97, 109, 112, 115 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 13u) {
        int codes[12] = { 65, 109, 98, 105, 101, 110, 116, 32, 70, 105, 108, 108 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 14u) {
        int codes[15] = { 83, 104, 97, 100, 111, 119, 32, 83, 111, 102, 116, 110, 101, 115, 115 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
