// KA_Cell / plan.hlsl — authors the robot cell into a durable record buffer.
//
// Single-threaded on purpose: the viewport event queue must be reduced in order and 48 records
// is nothing next to a render pass.
//
// AN ARRAY'S IDENTITY IS ITS LATTICE. That is why `variation` perturbs LATTICE PARAMETERS —
// pitch, rows, stagger, radius, span, skew, convergence — and then jitters each station inside
// its own cell, instead of drawing a fresh coordinate per arm. A free draw over 48 machines
// does not read as a different cell layout; it reads as a scrapyard. variation = 0 is exactly
// the arrangement the enum names, so it can never be lost.
//
// Regeneration is signature-driven. Structural parameters and the R-key salt rebuild; anything
// else preserves the buffer, so a hand-placed cell survives cooks, saves, presets and undo.
#include "../_shared/cell.hlsli"
#include "layout.hlsli"

RWStructuredBuffer<KaRec> Cell : register(u0);

// Bump when the LAYOUT ALGORITHM changes, or the persistent buffer will keep serving the cell
// generated by the previous version and the change will silently do nothing.
#define PLAN_VERSION 1.0

// ---------------------------------------------------------------------------
// The lattice, with the randomizer applied to it. No seed reaches this from the canvas: the
// canvas rebuilds the armature from exactly this function so the guides it draws are the guides
// the layout used, not a published copy that can drift.
// ---------------------------------------------------------------------------
KaLattice cellLattice(float s, float v)
{
    KaLattice L;
    L.pitch   = lerp(pitch,            pitch  * lerp(0.62, 1.55, ka_rnd(s, 1.0)), v);
    L.rows    = lerp((float)rows,      floor(lerp(1.0, 6.99, ka_rnd(s, 2.0))),    v);
    L.stagger = lerp(stagger,          ka_srnd(s, 3.0),                            v);
    L.radius  = lerp(radius,           radius * lerp(0.62, 1.55, ka_rnd(s, 4.0)), v);
    L.span    = lerp(span * KA_D2R,    lerp(60.0, 320.0, ka_rnd(s, 5.0)) * KA_D2R, v);
    L.skew    = lerp(skew * KA_D2R,    ka_srnd(s, 6.0) * 0.85,                     v);
    L.conv    = lerp(converge,         ka_rnd(s, 7.0),                             v);
    L.rows    = max(L.rows, 1.0);
    L.pitch   = max(L.pitch, 0.8);
    return L;
}

// Which control channel an arm belongs to. Every mode is DERIVED FROM THE PLACEMENT the lattice
// already decided, so changing the arrangement re-splits the channels coherently instead of
// leaving a routing table that no longer matches the floor.
float channelOf(uint i, float2 p, float pit, float g)
{
    int mode = (int)group_mode;
    float G = max(g, 1.0);
    float k = 0.0;
    if (mode == 1)      k = floor((p.y + 512.0) / pit);                      // by row (depth band)
    else if (mode == 2) k = floor(length(p) / max(pit, 0.5));                // by ring
    else if (mode == 3) k = floor((p.x + 512.0) / pit) + floor((p.y + 512.0) / pit); // checker
    else if (mode == 4) k = floor((atan2(p.y, p.x) + KA_PI) / KA_TAU * G);   // quadrant sectors
    else if (mode == 5) k = (float)i;                                        // alternate
    else if (mode == 6) k = floor(ka_rnd((float)i * 7.31 + 3.0, 61.0) * G);  // scattered
    else                k = 0.0;                                             // all one
    return fmod(fmod(k, G) + G, G);
}

float frameKindOf(uint i, uint n)
{
    int mix = (int)frame_mix;
    float b = (float)frame_base;
    if (mix == 1) return clamp(b + fmod((float)i, 2.0), 0.0, 2.0);                       // alternate
    if (mix == 2) return floor(saturate((float)i / max((float)n - 1.0, 1.0)) * 2.999);   // graded
    if (mix == 3) return floor(ka_rnd((float)i * 3.77 + 19.0, 5.0) * 2.999);             // scattered
    return b;
}

void buildCell(float s)
{
    uint want = (uint)clamp((float)arm_count, 0.0, (float)KA_MAX_ARMS);
    float v = saturate(variation);
    KaLattice L = cellLattice(s, v);
    int arr = (int)clamp((float)arrangement, 0.0, (float)(KA_ARR_COUNT - 1));

    for (uint i = 0u; i < KA_MAX_ARMS; i++)
    {
        KaRec r = (KaRec)0;
        // A per-station stream separate from r.seed, so re-rolling ONE arm with N does not
        // shift what every other station drew.
        float rs = s * 13.3 + (float)i * 29.7 + 7.0;

        float2 p; float hd;
        ka_station(arr, i, max(want, 1u), L, p, hd);

        // Jitter INSIDE the station's own cell. The lattice survives; the regularity softens.
        // Capped at 0.28 pitch so neighbouring stations can never swap places, which is what
        // turns a perturbed array back into scatter.
        p  += float2(ka_srnd(rs, 3.0), ka_srnd(rs, 4.0)) * (L.pitch * 0.28 * v);
        hd += ka_srnd(rs, 5.0) * v * 0.55;

        r.pos    = p;
        r.kind   = frameKindOf(i, want);
        // Temper the scale draw toward the mean: an untempered spread turns the smallest frame
        // into a bollard next to the largest, and the cell stops reading as a fleet.
        r.size.x = max(frame_scale * (1.0 + ka_srnd(rs, 6.0) * scale_spread * 0.8), 0.30);
        r.size.y = max(pedestal, 0.0);
        r.yaw    = hd;
        r.grp    = channelOf(i, p, L.pitch, (float)group_count);
        r.bias   = ka_rnd(rs, 8.0) * saturate(bias_spread);
        r.seed   = s * 5.7 + (float)i * 17.0 + 1.0;
        r.flags  = 0.0;
        r.active = (i < want) ? 1.0 : 0.0;
        r.spare  = 0.0;
        Cell[KA_ARM_0 + i] = r;
    }
}

// The target is rebuilt with the cell but its ORBIT PHASE is carried across, because a phase is
// a clock and re-rolling a layout must never jog a clock.
void buildTarget()
{
    KaRec old = Cell[KA_TARGET];
    KaRec t = (KaRec)0;
    t.pos    = float2(target_x, target_z);
    t.size   = float2(target_h, target_orbit);
    t.yaw    = target_rate;
    t.bias   = old.bias;
    t.kind   = 0.0;
    t.seed   = 3.0;
    t.flags  = 0.0;
    t.active = 1.0;
    Cell[KA_TARGET] = t;
}

// Tallest standing machine in the cell, used to fit the elevation strip.
float scanRise()
{
    float mr = 1.0;
    for (uint i = 0u; i < KA_MAX_ARMS; i++)
    {
        KaRec r = Cell[KA_ARM_0 + i];
        if (r.active > 0.5) mr = max(mr, ka_rise(ka_spec(r.kind, r.size.x), r.size.y));
    }
    return mr;
}

// Nearest pickable arm under a diagram point. Smallest hit wins so a compact frame standing in
// front of a heavy one stays reachable.
uint pickArm(KaMap m, float2 uv, int strip)
{
    uint best = 0u; float bestScore = 1e9;
    float2 asp = float2(m.res.x / max(m.res.y, 1.0), 1.0);

    // The target first, and with a generous grab radius: it is a small mark sitting on top of a
    // busy diagram, and smallest-hit-wins would otherwise make it nearly impossible to catch.
    {
        KaRec t = Cell[KA_TARGET];
        float3 tp = ka_targetPos(t);
        float2 hp = (strip == 1) ? kaPlanUV(m, float2(tp.x, tp.z)) : kaElevUV(m, tp.x, tp.y);
        float d = length((uv - hp) * asp);
        if (d < 0.022) { bestScore = d; best = KA_TARGET + 1u; }
    }

    for (uint i = 0u; i < KA_MAX_ARMS; i++)
    {
        KaRec r = Cell[KA_ARM_0 + i];
        if (r.active < 0.5) continue;
        KaSpec sp = ka_spec(r.kind, r.size.x);

        float2 hp;
        float rad;
        if (strip == 1)
        {
            hp  = kaPlanUV(m, r.pos);
            rad = max(kaLenX(m, sp.ped_r * 1.15), 0.013);
        }
        else
        {
            hp  = kaElevUV(m, r.pos.x, r.size.y + sp.turret * 0.5);
            rad = max(kaLenX(m, sp.ped_r * 1.15), 0.013);
        }
        float d = length((uv - hp) * asp);
        if (d < rad && d < bestScore) { bestScore = d; best = KA_ARM_0 + i + 1u; }
    }
    return best;
}

[numthreads(1, 1, 1)]
void main(uint3 DTid : SV_DispatchThreadID)
{
    KaRec hdr = Cell[KA_HEADER];
    float initFlag = hdr.active;
    float salt     = hdr.seed;
    float sel      = hdr.pos.y;    // selected index + 1
    float dragOn   = hdr.size.x;   // 0 none, 1 plan strip, 2 elevation strip
    float2 grab    = float2(hdr.size.y, hdr.yaw);

    uint n = min((uint)_ViewportEventCount, 64u);

    // --- pass 1: keys. R changes the salt, so it lands before the signature test.
    for (uint e = 0u; e < n; e++)
    {
        ViewportEvent ev = _ViewportEvents[e];
        if (ev.type == 4u && ev.phase == 1u)
        {
            uint c = (uint)ev.code;
            if (c == 18u) salt += 1.0;                    // R  reseed the cell
            else if (c == 3u) sel = 0.0;                  // C  clear selection
            else if (sel > 0.5)
            {
                uint idx = (uint)(sel - 1.0);
                KaRec r = Cell[idx];
                uint fl = (uint)r.flags;
                if (c == 1u)       { r.yaw += 15.0 * KA_D2R; }                        // A turn CCW
                else if (c == 4u)  { r.yaw -= 15.0 * KA_D2R; }                        // D turn CW
                else if (c == 7u)  { r.grp = fmod(r.grp + 1.0, max((float)group_count, 1.0)); } // G
                else if (c == 11u) { r.kind = fmod(r.kind + 1.0, 3.0); }              // K frame size
                else if (c == 5u)  { r.size.x = min(r.size.x * 1.12, 2.60); }         // E larger
                else if (c == 17u) { r.size.x = max(r.size.x * 0.893, 0.30); }        // Q smaller
                else if (c == 24u) { r.active = (r.active > 0.5) ? 0.0 : 1.0; }       // X on/off
                else if (c == 14u)                                                    // N re-roll
                {
                    r.seed += 7.77;
                    r.bias = ka_rnd(r.seed, 8.0) * max(saturate(bias_spread), 0.15);
                    r.yaw += ka_srnd(r.seed, 9.0) * 0.9;
                }
                if (c == 1u || c == 4u || c == 7u || c == 11u || c == 5u ||
                    c == 17u || c == 24u || c == 14u)
                    r.flags = (float)(fl | KF_EDITED);
                Cell[idx] = r;
            }
        }
    }

    float sig = (float)arrangement * 37.7 + (float)arm_count * 1.13 + pitch * 7.31
              + (float)rows * 5.17 + radius * 3.71 + span * 0.271 + skew * 0.533
              + stagger * 11.9 + converge * 23.7 + variation * 137.9 + seed * 2.19
              + (float)frame_base * 61.3 + (float)frame_mix * 71.9 + frame_scale * 43.1
              + scale_spread * 29.3 + (float)group_mode * 83.9 + (float)group_count * 97.1
              + bias_spread * 17.3 + salt * 101.3 + PLAN_VERSION * 911.7;

    if (initFlag < 0.5 || abs(sig - hdr.pos.x) > 1e-4)
    {
        buildCell(seed + salt * 3.19);
        buildTarget();
        sel = 0.0; dragOn = 0.0;
    }

    // The diagram scale is computed BEFORE the pointer pass and republished in the header, so
    // the canvas draws on exactly the scale this pass picked with.
    float maxRise = scanRise();
    KaMap map = kaMap(_Resolution.xy, cell_w, cell_d, maxRise);

    // --- pass 2: pointer.
    for (uint e2 = 0u; e2 < n; e2++)
    {
        ViewportEvent ev = _ViewportEvents[e2];
        if (ev.type != 5u) continue;
        float2 p = ev.position;

        if (ev.code == 1u && ev.phase == 7u)              // click: select
        {
            int st = kaStrip(p);
            sel = (st == 0) ? 0.0 : (float)pickArm(map, p, st);
        }
        else if (ev.code == 3u)                           // drag
        {
            if (ev.phase == 5u)                           // begin: acquire the handle once
            {
                int st = kaStrip(p);
                dragOn = 0.0;
                uint hit = (st == 0) ? 0u : pickArm(map, p, st);
                sel = (float)hit;
                if (hit != 0u)
                {
                    uint hidx = hit - 1u;
                    KaRec r = Cell[hidx];
                    dragOn = (float)st;
                    if (hidx == KA_TARGET)
                    {
                        // Grabbing the target grabs its LIVE orbiting point but moves its
                        // ANCHOR, so the orbit keeps running under your hand.
                        float3 tp = ka_targetPos(r);
                        if (st == 1) grab = r.pos - kaUVPlan(map, p);
                        else         grab = float2(r.pos.x - kaUVElevX(map, p.x),
                                                   r.size.x - kaUVElevH(map, p.y));
                    }
                    else
                    {
                        KaSpec sp = ka_spec(r.kind, r.size.x);
                        if (st == 1) grab = r.pos - kaUVPlan(map, p);
                        else         grab = float2(r.pos.x - kaUVElevX(map, p.x),
                                                   r.size.y - (kaUVElevH(map, p.y) - sp.turret * 0.5));
                    }
                }
            }
            else if (ev.phase == 6u && dragOn > 0.5 && sel > 0.5)
            {
                uint idx = (uint)(sel - 1.0);
                KaRec r = Cell[idx];
                KaSpec sp = ka_spec(r.kind, r.size.x);
                if (idx == KA_TARGET)
                {
                    if ((int)dragOn == 1) r.pos = clamp(kaUVPlan(map, p) + grab, -60.0, 60.0);
                    else
                    {
                        r.pos.x  = clamp(kaUVElevX(map, p.x) + grab.x, -60.0, 60.0);
                        r.size.x = clamp(kaUVElevH(map, p.y) + grab.y, 0.0, 14.0);
                    }
                    r.flags = (float)(((uint)r.flags) | KF_EDITED);
                    Cell[idx] = r;
                }
                else if ((int)dragOn == 1)
                {
                    // plan strip: the floor position, both axes
                    r.pos = clamp(kaUVPlan(map, p) + grab, -60.0, 60.0);
                    r.active = 1.0;
                    r.flags = (float)(((uint)r.flags) | KF_EDITED);
                    Cell[idx] = r;
                }
                else
                {
                    // elevation strip: the SAME handle, but this projection owns the pedestal.
                    // x still tracks, because x is the axis the two strips share.
                    r.pos.x  = clamp(kaUVElevX(map, p.x) + grab.x, -60.0, 60.0);
                    r.size.y = clamp(kaUVElevH(map, p.y) - sp.turret * 0.5 + grab.y, 0.0, 6.0);
                    r.active = 1.0;
                    r.flags = (float)(((uint)r.flags) | KF_EDITED);
                    Cell[idx] = r;
                }
            }
            else { dragOn = 0.0; }
        }
    }

    // Appearance-only refresh: the pedestal follows its parameter on arms nobody has touched,
    // and stays put on arms that were hand-set in the elevation strip.
    for (uint a = 0u; a < KA_MAX_ARMS; a++)
    {
        KaRec r = Cell[KA_ARM_0 + a];
        if (((uint)r.flags & KF_EDITED) == 0u) r.size.y = max(pedestal, 0.0);
        Cell[KA_ARM_0 + a] = r;
    }

    // Target: params keep driving it until somebody drags it, then the record wins. Its orbit
    // phase is integrated against _DeltaTime — never rate x absolute time — so changing the rate
    // mid-show moves the target smoothly instead of teleporting it.
    {
        KaRec t = Cell[KA_TARGET];
        if (((uint)t.flags & KF_EDITED) == 0u)
        {
            t.pos = float2(target_x, target_z);
            t.size.x = target_h;
        }
        t.size.y = max(target_orbit, 0.0);
        t.yaw    = target_rate;
        t.bias   = frac(t.bias + _DeltaTime * target_rate + 1.0);
        t.active = 1.0;
        uint tf = (uint)t.flags & ~KF_SELECTED;
        if (sel > 0.5 && (uint)(sel - 1.0) == KA_TARGET) tf |= KF_SELECTED;
        t.flags = (float)tf;
        Cell[KA_TARGET] = t;
    }

    // --- derived state. Selection is stored ONCE in the header; every "am I selected" test
    // reads the flag this loop writes, so the two can never disagree.
    float halfW = cell_w * 0.5, halfD = cell_d * 0.5;
    uint live = 0u, pairs = 0u;
    for (uint i2 = 0u; i2 < KA_MAX_ARMS; i2++)
    {
        KaRec r = Cell[KA_ARM_0 + i2];
        uint f = (uint)r.flags & ~(KF_SELECTED | KF_OVERLAP | KF_OUTSIDE);
        if (sel > 0.5 && (uint)(sel - 1.0) == (KA_ARM_0 + i2)) f |= KF_SELECTED;
        if (r.active > 0.5)
        {
            live++;
            if (abs(r.pos.x) > halfW || abs(r.pos.y) > halfD) f |= KF_OUTSIDE;
        }
        r.flags = (float)f;
        Cell[KA_ARM_0 + i2] = r;
    }

    // Envelope intersection: two arms that can reach the same air can strike each other. This
    // is the one thing about a cell layout that is genuinely BROKEN, so it earns alarm red in
    // the diagram and a live pair count in the readout.
    for (uint i3 = 0u; i3 < KA_MAX_ARMS; i3++)
    {
        KaRec a3 = Cell[KA_ARM_0 + i3];
        if (a3.active < 0.5) continue;
        float ra = ka_reachOf(a3);
        for (uint j3 = i3 + 1u; j3 < KA_MAX_ARMS; j3++)
        {
            KaRec b3 = Cell[KA_ARM_0 + j3];
            if (b3.active < 0.5) continue;
            if (length(a3.pos - b3.pos) < ra + ka_reachOf(b3))
            {
                pairs++;
                a3.flags = (float)((uint)a3.flags | KF_OVERLAP);
                b3.flags = (float)((uint)b3.flags | KF_OVERLAP);
                Cell[KA_ARM_0 + j3] = b3;
            }
        }
        Cell[KA_ARM_0 + i3] = a3;
    }

    hdr.pos    = float2(sig, sel);
    hdr.size   = float2(dragOn, grab.x);
    hdr.yaw    = grab.y;
    hdr.grp    = (float)live;
    hdr.kind   = (float)pairs;
    hdr.bias   = cell_w;
    hdr.seed   = salt;
    hdr.flags  = cell_d;
    hdr.active = 1.0;
    hdr.spare  = maxRise;
    Cell[KA_HEADER] = hdr;
}
