#ifndef MICRO_LFO_UI_GENERATED_HLSLI
#define MICRO_LFO_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 15c2bc2ba5ad068ce576168552c4cd78bdacc3957c03085e996de75b56ea75a2
static const uint UI_CONTROL_COUNT = 3u;
static const uint UI_LABEL_COUNT = 3u;
static const uint4 UI_MANIFEST_HASH = uint4(0x15c2bc2bu, 0xa5ad068cu, 0xe5761685u, 0x52c4cd78u);

static const uint UI_INDEX_RATE = 0u;
static const float4 UI_RECT_RATE = float4(0.56, 0.205, 0.95, 0.37);
static const uint UI_INDEX_DEPTH = 1u;
static const float4 UI_RECT_DEPTH = float4(0.56, 0.485, 0.95, 0.65);
static const uint UI_INDEX_SHAPE = 2u;
static const float4 UI_RECT_SHAPE = float4(0.56, 0.765, 0.95, 0.93);

static const uint UI_LABEL_CONTROL_RATE = 0u;
static const uint UI_LABEL_CONTROL_DEPTH = 1u;
static const uint UI_LABEL_CONTROL_SHAPE = 2u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 4;
    if (labelId == 1u) return 5;
    if (labelId == 2u) return 5;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[4] = { 82, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[5] = { 68, 101, 112, 116, 104 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[5] = { 83, 104, 97, 112, 101 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
