#ifndef DESERT_WARP_DECK_UI_GENERATED_HLSLI
#define DESERT_WARP_DECK_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 00ae29ac5643ee31b7d847967c17c219c30fcff4029d7829c1b6226790da68dc
static const uint UI_CONTROL_COUNT = 4u;
static const uint UI_LABEL_COUNT = 4u;
static const uint4 UI_MANIFEST_HASH = uint4(0x00ae29acu, 0x5643ee31u, 0xb7d84796u, 0x7c17c219u);

static const uint UI_INDEX_MELT_MACRO = 0u;
static const float4 UI_RECT_MELT_MACRO = float4(0.055, 0.65, 0.475, 0.735);
static const uint UI_INDEX_SAG_MACRO = 1u;
static const float4 UI_RECT_SAG_MACRO = float4(0.525, 0.65, 0.945, 0.735);
static const uint UI_INDEX_WARP_PRIMARY = 2u;
static const float4 UI_RECT_WARP_PRIMARY = float4(0.055, 0.815, 0.475, 0.9);
static const uint UI_INDEX_WARP_SECONDARY = 3u;
static const float4 UI_RECT_WARP_SECONDARY = float4(0.525, 0.815, 0.945, 0.9);

static const uint UI_LABEL_CONTROL_MELT_MACRO = 0u;
static const uint UI_LABEL_CONTROL_SAG_MACRO = 1u;
static const uint UI_LABEL_CONTROL_WARP_PRIMARY = 2u;
static const uint UI_LABEL_CONTROL_WARP_SECONDARY = 3u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 12;
    if (labelId == 1u) return 11;
    if (labelId == 2u) return 12;
    if (labelId == 3u) return 14;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[12] = { 77, 101, 108, 116, 32, 71, 101, 115, 116, 117, 114, 101 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[11] = { 83, 97, 103, 32, 71, 101, 115, 116, 117, 114, 101 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[12] = { 80, 114, 105, 109, 97, 114, 121, 32, 87, 97, 114, 112 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[14] = { 83, 101, 99, 111, 110, 100, 97, 114, 121, 32, 87, 97, 114, 112 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
