#ifndef DESERT_WARP_BUS_UI_GENERATED_HLSLI
#define DESERT_WARP_BUS_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: e07f197dfe5e02f800cce8fe0db0163e0c7869e059ba51810063f433bf240cb4
static const uint UI_CONTROL_COUNT = 0u;
static const uint UI_LABEL_COUNT = 0u;
static const uint4 UI_MANIFEST_HASH = uint4(0xe07f197du, 0xfe5e02f8u, 0x00cce8feu, 0x0db0163eu);



int uiLabelLength(uint labelId) {
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    return 32;
}

#endif
