#ifndef VARIANT_SWITCHER_UI_UI_GENERATED_HLSLI
#define VARIANT_SWITCHER_UI_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 46b57176afabda08e69409f33e2a8ed305529368d125f813868825f88ad4250b
static const uint UI_CONTROL_COUNT = 4u;
static const uint UI_LABEL_COUNT = 6u;
static const uint4 UI_MANIFEST_HASH = uint4(0x46b57176u, 0xafabda08u, 0xe69409f3u, 0x3e2a8ed3u);

static const uint UI_INDEX_AUTO_MODE = 0u;
static const float4 UI_RECT_AUTO_MODE = float4(0.55, 0.025, 0.68, 0.105);
static const uint UI_INDEX_SELECT_1 = 1u;
static const float4 UI_RECT_SELECT_1 = float4(0.7, 0.025, 0.78, 0.105);
static const uint UI_INDEX_SELECT_2 = 2u;
static const float4 UI_RECT_SELECT_2 = float4(0.8, 0.025, 0.88, 0.105);
static const uint UI_INDEX_SELECT_3 = 3u;
static const float4 UI_RECT_SELECT_3 = float4(0.9, 0.025, 0.98, 0.105);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_SUBTITLE = 1u;
static const uint UI_LABEL_CONTROL_AUTO_MODE = 2u;
static const uint UI_LABEL_CONTROL_SELECT_1 = 3u;
static const uint UI_LABEL_CONTROL_SELECT_2 = 4u;
static const uint UI_LABEL_CONTROL_SELECT_3 = 5u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 23;
    if (labelId == 1u) return 39;
    if (labelId == 2u) return 4;
    if (labelId == 3u) return 1;
    if (labelId == 4u) return 1;
    if (labelId == 5u) return 1;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[23] = { 68, 73, 82, 69, 67, 84, 32, 86, 65, 82, 73, 65, 78, 84, 32, 83, 87, 73, 84, 67, 72, 69, 82 };
        return characterIndex >= 0 && characterIndex < 23 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[39] = { 76, 73, 86, 69, 32, 77, 85, 88, 32, 79, 85, 84, 80, 85, 84, 32, 47, 32, 65, 85, 84, 79, 32, 79, 82, 32, 68, 73, 82, 69, 67, 84, 32, 83, 69, 76, 69, 67, 84 };
        return characterIndex >= 0 && characterIndex < 39 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[4] = { 65, 85, 84, 79 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[1] = { 49 };
        return characterIndex >= 0 && characterIndex < 1 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[1] = { 50 };
        return characterIndex >= 0 && characterIndex < 1 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[1] = { 51 };
        return characterIndex >= 0 && characterIndex < 1 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
