#ifndef FORENSIC_PERFORMANCE_CARTOGRAPHY_UI_GENERATED_HLSLI
#define FORENSIC_PERFORMANCE_CARTOGRAPHY_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 514a8f766215204fba134ab869a5a20c2916b689912272f3eb112e38b5a35a55
static const uint UI_CONTROL_COUNT = 5u;
static const uint UI_LABEL_COUNT = 12u;
static const uint4 UI_MANIFEST_HASH = uint4(0x514a8f76u, 0x6215204fu, 0xba134ab8u, 0x69a5a20cu);

static const uint UI_INDEX_PERFORMANCE_PAD = 0u;
static const float4 UI_RECT_PERFORMANCE_PAD = float4(0.705, 0.225, 0.948, 0.515);
static const uint UI_INDEX_ENERGY = 1u;
static const float4 UI_RECT_ENERGY = float4(0.705, 0.665, 0.948, 0.715);
static const uint UI_INDEX_TOPOLOGY = 2u;
static const float4 UI_RECT_TOPOLOGY = float4(0.705, 0.775, 0.948, 0.825);
static const uint UI_INDEX_ARCHIVE_CUT = 3u;
static const float4 UI_RECT_ARCHIVE_CUT = float4(0.705, 0.885, 0.818, 0.932);
static const uint UI_INDEX_HOLD_MEMORY = 4u;
static const float4 UI_RECT_HOLD_MEMORY = float4(0.835, 0.885, 0.948, 0.932);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_STAGE = 1u;
static const uint UI_LABEL_MACROS = 2u;
static const uint UI_LABEL_EXECUTE = 3u;
static const uint UI_LABEL_MODE_CHOIR = 4u;
static const uint UI_LABEL_MODE_EXCAVATION = 5u;
static const uint UI_LABEL_MODE_SEVERED = 6u;
static const uint UI_LABEL_CONTROL_PERFORMANCE_PAD = 7u;
static const uint UI_LABEL_CONTROL_ENERGY = 8u;
static const uint UI_LABEL_CONTROL_TOPOLOGY = 9u;
static const uint UI_LABEL_CONTROL_ARCHIVE_CUT = 10u;
static const uint UI_LABEL_CONTROL_HOLD_MEMORY = 11u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 40;
    if (labelId == 1u) return 29;
    if (labelId == 2u) return 18;
    if (labelId == 3u) return 19;
    if (labelId == 4u) return 5;
    if (labelId == 5u) return 10;
    if (labelId == 6u) return 7;
    if (labelId == 7u) return 22;
    if (labelId == 8u) return 13;
    if (labelId == 9u) return 13;
    if (labelId == 10u) return 11;
    if (labelId == 11u) return 11;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[40] = { 70, 79, 82, 69, 78, 83, 73, 67, 32, 67, 72, 79, 73, 82, 32, 47, 32, 80, 69, 82, 70, 79, 82, 77, 65, 78, 67, 69, 32, 67, 65, 82, 84, 79, 71, 82, 65, 80, 72, 89 };
        return characterIndex >= 0 && characterIndex < 40 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[29] = { 76, 73, 86, 69, 32, 80, 82, 79, 71, 82, 65, 77, 32, 47, 32, 69, 86, 73, 68, 69, 78, 67, 69, 32, 70, 73, 69, 76, 68 };
        return characterIndex >= 0 && characterIndex < 29 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[18] = { 80, 69, 82, 70, 79, 82, 77, 65, 78, 67, 69, 32, 77, 65, 67, 82, 79, 83 };
        return characterIndex >= 0 && characterIndex < 18 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[19] = { 77, 79, 77, 69, 78, 84, 65, 82, 89, 32, 69, 88, 69, 67, 85, 84, 73, 79, 78 };
        return characterIndex >= 0 && characterIndex < 19 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[5] = { 67, 72, 79, 73, 82 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[10] = { 69, 88, 67, 65, 86, 65, 84, 73, 79, 78 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[7] = { 83, 69, 86, 69, 82, 69, 68 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[22] = { 84, 101, 110, 115, 105, 111, 110, 32, 47, 32, 77, 101, 109, 111, 114, 121, 32, 70, 105, 101, 108, 100 };
        return characterIndex >= 0 && characterIndex < 22 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[13] = { 77, 97, 115, 116, 101, 114, 32, 69, 110, 101, 114, 103, 121 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[13] = { 84, 111, 112, 111, 108, 111, 103, 121, 32, 77, 111, 100, 101 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[11] = { 65, 114, 99, 104, 105, 118, 101, 32, 67, 117, 116 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[11] = { 72, 111, 108, 100, 32, 77, 101, 109, 111, 114, 121 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
