#ifndef TERRITORY_INTERACTION_FIELD_UI_GENERATED_HLSLI
#define TERRITORY_INTERACTION_FIELD_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: abdf5023ff42cd3bdd9103258ebb0efe1e3c13632ffe2128f44aad170993935c
static const uint UI_CONTROL_COUNT = 1u;
static const uint UI_LABEL_COUNT = 6u;
static const uint4 UI_MANIFEST_HASH = uint4(0xabdf5023u, 0xff42cd3bu, 0xdd910325u, 0x8ebb0efeu);

static const uint UI_INDEX_IMPACT_CENTER = 0u;
static const float4 UI_RECT_IMPACT_CENTER = float4(0.305, 0.105, 0.965, 0.735);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_LOOM = 1u;
static const uint UI_LABEL_SEISMIC = 2u;
static const uint UI_LABEL_DISPLACED_STAGE = 3u;
static const uint UI_LABEL_FORCE_TRACE = 4u;
static const uint UI_LABEL_CONTROL_IMPACT_CENTER = 5u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 27;
    if (labelId == 1u) return 12;
    if (labelId == 2u) return 13;
    if (labelId == 3u) return 15;
    if (labelId == 4u) return 16;
    if (labelId == 5u) return 13;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[27] = { 84, 69, 82, 82, 73, 84, 79, 82, 89, 32, 73, 78, 84, 69, 82, 65, 67, 84, 73, 79, 78, 32, 70, 73, 69, 76, 68 };
        return characterIndex >= 0 && characterIndex < 27 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[12] = { 76, 79, 79, 77, 32, 84, 69, 78, 83, 73, 79, 78 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[13] = { 83, 69, 73, 83, 77, 73, 67, 32, 70, 79, 82, 67, 69 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[15] = { 68, 73, 83, 80, 76, 65, 67, 69, 68, 32, 83, 84, 65, 71, 69 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[16] = { 76, 73, 86, 69, 32, 70, 79, 82, 67, 69, 32, 84, 82, 65, 67, 69 };
        return characterIndex >= 0 && characterIndex < 16 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[13] = { 73, 109, 112, 97, 99, 116, 32, 67, 101, 110, 116, 101, 114 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
