// Generated by tools/phage_labels.py. Edit the generator, not this file.
#ifndef PH_LABELS_HLSLI
#define PH_LABELS_HLSLI
static const uint PH_LBL_CH[167]={80,72,65,71,69,32,47,32,83,72,79,87,32,83,84,65,84,69,75,73,67,75,83,78,65,82,69,72,73,45,72,65,84,66,85,73,76,68,80,72,82,65,83,69,66,80,77,66,69,65,84,80,65,76,69,84,84,69,83,65,66,67,83,84,82,79,66,69,66,76,65,67,75,79,85,84,80,82,79,71,82,65,77,77,69,82,82,69,70,69,82,69,78,67,69,32,67,72,65,83,69,75,73,78,69,84,73,67,83,82,65,77,80,72,69,76,68,83,85,82,70,65,67,69,32,76,65,78,69,83,73,78,84,69,82,78,65,76,32,76,65,78,69,83,80,69,82,32,66,69,65,84,68,85,84,89,83,84,79,80,80,69,68,72,79,76,68};
static const uint2 PH_LBL_RANGE[25]={uint2(0,18),uint2(18,4),uint2(22,5),uint2(27,6),uint2(33,5),uint2(38,6),uint2(44,3),uint2(47,4),uint2(51,8),uint2(59,1),uint2(60,1),uint2(61,1),uint2(62,6),uint2(68,8),uint2(76,10),uint2(86,15),uint2(101,8),uint2(109,4),uint2(113,4),uint2(117,13),uint2(130,14),uint2(144,8),uint2(152,4),uint2(156,7),uint2(163,4)};
float phLabelWidth(uint id,float s){return (float)PH_LBL_RANGE[id].y*SUI3_ADVANCE*s;}
float phLabel(float2 P,float2 anchor,float s,uint id){
 uint2 r=PH_LBL_RANGE[id];if(sui3RunMiss(P,anchor,s,(int)r.y))return 0;
 int k=(int)floor((P.x-anchor.x)/(SUI3_ADVANCE*s));if(k<0||k>=(int)r.y)return 0;
 float cov=sui3Glyph(P,anchor+float2((float)k*SUI3_ADVANCE*s,0),s,(int)PH_LBL_CH[r.x+(uint)k]);
 if(k>0)cov=max(cov,sui3Glyph(P,anchor+float2((float)(k-1)*SUI3_ADVANCE*s,0),s,(int)PH_LBL_CH[r.x+(uint)k-1]));
 return cov;}
#endif
