#ifndef KLANGRIG___MARTIN_MOTORS_AND_LIGHT_UI_GENERATED_HLSLI
#define KLANGRIG___MARTIN_MOTORS_AND_LIGHT_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: a5f2b416c78eb87851bd76f8320fd2a1071bd502b0cf19dadef99e7c48735757
static const uint UI_CONTROL_COUNT = 16u;
static const uint UI_LABEL_COUNT = 16u;
static const uint4 UI_MANIFEST_HASH = uint4(0xa5f2b416u, 0xc78eb878u, 0x51bd76f8u, 0x320fd2a1u);

static const uint UI_INDEX_SELECT_ALL = 0u;
static const float4 UI_RECT_SELECT_ALL = float4(0.015, 0.06, 0.127, 0.12);
static const uint UI_INDEX_SELECT_SPINE = 1u;
static const float4 UI_RECT_SELECT_SPINE = float4(0.136, 0.06, 0.248, 0.12);
static const uint UI_INDEX_SELECT_WINGS = 2u;
static const float4 UI_RECT_SELECT_WINGS = float4(0.257, 0.06, 0.369, 0.12);
static const uint UI_INDEX_SELECT_UPPER = 3u;
static const float4 UI_RECT_SELECT_UPPER = float4(0.378, 0.06, 0.49, 0.12);
static const uint UI_INDEX_SELECT_LOWER = 4u;
static const float4 UI_RECT_SELECT_LOWER = float4(0.499, 0.06, 0.611, 0.12);
static const uint UI_INDEX_SELECT_LEFT = 5u;
static const float4 UI_RECT_SELECT_LEFT = float4(0.62, 0.06, 0.732, 0.12);
static const uint UI_INDEX_SELECT_RIGHT = 6u;
static const float4 UI_RECT_SELECT_RIGHT = float4(0.741, 0.06, 0.853, 0.12);
static const uint UI_INDEX_SELECT_LED = 7u;
static const float4 UI_RECT_SELECT_LED = float4(0.862, 0.06, 0.974, 0.12);
static const uint UI_INDEX_SELECT_NONE = 8u;
static const float4 UI_RECT_SELECT_NONE = float4(0.015, 0.13, 0.127, 0.19);
static const uint UI_INDEX_SELECT_BAY1 = 9u;
static const float4 UI_RECT_SELECT_BAY1 = float4(0.136, 0.13, 0.248, 0.19);
static const uint UI_INDEX_SELECT_BAY2 = 10u;
static const float4 UI_RECT_SELECT_BAY2 = float4(0.257, 0.13, 0.369, 0.19);
static const uint UI_INDEX_SELECT_BAY3 = 11u;
static const float4 UI_RECT_SELECT_BAY3 = float4(0.378, 0.13, 0.49, 0.19);
static const uint UI_INDEX_SELECT_CUSTOM1 = 12u;
static const float4 UI_RECT_SELECT_CUSTOM1 = float4(0.499, 0.13, 0.611, 0.19);
static const uint UI_INDEX_SELECT_CUSTOM2 = 13u;
static const float4 UI_RECT_SELECT_CUSTOM2 = float4(0.62, 0.13, 0.732, 0.19);
static const uint UI_INDEX_SELECT_CUSTOM3 = 14u;
static const float4 UI_RECT_SELECT_CUSTOM3 = float4(0.741, 0.13, 0.853, 0.19);
static const uint UI_INDEX_SELECT_CUSTOM4 = 15u;
static const float4 UI_RECT_SELECT_CUSTOM4 = float4(0.862, 0.13, 0.974, 0.19);

static const uint UI_LABEL_CONTROL_SELECT_ALL = 0u;
static const uint UI_LABEL_CONTROL_SELECT_SPINE = 1u;
static const uint UI_LABEL_CONTROL_SELECT_WINGS = 2u;
static const uint UI_LABEL_CONTROL_SELECT_UPPER = 3u;
static const uint UI_LABEL_CONTROL_SELECT_LOWER = 4u;
static const uint UI_LABEL_CONTROL_SELECT_LEFT = 5u;
static const uint UI_LABEL_CONTROL_SELECT_RIGHT = 6u;
static const uint UI_LABEL_CONTROL_SELECT_LED = 7u;
static const uint UI_LABEL_CONTROL_SELECT_NONE = 8u;
static const uint UI_LABEL_CONTROL_SELECT_BAY1 = 9u;
static const uint UI_LABEL_CONTROL_SELECT_BAY2 = 10u;
static const uint UI_LABEL_CONTROL_SELECT_BAY3 = 11u;
static const uint UI_LABEL_CONTROL_SELECT_CUSTOM1 = 12u;
static const uint UI_LABEL_CONTROL_SELECT_CUSTOM2 = 13u;
static const uint UI_LABEL_CONTROL_SELECT_CUSTOM3 = 14u;
static const uint UI_LABEL_CONTROL_SELECT_CUSTOM4 = 15u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 3;
    if (labelId == 1u) return 5;
    if (labelId == 2u) return 5;
    if (labelId == 3u) return 5;
    if (labelId == 4u) return 5;
    if (labelId == 5u) return 4;
    if (labelId == 6u) return 5;
    if (labelId == 7u) return 3;
    if (labelId == 8u) return 4;
    if (labelId == 9u) return 4;
    if (labelId == 10u) return 4;
    if (labelId == 11u) return 4;
    if (labelId == 12u) return 7;
    if (labelId == 13u) return 7;
    if (labelId == 14u) return 7;
    if (labelId == 15u) return 7;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[3] = { 65, 76, 76 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[5] = { 83, 80, 73, 78, 69 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[5] = { 87, 73, 78, 71, 83 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[5] = { 85, 80, 80, 69, 82 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[5] = { 76, 79, 87, 69, 82 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[4] = { 76, 69, 70, 84 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[5] = { 82, 73, 71, 72, 84 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[3] = { 76, 69, 68 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[4] = { 78, 79, 78, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[4] = { 66, 65, 89, 49 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[4] = { 66, 65, 89, 50 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[4] = { 66, 65, 89, 51 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 12u) {
        int codes[7] = { 71, 82, 79, 85, 80, 32, 49 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 13u) {
        int codes[7] = { 71, 82, 79, 85, 80, 32, 50 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 14u) {
        int codes[7] = { 71, 82, 79, 85, 80, 32, 51 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 15u) {
        int codes[7] = { 71, 82, 79, 85, 80, 32, 52 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
