#ifndef SHAPE_MAKER_UI_GENERATED_HLSLI
#define SHAPE_MAKER_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: a7de5c8ba4925efafb269044b49ae453048d0b398936277996cd91af0828f22c
static const uint UI_CONTROL_COUNT = 14u;
static const uint UI_LABEL_COUNT = 26u;
static const uint4 UI_MANIFEST_HASH = uint4(0xa7de5c8bu, 0xa4925efau, 0xfb269044u, 0xb49ae453u);

static const uint UI_INDEX_SHAPE_MODE = 0u;
static const float4 UI_RECT_SHAPE_MODE = float4(0.04, 0.05, 0.27, 0.095);
static const uint UI_INDEX_ASPECT = 1u;
static const float4 UI_RECT_ASPECT = float4(0.04, 0.115, 0.27, 0.16);
static const uint UI_INDEX_ROTATION = 2u;
static const float4 UI_RECT_ROTATION = float4(0.04, 0.18, 0.27, 0.225);
static const uint UI_INDEX_CHARACTER_A = 3u;
static const float4 UI_RECT_CHARACTER_A = float4(0.04, 0.245, 0.27, 0.29);
static const uint UI_INDEX_CHARACTER_B = 4u;
static const float4 UI_RECT_CHARACTER_B = float4(0.04, 0.31, 0.27, 0.355);
static const uint UI_INDEX_DISPLACEMENT_MODE = 5u;
static const float4 UI_RECT_DISPLACEMENT_MODE = float4(0.04, 0.375, 0.27, 0.42);
static const uint UI_INDEX_DISPLACEMENT_AMOUNT = 6u;
static const float4 UI_RECT_DISPLACEMENT_AMOUNT = float4(0.04, 0.44, 0.27, 0.485);
static const uint UI_INDEX_DISPLACEMENT_SCALE = 7u;
static const float4 UI_RECT_DISPLACEMENT_SCALE = float4(0.04, 0.505, 0.27, 0.55);
static const uint UI_INDEX_PATTERN_ANGLE = 8u;
static const float4 UI_RECT_PATTERN_ANGLE = float4(0.04, 0.57, 0.27, 0.615);
static const uint UI_INDEX_MOTION_SPEED = 9u;
static const float4 UI_RECT_MOTION_SPEED = float4(0.04, 0.635, 0.27, 0.68);
static const uint UI_INDEX_EDGE_SOFTNESS = 10u;
static const float4 UI_RECT_EDGE_SOFTNESS = float4(0.04, 0.7, 0.27, 0.745);
static const uint UI_INDEX_DEPTH_PROFILE = 11u;
static const float4 UI_RECT_DEPTH_PROFILE = float4(0.04, 0.765, 0.27, 0.81);
static const uint UI_INDEX_DEPTH_STRENGTH = 12u;
static const float4 UI_RECT_DEPTH_STRENGTH = float4(0.04, 0.83, 0.27, 0.875);
static const uint UI_INDEX_SHOW_DEPTH = 13u;
static const float4 UI_RECT_SHOW_DEPTH = float4(0.875, 0.025, 0.97, 0.085);

static const uint UI_LABEL_NAV = 0u;
static const uint UI_LABEL_DEPTH = 1u;
static const uint UI_LABEL_SHAPE_ROUND = 2u;
static const uint UI_LABEL_SHAPE_BOX = 3u;
static const uint UI_LABEL_SHAPE_CAPSULE = 4u;
static const uint UI_LABEL_SHAPE_TRIANGLE = 5u;
static const uint UI_LABEL_SHAPE_STAR = 6u;
static const uint UI_LABEL_SHAPE_BLOB = 7u;
static const uint UI_LABEL_DISPLACE_WAVES = 8u;
static const uint UI_LABEL_DISPLACE_ORBIT = 9u;
static const uint UI_LABEL_DISPLACE_RADIAL = 10u;
static const uint UI_LABEL_DISPLACE_ORGANIC = 11u;
static const uint UI_LABEL_CONTROL_SHAPE_MODE = 12u;
static const uint UI_LABEL_CONTROL_ASPECT = 13u;
static const uint UI_LABEL_CONTROL_ROTATION = 14u;
static const uint UI_LABEL_CONTROL_CHARACTER_A = 15u;
static const uint UI_LABEL_CONTROL_CHARACTER_B = 16u;
static const uint UI_LABEL_CONTROL_DISPLACEMENT_MODE = 17u;
static const uint UI_LABEL_CONTROL_DISPLACEMENT_AMOUNT = 18u;
static const uint UI_LABEL_CONTROL_DISPLACEMENT_SCALE = 19u;
static const uint UI_LABEL_CONTROL_PATTERN_ANGLE = 20u;
static const uint UI_LABEL_CONTROL_MOTION_SPEED = 21u;
static const uint UI_LABEL_CONTROL_EDGE_SOFTNESS = 22u;
static const uint UI_LABEL_CONTROL_DEPTH_PROFILE = 23u;
static const uint UI_LABEL_CONTROL_DEPTH_STRENGTH = 24u;
static const uint UI_LABEL_CONTROL_SHOW_DEPTH = 25u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 24;
    if (labelId == 1u) return 5;
    if (labelId == 2u) return 5;
    if (labelId == 3u) return 11;
    if (labelId == 4u) return 7;
    if (labelId == 5u) return 8;
    if (labelId == 6u) return 4;
    if (labelId == 7u) return 4;
    if (labelId == 8u) return 15;
    if (labelId == 9u) return 13;
    if (labelId == 10u) return 12;
    if (labelId == 11u) return 13;
    if (labelId == 12u) return 10;
    if (labelId == 13u) return 6;
    if (labelId == 14u) return 8;
    if (labelId == 15u) return 11;
    if (labelId == 16u) return 11;
    if (labelId == 17u) return 17;
    if (labelId == 18u) return 15;
    if (labelId == 19u) return 14;
    if (labelId == 20u) return 14;
    if (labelId == 21u) return 12;
    if (labelId == 22u) return 13;
    if (labelId == 23u) return 16;
    if (labelId == 24u) return 14;
    if (labelId == 25u) return 5;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[24] = { 68, 82, 65, 71, 32, 77, 79, 86, 69, 32, 32, 47, 32, 32, 87, 72, 69, 69, 76, 32, 83, 73, 90, 69 };
        return characterIndex >= 0 && characterIndex < 24 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[5] = { 68, 69, 80, 84, 72 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[5] = { 82, 79, 85, 78, 68 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[11] = { 82, 79, 85, 78, 68, 69, 68, 32, 66, 79, 88 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[7] = { 67, 65, 80, 83, 85, 76, 69 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[8] = { 84, 82, 73, 65, 78, 71, 76, 69 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[4] = { 83, 84, 65, 82 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[4] = { 66, 76, 79, 66 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[15] = { 84, 82, 65, 86, 69, 76, 73, 78, 71, 32, 87, 65, 86, 69, 83 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[13] = { 79, 82, 66, 73, 84, 73, 78, 71, 32, 69, 68, 71, 69 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[12] = { 82, 65, 68, 73, 65, 76, 32, 80, 85, 76, 83, 69 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[13] = { 79, 82, 71, 65, 78, 73, 67, 32, 68, 82, 73, 70, 84 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 12u) {
        int codes[10] = { 83, 104, 97, 112, 101, 32, 32, 48, 45, 53 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 13u) {
        int codes[6] = { 65, 115, 112, 101, 99, 116 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 14u) {
        int codes[8] = { 82, 111, 116, 97, 116, 105, 111, 110 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 15u) {
        int codes[11] = { 67, 104, 97, 114, 97, 99, 116, 101, 114, 32, 65 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 16u) {
        int codes[11] = { 67, 104, 97, 114, 97, 99, 116, 101, 114, 32, 66 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 17u) {
        int codes[17] = { 68, 105, 115, 112, 108, 97, 99, 101, 109, 101, 110, 116, 32, 32, 48, 45, 51 };
        return characterIndex >= 0 && characterIndex < 17 ? codes[characterIndex] : 32;
    }
    if (labelId == 18u) {
        int codes[15] = { 68, 105, 115, 112, 108, 97, 99, 101, 32, 65, 109, 111, 117, 110, 116 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 19u) {
        int codes[14] = { 68, 105, 115, 112, 108, 97, 99, 101, 32, 83, 99, 97, 108, 101 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    if (labelId == 20u) {
        int codes[14] = { 68, 105, 115, 112, 108, 97, 99, 101, 32, 65, 110, 103, 108, 101 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    if (labelId == 21u) {
        int codes[12] = { 83, 112, 101, 101, 100, 32, 32, 45, 50, 46, 46, 50 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 22u) {
        int codes[13] = { 69, 100, 103, 101, 32, 83, 111, 102, 116, 110, 101, 115, 115 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 23u) {
        int codes[16] = { 68, 101, 112, 116, 104, 32, 83, 104, 97, 112, 101, 32, 32, 48, 45, 50 };
        return characterIndex >= 0 && characterIndex < 16 ? codes[characterIndex] : 32;
    }
    if (labelId == 24u) {
        int codes[14] = { 68, 101, 112, 116, 104, 32, 83, 116, 114, 101, 110, 103, 116, 104 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    if (labelId == 25u) {
        int codes[5] = { 68, 101, 112, 116, 104 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
