#ifndef MOTION_CONSOLE_UI_GENERATED_HLSLI
#define MOTION_CONSOLE_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 8a7e3c0badde3d0179c5d9d67af4d177af915eddb566ff24bc7b9b265b3345ff
static const uint UI_CONTROL_COUNT = 15u;
static const uint UI_LABEL_COUNT = 15u;
static const uint4 UI_MANIFEST_HASH = uint4(0x8a7e3c0bu, 0xadde3d01u, 0x79c5d9d6u, 0x7af4d177u);

static const uint UI_INDEX_MASTER_RATE = 0u;
static const float4 UI_RECT_MASTER_RATE = float4(0.36, 0.03, 0.58, 0.075);
static const uint UI_INDEX_MUTE = 1u;
static const float4 UI_RECT_MUTE = float4(0.6, 0.03, 0.68, 0.075);
static const uint UI_INDEX_BIAS = 2u;
static const float4 UI_RECT_BIAS = float4(0.82, 0.02, 0.97, 0.13);
static const uint UI_INDEX_L1_SPEED = 3u;
static const float4 UI_RECT_L1_SPEED = float4(0.62, 0.155, 0.78, 0.2);
static const uint UI_INDEX_L1_AMP = 4u;
static const float4 UI_RECT_L1_AMP = float4(0.8, 0.155, 0.96, 0.2);
static const uint UI_INDEX_L1_SHAPE = 5u;
static const float4 UI_RECT_L1_SHAPE = float4(0.62, 0.215, 0.96, 0.26);
static const uint UI_INDEX_L2_SPEED = 6u;
static const float4 UI_RECT_L2_SPEED = float4(0.62, 0.335, 0.78, 0.38);
static const uint UI_INDEX_L2_AMP = 7u;
static const float4 UI_RECT_L2_AMP = float4(0.8, 0.335, 0.96, 0.38);
static const uint UI_INDEX_L2_SHAPE = 8u;
static const float4 UI_RECT_L2_SHAPE = float4(0.62, 0.395, 0.96, 0.44);
static const uint UI_INDEX_L3_SPEED = 9u;
static const float4 UI_RECT_L3_SPEED = float4(0.62, 0.515, 0.78, 0.56);
static const uint UI_INDEX_L3_AMP = 10u;
static const float4 UI_RECT_L3_AMP = float4(0.8, 0.515, 0.96, 0.56);
static const uint UI_INDEX_L3_SHAPE = 11u;
static const float4 UI_RECT_L3_SHAPE = float4(0.62, 0.575, 0.96, 0.62);
static const uint UI_INDEX_L4_SPEED = 12u;
static const float4 UI_RECT_L4_SPEED = float4(0.62, 0.695, 0.78, 0.74);
static const uint UI_INDEX_L4_AMP = 13u;
static const float4 UI_RECT_L4_AMP = float4(0.8, 0.695, 0.96, 0.74);
static const uint UI_INDEX_L4_SHAPE = 14u;
static const float4 UI_RECT_L4_SHAPE = float4(0.62, 0.755, 0.96, 0.8);

static const uint UI_LABEL_CONTROL_MASTER_RATE = 0u;
static const uint UI_LABEL_CONTROL_MUTE = 1u;
static const uint UI_LABEL_CONTROL_BIAS = 2u;
static const uint UI_LABEL_CONTROL_L1_SPEED = 3u;
static const uint UI_LABEL_CONTROL_L1_AMP = 4u;
static const uint UI_LABEL_CONTROL_L1_SHAPE = 5u;
static const uint UI_LABEL_CONTROL_L2_SPEED = 6u;
static const uint UI_LABEL_CONTROL_L2_AMP = 7u;
static const uint UI_LABEL_CONTROL_L2_SHAPE = 8u;
static const uint UI_LABEL_CONTROL_L3_SPEED = 9u;
static const uint UI_LABEL_CONTROL_L3_AMP = 10u;
static const uint UI_LABEL_CONTROL_L3_SHAPE = 11u;
static const uint UI_LABEL_CONTROL_L4_SPEED = 12u;
static const uint UI_LABEL_CONTROL_L4_AMP = 13u;
static const uint UI_LABEL_CONTROL_L4_SHAPE = 14u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 11;
    if (labelId == 1u) return 4;
    if (labelId == 2u) return 11;
    if (labelId == 3u) return 11;
    if (labelId == 4u) return 10;
    if (labelId == 5u) return 12;
    if (labelId == 6u) return 11;
    if (labelId == 7u) return 10;
    if (labelId == 8u) return 12;
    if (labelId == 9u) return 11;
    if (labelId == 10u) return 10;
    if (labelId == 11u) return 12;
    if (labelId == 12u) return 10;
    if (labelId == 13u) return 9;
    if (labelId == 14u) return 11;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[11] = { 77, 97, 115, 116, 101, 114, 32, 82, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[4] = { 77, 117, 116, 101 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[11] = { 77, 111, 116, 105, 111, 110, 32, 66, 105, 97, 115 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[11] = { 80, 114, 111, 109, 112, 116, 32, 82, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[10] = { 80, 114, 111, 109, 112, 116, 32, 65, 109, 112 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[12] = { 80, 114, 111, 109, 112, 116, 32, 83, 104, 97, 112, 101 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[11] = { 69, 110, 101, 114, 103, 121, 32, 82, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[10] = { 69, 110, 101, 114, 103, 121, 32, 65, 109, 112 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[12] = { 69, 110, 101, 114, 103, 121, 32, 83, 104, 97, 112, 101 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[11] = { 67, 97, 109, 101, 114, 97, 32, 82, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[10] = { 67, 97, 109, 101, 114, 97, 32, 65, 109, 112 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[12] = { 67, 97, 109, 101, 114, 97, 32, 83, 104, 97, 112, 101 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 12u) {
        int codes[10] = { 80, 117, 108, 115, 101, 32, 82, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 13u) {
        int codes[9] = { 80, 117, 108, 115, 101, 32, 65, 109, 112 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 14u) {
        int codes[11] = { 80, 117, 108, 115, 101, 32, 83, 104, 97, 112, 101 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
