"""Generate the PHAGE desk: a Push-free performance panel for the Surface.

One layout table drives three files so the Module, its shader and the Surface can never disagree:
    modules/Phage_Desk/manifest.yaml       viewport panel controls (pads / readouts), normalized rects
    modules/Phage_Desk/desk_layout.hlsli   the same rects, kinds and roles for render.hlsl
    scripts/show/desk_layout.luau          control index -> id, label and rig_commands action
then refreshes modules/Phage_Desk/_ui.generated.hlsli with the workspace's tools/module-ui.ps1, the
manifest-hash contract the example validator checks.

Pad titles come from tools/phage_looks.py, so renaming a look renames its pad.

    python tools/phage_desk.py
"""
from __future__ import annotations

import subprocess
from pathlib import Path

import phage_looks

ROOT = Path(__file__).resolve().parents[1]
W, H = 1600, 720
# Roles (render.hlsl deskRole): 0 neutral, 1 accent, 2 go, 3 kill, 4 warn, 5 freeze, 6 link.
TIER_ROLE = [5, 2, 4, 3]                     # CALM blue, GROOVE green, BUILD amber, CRAZY red
KIND = {"pad": 0, "readout": 1, "header": 2, "status": 3, "tier": 4}

controls: list[dict] = []


def add(cid, kind, rect, label, action=None, role=0):
    x0, y0, x1, y1 = rect
    controls.append({"id": cid, "kind": kind, "rect": (x0 / W, y0 / H, x1 / W, y1 / H), "label": label,
                     "action": action, "role": role})


def titles(kind):
    return [name for name, _ in phage_looks.build()[kind]]


BUILT = {k: titles(k) for k in ("static", "effects", "color", "complete")}

# Transport and holds.
x = 20
for cid, label in (("tap", "TAP"), ("play", "PLAY"), ("stop", "STOP"), ("sync", "SYNC")):
    add(cid, "pad", (x, 20, x + 130, 90), label, ("tempo", cid), role=0)
    x += 136
add("bpm", "readout", (x + 20, 20, x + 300, 90), "---.- BPM")
add("beat", "readout", (x + 300, 20, 1220, 90), "BAR - BEAT -")
add("blackout", "pad", (1234, 20, 1404, 90), "BLACKOUT", ("hold", "blackout"), role=3)
add("strobe", "pad", (1410, 20, 1580, 90), "STROBE", ("hold", "strobe"), role=4)

# Four banks of 16: FULL LOOKS / STATIC on top, EFFECTS / COLOR below.
COLS = {"left": 20, "right": 815}
COLW, GAP, PADH = 765, 6, 56
PADW = (COLW - 7 * GAP) / 8


def bank(kind, header, col, top, role_of=lambda slot: 0, head_w=COLW):
    x0 = COLS[col]
    add(f"head_{kind}", "header", (x0, top, x0 + head_w, top + 26), header)
    for slot in range(1, 17):
        r, c = divmod(slot - 1, 8)
        px, py = x0 + c * (PADW + GAP), top + 32 + r * (PADH + GAP)
        add(f"{kind}_{slot}", "pad", (px, py, px + PADW, py + PADH), BUILT[kind][slot - 1],
            ("preset", "recall", kind, str(slot)), role=role_of(slot))


bank("complete", "FULL LOOKS", "left", 112, lambda s: TIER_ROLE[(s - 1) // 4])
# Tier labels share their bank's header row, so those headers stop short of them (no overlapping controls).
bank("static", "STATIC", "right", 112, lambda s: 6 if s > 12 else 0, head_w=COLW - 256)
add("tier_static", "tier", (COLS["right"] + COLW - 250, 112, COLS["right"] + COLW, 136), "13-16 TRUSS POSES", role=6)
tx = COLS["left"] + COLW - 4 * 110
bank("effects", "EFFECTS", "left", 290, lambda s: TIER_ROLE[(s - 1) // 4], head_w=tx - 6 - COLS["left"])
for i, name in enumerate(("CALM", "GROOVE", "BUILD", "CRAZY")):
    add(f"tier_{name.lower()}", "tier", (tx + i * 110, 290, tx + i * 110 + 104, 314), name, role=TIER_ROLE[i])
bank("color", "COLOR", "right", 290)

# Camera orbit (same moves as the Push arrows) and the status line.
add("head_camera", "header", (20, 480, 600, 506), "CAMERA")
cam = [("cam_up", "UP", 1, 0), ("cam_left", "<", 0, 1), ("cam_down", "DOWN", 1, 1), ("cam_right", ">", 2, 1),
       ("cam_in", "IN", 4, 0), ("cam_out", "OUT", 4, 1), ("cam_home", "HOME", 5, 0)]
for cid, label, c, r in cam:
    px, py = 20 + c * 102, 514 + r * 64
    add(cid, "pad", (px, py, px + 96, py + 58), label, ("camera", cid[4:]))
add("head_status", "header", (640, 480, 1580, 506), "PROGRAMMER")
add("status", "status", (640, 514, 1580, 636), "DESK READY")
add("legend_full", "status", (20, 660, 785, 700), "FULL LOOK = STATIC + TRUSS POSE + EFFECTS + COLOR")
add("legend_fx", "status", (815, 660, 1580, 700), "EFFECTS: CALM / GROOVE / BUILD (16 BEATS) / CRAZY")


for c in controls:
    assert len(c["label"].encode()) <= 63, f"{c['id']} label over 63 bytes"


def manifest() -> str:
    lines = ["# Generated by tools/phage_desk.py; edit the generator, not this file.",
             "name: PHAGE / Desk", "version: '1.0'", "mode: generator", f"resolution: [{W}, {H}]",
             "panel:", "  mode: canvas", "  output: Desk", "viewport:", "  panel: true", "  controls:"]
    for c in controls:
        r = ", ".join(f"{v:.5f}" for v in c["rect"])
        if c["kind"] == "pad":
            lines.append(f'    - {{id: {c["id"]}, kind: pad, mode: momentary, rect: [{r}], label: "{c["label"]}"}}')
        else:
            lines.append(f'    - {{id: {c["id"]}, kind: readout, rect: [{r}], label: "{c["label"]}"}}')
    lines += ["passes:", "  - name: render", "    shader: render.hlsl", "outputs:", "  - name: Desk", "    pass: render", ""]
    return "\n".join(lines)


def hlsl() -> str:
    n = len(controls)
    rects = ",\n".join("    float4(" + ", ".join(f"{v:.5f}" for v in c["rect"]) + ")" for c in controls)
    kinds = ", ".join(str(KIND[c["kind"]]) for c in controls)
    roles = ", ".join(str(c["role"]) for c in controls)
    return "\n".join(["// Generated by tools/phage_desk.py; edit the generator, not this file.",
                      f"static const uint DESK_COUNT = {n};", f"static const float2 DESK_SIZE = float2({W}, {H});",
                      f"static const float4 DESK_RECT[DESK_COUNT] = {{\n{rects}\n}};",
                      f"static const uint DESK_KIND[DESK_COUNT] = {{{kinds}}};",
                      f"static const uint DESK_ROLE[DESK_COUNT] = {{{roles}}};", ""])


def luau() -> str:
    out = ["--!strict", "-- Generated by tools/phage_desk.py; edit the generator, not this file.",
           "-- Phage_Desk control index (0-based, manifest order) -> id and rig_command action.", "return {"]
    for i, c in enumerate(controls):
        kind = {"tier": "readout", "status": "status"}.get(c["kind"], c["kind"])
        action = "{" + ",".join(f'"{a}"' for a in c["action"]) + "}" if c["action"] else "nil"
        out.append(f'    [{i}]={{id="{c["id"]}",kind="{kind}",label="{c["label"]}",action={action}}},')
    out += ["}", ""]
    return "\n".join(out)


RENDER = """// Phage_Desk: a Push-free desk drawn from the host's per-control state.
// Clicks leave on the `panel` Event output; the Surface Script answers with lit/state feedback,
// which arrives here through _ViewportControlState. Effects and full looks carry their energy tier
// as an identity hue (CALM, GROOVE, BUILD, CRAZY); truss poses carry their own.
#include "../_shared/ui/show_controls.hlsli"
#include "desk_layout.hlsli"

float3 deskRole(uint role) {
    switch (role) {
        case 1: return SC_ACCENT;
        case 2: return SC_ROLE_GO;
        case 3: return SC_ROLE_KILL;
        case 4: return SC_ROLE_WARN;
        case 5: return SC_ROLE_FREEZE;
        case 6: return SC_ROLE_LINK;
        default: return SC_ROLE_NEUTRAL;
    }
}

float4 main(VS_OUTPUT In) : SV_TARGET0 {
    float2 p = In.Uv * _Resolution;
    float2 k = _Resolution / DESK_SIZE;       // layout pixels -> output pixels
    float s = min(k.x, k.y);
    float3 color = SC_SURFACE_BASE;
    [loop] for (uint i = 0; i < DESK_COUNT; i++) {
        float4 r = DESK_RECT[i] * float4(_Resolution, _Resolution);
        if (p.x < r.x - 4.0 || p.x > r.z + 4.0 || p.y < r.y - 4.0 || p.y > r.w + 4.0) continue;
        uint kind = DESK_KIND[i];
        float3 role = deskRole(DESK_ROLE[i]);
        if (kind == 0) {
            scPad(color, p, r.xy, r.zw, i, role, 14.0 * s, DESK_ROLE[i] >= 2);
        } else if (kind == 1) {
            scReadout(color, p, r.xy, r.zw, i, SC_TEXT_PRIMARY, 30.0 * s, 1);
        } else if (kind == 3) {
            scReadout(color, p, r.xy, r.zw, i, SC_TEXT_MUTED, 18.0 * s, 1);
        } else if (kind == 4) {
            scReadout(color, p, r.xy, r.zw, i, role, 14.0 * s, 2);
        } else {
            scHeader(color, p, r.xy, r.zw, i, 16.0 * s);
        }
    }
    return float4(color, 1.0);
}
"""


def main():
    mod = ROOT / "modules" / "Phage_Desk"
    mod.mkdir(parents=True, exist_ok=True)
    (mod / "manifest.yaml").write_text(manifest(), newline="\n")
    (mod / "desk_layout.hlsli").write_text(hlsl(), newline="\n")
    (mod / "render.hlsl").write_text(RENDER, newline="\n")
    (ROOT / "scripts" / "show" / "desk_layout.luau").write_text(luau(), newline="\n")
    print(f"Phage_Desk: {len(controls)} controls, {sum(c['kind'] == 'pad' for c in controls)} pads")
    workspace = ROOT.parents[1]
    module_ui = workspace / "tools" / "module-ui.ps1"
    if module_ui.exists():
        subprocess.run(["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", str(module_ui),
                        "-Action", "generate", "-ModulePath", str(mod), "-Root", str(workspace)], check=True)
    else:
        print("tools/module-ui.ps1 not found: regenerate modules/Phage_Desk/_ui.generated.hlsli before shipping")


if __name__ == "__main__":
    main()
