#ifndef INTERACTIVE_MATERIAL_LABORATORY_UI_GENERATED_HLSLI
#define INTERACTIVE_MATERIAL_LABORATORY_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: e4d8ea51a99d9c04de2d19f280bd4b7fcc18382ba3123bf0dac6f772b3187955
static const uint UI_CONTROL_COUNT = 0u;
static const uint UI_LABEL_COUNT = 3u;
static const uint4 UI_MANIFEST_HASH = uint4(0xe4d8ea51u, 0xa99d9c04u, 0xde2d19f2u, 0x80bd4b7fu);


static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_HINT = 1u;
static const uint UI_LABEL_BOARD = 2u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 19;
    if (labelId == 1u) return 36;
    if (labelId == 2u) return 28;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[19] = { 77, 65, 84, 69, 82, 73, 65, 76, 32, 76, 65, 66, 79, 82, 65, 84, 79, 82, 89 };
        return characterIndex >= 0 && characterIndex < 19 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[36] = { 77, 65, 84, 69, 82, 73, 65, 76, 32, 83, 87, 65, 84, 67, 72, 69, 83, 32, 47, 32, 76, 73, 86, 69, 32, 80, 66, 82, 32, 82, 69, 67, 79, 82, 68, 83 };
        return characterIndex >= 0 && characterIndex < 36 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[28] = { 84, 87, 69, 76, 86, 69, 32, 76, 73, 86, 69, 32, 77, 65, 84, 69, 82, 73, 65, 76, 32, 82, 69, 67, 79, 82, 68, 83 };
        return characterIndex >= 0 && characterIndex < 28 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
