#include "../_shared/ui/sui_theme.hlsli"
#include "../_shared/ui/sui_core.hlsli"
#include "../_shared/ui/sui_layout.hlsli"
#include "../_shared/ui/sui_typography.hlsli"
#include "_ui.generated.hlsli"
#include "../_shared/ui/sui_generated_text.hlsli"
struct MaterialRecord{float3 base_color;float roughness;float3 secondary_color;float metallic;float texture_scale;float texture_strength;float pattern_id;float emissive;float specular;float normal_strength;float seed;float reserved;};
StructuredBuffer<MaterialRecord> Materials:register(t0);RWTexture2D<float4> OutputUAV:register(u0);
SuiTheme materialTheme(){SuiTheme t=suiMonochromeTheme();t.background=float3(.006,.007,.009);t.panel=float3(.012,.013,.016);t.panelRaised=float3(.020,.021,.025);t.control=float3(.030,.032,.038);t.controlHover=float3(.050,.053,.060);t.controlDown=float3(.82,.60,.24);t.text=float3(.88,.90,.92);t.muted=float3(.42,.45,.49);t.border=float3(.12,.13,.15);t.accent=float3(.82,.60,.24);t.axisY=float3(.66,.68,.71);return t;}
void materialPanel(inout float3 color,SuiContext c,SuiTheme theme,float4 rect,bool raised){suiComposite(color,raised?theme.panelRaised:theme.panel,suiFillRect(c,rect));suiComposite(color,theme.border,suiStrokeRect(c,rect,1.0));}
float sdRoundBoxPx(float2 p,float2 b,float r){float2 q=abs(p)-b+r;return length(max(q,0))+min(max(q.x,q.y),0)-r;}
[numthreads(8,8,1)]void main(uint3 id:SV_DispatchThreadID){if(id.x>=(uint)_Resolution.x||id.y>=(uint)_Resolution.y)return;SuiContext c=suiContext(id.xy,_Resolution.xy);SuiTheme theme=materialTheme();float3 col=theme.background;suiComposite(col,float3(.018,.019,.022),suiGridPx(c,24,.42));materialPanel(col,c,theme,float4(.012,.018,.988,.982),false);suiComposite(col,theme.panelRaised,suiFillRect(c,float4(.012,.018,.988,.092)));suiComposite(col,theme.accent,suiFillRect(c,float4(.012,.018,.016,.092)));suiComposite(col,theme.text,suiLabelText(c,float2(.032,.041),suiTextStyle(1.30,.15),UI_LABEL_TITLE));suiComposite(col,theme.muted,suiLabelText(c,float2(.545,.047),suiTextStyle(.64,0),UI_LABEL_HINT));
 float4 board=float4(.025,.112,.975,.955);materialPanel(col,c,theme,board,true);float2 uv=(c.uv-board.xy)/max(board.zw-board.xy,.0001);if(all(uv>=0)&&all(uv<=1)){float2 grid=uv*float2(4,3);uint ix=min((uint)grid.x,3u),iy=min((uint)grid.y,2u),idx=iy*4u+ix;float2 cell=frac(grid);float2 q=(cell-.5)*float2(1,1.15);float sphere=saturate(1-length(q)*1.65);float rim=saturate(1-length(q)*1.42)-saturate(1-length(q)*1.65);MaterialRecord m=Materials[idx];float grain=.5+.5*sin((cell.x+cell.y*.37)*m.texture_scale*35+m.seed);float3 swatch=lerp(m.secondary_color,m.base_color,sphere);swatch=lerp(swatch,m.secondary_color,grain*m.texture_strength*.25);float highlight=pow(saturate(sphere),lerp(4,40,1-m.roughness))*m.specular;swatch+=highlight+rim*lerp(theme.axisY,theme.accent,m.metallic)+m.base_color*m.emissive*.10;float2 inset=abs(cell-.5)-float2(.43,.39);float card=length(max(inset,0))+min(max(inset.x,inset.y),0);col=lerp(col,swatch,smoothstep(.025,-.01,card));col+=(1-smoothstep(.006,.018,abs(card)))*lerp(theme.border,theme.accent,m.metallic);}
 suiComposite(col,theme.border,suiStrokeRect(c,board,1));suiComposite(col,theme.muted,suiLabelText(c,float2(board.x+.010,board.w-.020),suiTextStyle(.66,0),UI_LABEL_BOARD));OutputUAV[id.xy]=float4(saturate(col),1);}
