#ifndef LIVING_ROOM_ARCHITECTURE_CONTROLS_UI_GENERATED_HLSLI
#define LIVING_ROOM_ARCHITECTURE_CONTROLS_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 845641ba601b8e573d1dee5dd21fd1bd1922bab3758c823a41d41760805a5183
static const uint UI_CONTROL_COUNT = 0u;
static const uint UI_LABEL_COUNT = 7u;
static const uint4 UI_MANIFEST_HASH = uint4(0x845641bau, 0x601b8e57u, 0x3d1dee5du, 0xd21fd1bdu);


static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_SHELL = 1u;
static const uint UI_LABEL_ENTRY = 2u;
static const uint UI_LABEL_FLOOR = 3u;
static const uint UI_LABEL_ART = 4u;
static const uint UI_LABEL_LIGHTS = 5u;
static const uint UI_LABEL_NAV = 6u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 17;
    if (labelId == 1u) return 5;
    if (labelId == 2u) return 5;
    if (labelId == 3u) return 5;
    if (labelId == 4u) return 3;
    if (labelId == 5u) return 6;
    if (labelId == 6u) return 23;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[17] = { 65, 82, 67, 72, 73, 84, 69, 67, 84, 85, 82, 69, 32, 80, 76, 65, 78 };
        return characterIndex >= 0 && characterIndex < 17 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[5] = { 83, 72, 69, 76, 76 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[5] = { 69, 78, 84, 82, 89 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[5] = { 70, 76, 79, 79, 82 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[3] = { 65, 82, 84 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[6] = { 76, 73, 71, 72, 84, 83 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[23] = { 77, 73, 68, 68, 76, 69, 32, 80, 65, 78, 32, 47, 32, 87, 72, 69, 69, 76, 32, 90, 79, 79, 77 };
        return characterIndex >= 0 && characterIndex < 23 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
