// Generated by tools/phage_labels.py. Edit the generator, not this file.
#ifndef PH_LABELS_HLSLI
#define PH_LABELS_HLSLI
static const uint PH_LBL_CH[250]={80,72,65,71,69,32,47,32,70,73,88,84,85,82,69,83,65,76,76,78,79,78,69,77,79,86,69,82,83,83,84,82,79,66,69,83,66,65,82,83,65,88,69,83,76,69,70,84,82,73,71,72,84,80,76,65,84,69,67,65,80,83,73,68,67,79,76,76,65,82,75,78,69,69,83,70,69,69,84,66,79,79,84,72,76,69,71,83,79,68,68,70,82,79,78,84,32,69,76,69,86,65,84,73,79,78,80,76,65,78,32,40,65,85,68,73,69,78,67,69,32,66,69,76,79,87,41,83,69,76,69,67,84,69,68,67,76,73,67,75,32,47,32,68,82,65,71,32,83,69,76,69,67,84,32,32,32,83,72,73,70,84,32,65,68,68,32,32,32,67,84,82,76,32,84,79,71,71,76,69,32,32,32,65,32,65,76,76,32,32,32,69,83,67,32,67,76,69,65,82,80,82,79,71,82,65,77,77,69,82,82,69,70,69,82,69,78,67,69,72,73,71,72,76,73,71,72,84,83,79,76,79,87,65,73,84,73,78,71,32,70,79,82,32,77,79,85,78,84,83};
static const uint2 PH_LBL_RANGE[26]={uint2(0,16),uint2(16,3),uint2(19,4),uint2(23,6),uint2(29,7),uint2(36,4),uint2(40,4),uint2(44,4),uint2(48,5),uint2(53,5),uint2(58,6),uint2(64,6),uint2(70,5),uint2(75,4),uint2(79,5),uint2(84,4),uint2(88,3),uint2(91,15),uint2(106,21),uint2(127,8),uint2(135,65),uint2(200,10),uint2(210,9),uint2(219,9),uint2(228,4),uint2(232,18)};
float phLabelWidth(uint id,float s){return (float)PH_LBL_RANGE[id].y*SUI3_ADVANCE*s;}
float phLabel(float2 P,float2 anchor,float s,uint id){
 uint2 r=PH_LBL_RANGE[id];if(sui3RunMiss(P,anchor,s,(int)r.y))return 0;
 int k=(int)floor((P.x-anchor.x)/(SUI3_ADVANCE*s));if(k<0||k>=(int)r.y)return 0;
 float cov=sui3Glyph(P,anchor+float2((float)k*SUI3_ADVANCE*s,0),s,(int)PH_LBL_CH[r.x+(uint)k]);
 if(k>0)cov=max(cov,sui3Glyph(P,anchor+float2((float)(k-1)*SUI3_ADVANCE*s,0),s,(int)PH_LBL_CH[r.x+(uint)k-1]));
 return cov;}
#endif
