// Generated by tools/phage_labels.py. Edit the generator, not this file.
#ifndef PH_LABELS_HLSLI
#define PH_LABELS_HLSLI
static const uint PH_LBL_CH[170]={80,72,65,71,69,32,47,32,80,73,88,69,76,32,66,65,82,83,76,69,71,83,80,76,65,84,69,83,72,69,65,84,72,67,79,76,76,65,82,67,65,80,83,73,68,66,79,79,84,72,83,79,76,73,68,67,72,65,83,69,80,85,76,83,69,83,69,71,77,69,78,84,83,83,67,65,84,84,69,82,67,79,77,69,84,84,87,73,78,70,73,76,76,83,67,65,78,78,69,82,66,65,82,67,79,68,69,80,76,65,83,77,65,83,80,65,82,75,76,69,72,69,65,82,84,66,69,65,84,67,76,73,77,66,83,84,82,79,66,69,82,73,80,80,76,69,80,82,79,71,82,65,77,77,69,82,82,69,70,69,82,69,78,67,69,76,73,84,80,88};
static const uint2 PH_LBL_RANGE[27]={uint2(0,18),uint2(18,4),uint2(22,5),uint2(27,6),uint2(33,6),uint2(39,6),uint2(45,5),uint2(50,5),uint2(55,5),uint2(60,5),uint2(65,8),uint2(73,7),uint2(80,5),uint2(85,4),uint2(89,4),uint2(93,7),uint2(100,7),uint2(107,6),uint2(113,7),uint2(120,9),uint2(129,5),uint2(134,6),uint2(140,6),uint2(146,10),uint2(156,9),uint2(165,3),uint2(168,2)};
float phLabelWidth(uint id,float s){return (float)PH_LBL_RANGE[id].y*SUI3_ADVANCE*s;}
float phLabel(float2 P,float2 anchor,float s,uint id){
 uint2 r=PH_LBL_RANGE[id];if(sui3RunMiss(P,anchor,s,(int)r.y))return 0;
 int k=(int)floor((P.x-anchor.x)/(SUI3_ADVANCE*s));if(k<0||k>=(int)r.y)return 0;
 float cov=sui3Glyph(P,anchor+float2((float)k*SUI3_ADVANCE*s,0),s,(int)PH_LBL_CH[r.x+(uint)k]);
 if(k>0)cov=max(cov,sui3Glyph(P,anchor+float2((float)(k-1)*SUI3_ADVANCE*s,0),s,(int)PH_LBL_CH[r.x+(uint)k-1]));
 return cov;}
#endif
