// Generated by tools/phage_labels.py. Edit the generator, not this file.
#ifndef PH_LABELS_HLSLI
#define PH_LABELS_HLSLI
static const uint PH_LBL_CH[33]={80,72,65,71,69,32,47,32,84,82,85,83,83,32,65,83,83,69,77,66,76,89,84,85,66,69,83,83,79,76,73,68,83};
static const uint2 PH_LBL_RANGE[3]={uint2(0,22),uint2(22,5),uint2(27,6)};
float phLabelWidth(uint id,float s){return (float)PH_LBL_RANGE[id].y*SUI3_ADVANCE*s;}
float phLabel(float2 P,float2 anchor,float s,uint id){
 uint2 r=PH_LBL_RANGE[id];if(sui3RunMiss(P,anchor,s,(int)r.y))return 0;
 int k=(int)floor((P.x-anchor.x)/(SUI3_ADVANCE*s));if(k<0||k>=(int)r.y)return 0;
 float cov=sui3Glyph(P,anchor+float2((float)k*SUI3_ADVANCE*s,0),s,(int)PH_LBL_CH[r.x+(uint)k]);
 if(k>0)cov=max(cov,sui3Glyph(P,anchor+float2((float)(k-1)*SUI3_ADVANCE*s,0),s,(int)PH_LBL_CH[r.x+(uint)k-1]));
 return cov;}
#endif
