#ifndef MOTION_CONTROL_DESK_UI_GENERATED_HLSLI
#define MOTION_CONTROL_DESK_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 9536257e7f4ca106daf4e6c3d9c90e54adda6e3732a79f1817c8c55c34da2dde
static const uint UI_CONTROL_COUNT = 16u;
static const uint UI_LABEL_COUNT = 29u;
static const uint4 UI_MANIFEST_HASH = uint4(0x9536257eu, 0x7f4ca106u, 0xdaf4e6c3u, 0xd9c90e54u);

static const uint UI_INDEX_MASTER_RATE = 0u;
static const float4 UI_RECT_MASTER_RATE = float4(0.6, 0.08, 0.82, 0.145);
static const uint UI_INDEX_MUTE = 1u;
static const float4 UI_RECT_MUTE = float4(0.84, 0.08, 0.95, 0.145);
static const uint UI_INDEX_MOTION_BIAS = 2u;
static const float4 UI_RECT_MOTION_BIAS = float4(0.8, 0.28, 0.95, 0.485);
static const uint UI_INDEX_BURST = 3u;
static const float4 UI_RECT_BURST = float4(0.8, 0.535, 0.95, 0.6);
static const uint UI_INDEX_LFO1_SPEED = 4u;
static const float4 UI_RECT_LFO1_SPEED = float4(0.535, 0.235, 0.62, 0.33);
static const uint UI_INDEX_LFO1_AMP = 5u;
static const float4 UI_RECT_LFO1_AMP = float4(0.64, 0.235, 0.725, 0.33);
static const uint UI_INDEX_LFO1_SHAPE = 6u;
static const float4 UI_RECT_LFO1_SHAPE = float4(0.135, 0.305, 0.505, 0.365);
static const uint UI_INDEX_LFO2_SPEED = 7u;
static const float4 UI_RECT_LFO2_SPEED = float4(0.535, 0.425, 0.62, 0.52);
static const uint UI_INDEX_LFO2_AMP = 8u;
static const float4 UI_RECT_LFO2_AMP = float4(0.64, 0.425, 0.725, 0.52);
static const uint UI_INDEX_LFO2_SHAPE = 9u;
static const float4 UI_RECT_LFO2_SHAPE = float4(0.135, 0.495, 0.505, 0.555);
static const uint UI_INDEX_LFO3_SPEED = 10u;
static const float4 UI_RECT_LFO3_SPEED = float4(0.535, 0.615, 0.62, 0.71);
static const uint UI_INDEX_LFO3_AMP = 11u;
static const float4 UI_RECT_LFO3_AMP = float4(0.64, 0.615, 0.725, 0.71);
static const uint UI_INDEX_LFO3_SHAPE = 12u;
static const float4 UI_RECT_LFO3_SHAPE = float4(0.135, 0.685, 0.505, 0.745);
static const uint UI_INDEX_LFO4_SPEED = 13u;
static const float4 UI_RECT_LFO4_SPEED = float4(0.535, 0.805, 0.62, 0.9);
static const uint UI_INDEX_LFO4_AMP = 14u;
static const float4 UI_RECT_LFO4_AMP = float4(0.64, 0.805, 0.725, 0.9);
static const uint UI_INDEX_LFO4_SHAPE = 15u;
static const float4 UI_RECT_LFO4_SHAPE = float4(0.135, 0.875, 0.505, 0.935);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_SUBTITLE = 1u;
static const uint UI_LABEL_PROMPT = 2u;
static const uint UI_LABEL_ENERGY = 3u;
static const uint UI_LABEL_CAMERA = 4u;
static const uint UI_LABEL_PULSE = 5u;
static const uint UI_LABEL_RATE = 6u;
static const uint UI_LABEL_AMP = 7u;
static const uint UI_LABEL_SHAPE = 8u;
static const uint UI_LABEL_BIAS = 9u;
static const uint UI_LABEL_BURST = 10u;
static const uint UI_LABEL_MUTED = 11u;
static const uint UI_LABEL_LIVE = 12u;
static const uint UI_LABEL_CONTROL_MASTER_RATE = 13u;
static const uint UI_LABEL_CONTROL_MUTE = 14u;
static const uint UI_LABEL_CONTROL_MOTION_BIAS = 15u;
static const uint UI_LABEL_CONTROL_BURST = 16u;
static const uint UI_LABEL_CONTROL_LFO1_SPEED = 17u;
static const uint UI_LABEL_CONTROL_LFO1_AMP = 18u;
static const uint UI_LABEL_CONTROL_LFO1_SHAPE = 19u;
static const uint UI_LABEL_CONTROL_LFO2_SPEED = 20u;
static const uint UI_LABEL_CONTROL_LFO2_AMP = 21u;
static const uint UI_LABEL_CONTROL_LFO2_SHAPE = 22u;
static const uint UI_LABEL_CONTROL_LFO3_SPEED = 23u;
static const uint UI_LABEL_CONTROL_LFO3_AMP = 24u;
static const uint UI_LABEL_CONTROL_LFO3_SHAPE = 25u;
static const uint UI_LABEL_CONTROL_LFO4_SPEED = 26u;
static const uint UI_LABEL_CONTROL_LFO4_AMP = 27u;
static const uint UI_LABEL_CONTROL_LFO4_SHAPE = 28u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 19;
    if (labelId == 1u) return 26;
    if (labelId == 2u) return 6;
    if (labelId == 3u) return 6;
    if (labelId == 4u) return 6;
    if (labelId == 5u) return 5;
    if (labelId == 6u) return 4;
    if (labelId == 7u) return 3;
    if (labelId == 8u) return 5;
    if (labelId == 9u) return 11;
    if (labelId == 10u) return 5;
    if (labelId == 11u) return 5;
    if (labelId == 12u) return 4;
    if (labelId == 13u) return 11;
    if (labelId == 14u) return 4;
    if (labelId == 15u) return 11;
    if (labelId == 16u) return 5;
    if (labelId == 17u) return 11;
    if (labelId == 18u) return 16;
    if (labelId == 19u) return 12;
    if (labelId == 20u) return 11;
    if (labelId == 21u) return 16;
    if (labelId == 22u) return 12;
    if (labelId == 23u) return 11;
    if (labelId == 24u) return 16;
    if (labelId == 25u) return 12;
    if (labelId == 26u) return 10;
    if (labelId == 27u) return 15;
    if (labelId == 28u) return 11;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[19] = { 77, 79, 84, 73, 79, 78, 32, 67, 79, 78, 84, 82, 79, 76, 32, 68, 69, 83, 75 };
        return characterIndex >= 0 && characterIndex < 19 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[26] = { 70, 79, 85, 82, 45, 76, 65, 78, 69, 32, 77, 79, 68, 85, 76, 65, 84, 73, 79, 78, 32, 70, 73, 69, 76, 68 };
        return characterIndex >= 0 && characterIndex < 26 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[6] = { 80, 82, 79, 77, 80, 84 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[6] = { 69, 78, 69, 82, 71, 89 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[6] = { 67, 65, 77, 69, 82, 65 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[5] = { 80, 85, 76, 83, 69 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[4] = { 82, 65, 84, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[3] = { 65, 77, 80 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[5] = { 83, 72, 65, 80, 69 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[11] = { 77, 79, 84, 73, 79, 78, 32, 66, 73, 65, 83 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[5] = { 66, 85, 82, 83, 84 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[5] = { 77, 85, 84, 69, 68 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 12u) {
        int codes[4] = { 76, 73, 86, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 13u) {
        int codes[11] = { 77, 97, 115, 116, 101, 114, 32, 82, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 14u) {
        int codes[4] = { 77, 117, 116, 101 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 15u) {
        int codes[11] = { 77, 111, 116, 105, 111, 110, 32, 66, 105, 97, 115 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 16u) {
        int codes[5] = { 66, 117, 114, 115, 116 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 17u) {
        int codes[11] = { 80, 114, 111, 109, 112, 116, 32, 82, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 18u) {
        int codes[16] = { 80, 114, 111, 109, 112, 116, 32, 65, 109, 112, 108, 105, 116, 117, 100, 101 };
        return characterIndex >= 0 && characterIndex < 16 ? codes[characterIndex] : 32;
    }
    if (labelId == 19u) {
        int codes[12] = { 80, 114, 111, 109, 112, 116, 32, 83, 104, 97, 112, 101 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 20u) {
        int codes[11] = { 69, 110, 101, 114, 103, 121, 32, 82, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 21u) {
        int codes[16] = { 69, 110, 101, 114, 103, 121, 32, 65, 109, 112, 108, 105, 116, 117, 100, 101 };
        return characterIndex >= 0 && characterIndex < 16 ? codes[characterIndex] : 32;
    }
    if (labelId == 22u) {
        int codes[12] = { 69, 110, 101, 114, 103, 121, 32, 83, 104, 97, 112, 101 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 23u) {
        int codes[11] = { 67, 97, 109, 101, 114, 97, 32, 82, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 24u) {
        int codes[16] = { 67, 97, 109, 101, 114, 97, 32, 65, 109, 112, 108, 105, 116, 117, 100, 101 };
        return characterIndex >= 0 && characterIndex < 16 ? codes[characterIndex] : 32;
    }
    if (labelId == 25u) {
        int codes[12] = { 67, 97, 109, 101, 114, 97, 32, 83, 104, 97, 112, 101 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 26u) {
        int codes[10] = { 80, 117, 108, 115, 101, 32, 82, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 27u) {
        int codes[15] = { 80, 117, 108, 115, 101, 32, 65, 109, 112, 108, 105, 116, 117, 100, 101 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 28u) {
        int codes[11] = { 80, 117, 108, 115, 101, 32, 83, 104, 97, 112, 101 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
