#ifndef PHAGE___DESK_UI_GENERATED_HLSLI
#define PHAGE___DESK_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: cc8638069522862377a59c5655b4e80732dc2f0883637854b89e50d3a4693b97
static const uint UI_CONTROL_COUNT = 93u;
static const uint UI_LABEL_COUNT = 93u;
static const uint4 UI_MANIFEST_HASH = uint4(0xcc863806u, 0x95228623u, 0x77a59c56u, 0x55b4e807u);

static const uint UI_INDEX_TAP = 0u;
static const float4 UI_RECT_TAP = float4(0.0125, 0.02778, 0.09375, 0.125);
static const uint UI_INDEX_PLAY = 1u;
static const float4 UI_RECT_PLAY = float4(0.0975, 0.02778, 0.17875, 0.125);
static const uint UI_INDEX_STOP = 2u;
static const float4 UI_RECT_STOP = float4(0.1825, 0.02778, 0.26375, 0.125);
static const uint UI_INDEX_SYNC = 3u;
static const float4 UI_RECT_SYNC = float4(0.2675, 0.02778, 0.34875, 0.125);
static const uint UI_INDEX_BPM = 4u;
static const float4 UI_RECT_BPM = float4(0.365, 0.02778, 0.54, 0.125);
static const uint UI_INDEX_BEAT = 5u;
static const float4 UI_RECT_BEAT = float4(0.54, 0.02778, 0.7625, 0.125);
static const uint UI_INDEX_BLACKOUT = 6u;
static const float4 UI_RECT_BLACKOUT = float4(0.77125, 0.02778, 0.8775, 0.125);
static const uint UI_INDEX_STROBE = 7u;
static const float4 UI_RECT_STROBE = float4(0.88125, 0.02778, 0.9875, 0.125);
static const uint UI_INDEX_HEAD_COMPLETE = 8u;
static const float4 UI_RECT_HEAD_COMPLETE = float4(0.0125, 0.15556, 0.49062, 0.19167);
static const uint UI_INDEX_COMPLETE_1 = 9u;
static const float4 UI_RECT_COMPLETE_1 = float4(0.0125, 0.2, 0.06898, 0.27778);
static const uint UI_INDEX_COMPLETE_2 = 10u;
static const float4 UI_RECT_COMPLETE_2 = float4(0.07273, 0.2, 0.12922, 0.27778);
static const uint UI_INDEX_COMPLETE_3 = 11u;
static const float4 UI_RECT_COMPLETE_3 = float4(0.13297, 0.2, 0.18945, 0.27778);
static const uint UI_INDEX_COMPLETE_4 = 12u;
static const float4 UI_RECT_COMPLETE_4 = float4(0.1932, 0.2, 0.24969, 0.27778);
static const uint UI_INDEX_COMPLETE_5 = 13u;
static const float4 UI_RECT_COMPLETE_5 = float4(0.25344, 0.2, 0.30992, 0.27778);
static const uint UI_INDEX_COMPLETE_6 = 14u;
static const float4 UI_RECT_COMPLETE_6 = float4(0.31367, 0.2, 0.37016, 0.27778);
static const uint UI_INDEX_COMPLETE_7 = 15u;
static const float4 UI_RECT_COMPLETE_7 = float4(0.37391, 0.2, 0.43039, 0.27778);
static const uint UI_INDEX_COMPLETE_8 = 16u;
static const float4 UI_RECT_COMPLETE_8 = float4(0.43414, 0.2, 0.49062, 0.27778);
static const uint UI_INDEX_COMPLETE_9 = 17u;
static const float4 UI_RECT_COMPLETE_9 = float4(0.0125, 0.28611, 0.06898, 0.36389);
static const uint UI_INDEX_COMPLETE_10 = 18u;
static const float4 UI_RECT_COMPLETE_10 = float4(0.07273, 0.28611, 0.12922, 0.36389);
static const uint UI_INDEX_COMPLETE_11 = 19u;
static const float4 UI_RECT_COMPLETE_11 = float4(0.13297, 0.28611, 0.18945, 0.36389);
static const uint UI_INDEX_COMPLETE_12 = 20u;
static const float4 UI_RECT_COMPLETE_12 = float4(0.1932, 0.28611, 0.24969, 0.36389);
static const uint UI_INDEX_COMPLETE_13 = 21u;
static const float4 UI_RECT_COMPLETE_13 = float4(0.25344, 0.28611, 0.30992, 0.36389);
static const uint UI_INDEX_COMPLETE_14 = 22u;
static const float4 UI_RECT_COMPLETE_14 = float4(0.31367, 0.28611, 0.37016, 0.36389);
static const uint UI_INDEX_COMPLETE_15 = 23u;
static const float4 UI_RECT_COMPLETE_15 = float4(0.37391, 0.28611, 0.43039, 0.36389);
static const uint UI_INDEX_COMPLETE_16 = 24u;
static const float4 UI_RECT_COMPLETE_16 = float4(0.43414, 0.28611, 0.49062, 0.36389);
static const uint UI_INDEX_HEAD_STATIC = 25u;
static const float4 UI_RECT_HEAD_STATIC = float4(0.50938, 0.15556, 0.8275, 0.19167);
static const uint UI_INDEX_STATIC_1 = 26u;
static const float4 UI_RECT_STATIC_1 = float4(0.50938, 0.2, 0.56586, 0.27778);
static const uint UI_INDEX_STATIC_2 = 27u;
static const float4 UI_RECT_STATIC_2 = float4(0.56961, 0.2, 0.62609, 0.27778);
static const uint UI_INDEX_STATIC_3 = 28u;
static const float4 UI_RECT_STATIC_3 = float4(0.62984, 0.2, 0.68633, 0.27778);
static const uint UI_INDEX_STATIC_4 = 29u;
static const float4 UI_RECT_STATIC_4 = float4(0.69008, 0.2, 0.74656, 0.27778);
static const uint UI_INDEX_STATIC_5 = 30u;
static const float4 UI_RECT_STATIC_5 = float4(0.75031, 0.2, 0.8068, 0.27778);
static const uint UI_INDEX_STATIC_6 = 31u;
static const float4 UI_RECT_STATIC_6 = float4(0.81055, 0.2, 0.86703, 0.27778);
static const uint UI_INDEX_STATIC_7 = 32u;
static const float4 UI_RECT_STATIC_7 = float4(0.87078, 0.2, 0.92727, 0.27778);
static const uint UI_INDEX_STATIC_8 = 33u;
static const float4 UI_RECT_STATIC_8 = float4(0.93102, 0.2, 0.9875, 0.27778);
static const uint UI_INDEX_STATIC_9 = 34u;
static const float4 UI_RECT_STATIC_9 = float4(0.50938, 0.28611, 0.56586, 0.36389);
static const uint UI_INDEX_STATIC_10 = 35u;
static const float4 UI_RECT_STATIC_10 = float4(0.56961, 0.28611, 0.62609, 0.36389);
static const uint UI_INDEX_STATIC_11 = 36u;
static const float4 UI_RECT_STATIC_11 = float4(0.62984, 0.28611, 0.68633, 0.36389);
static const uint UI_INDEX_STATIC_12 = 37u;
static const float4 UI_RECT_STATIC_12 = float4(0.69008, 0.28611, 0.74656, 0.36389);
static const uint UI_INDEX_STATIC_13 = 38u;
static const float4 UI_RECT_STATIC_13 = float4(0.75031, 0.28611, 0.8068, 0.36389);
static const uint UI_INDEX_STATIC_14 = 39u;
static const float4 UI_RECT_STATIC_14 = float4(0.81055, 0.28611, 0.86703, 0.36389);
static const uint UI_INDEX_STATIC_15 = 40u;
static const float4 UI_RECT_STATIC_15 = float4(0.87078, 0.28611, 0.92727, 0.36389);
static const uint UI_INDEX_STATIC_16 = 41u;
static const float4 UI_RECT_STATIC_16 = float4(0.93102, 0.28611, 0.9875, 0.36389);
static const uint UI_INDEX_TIER_STATIC = 42u;
static const float4 UI_RECT_TIER_STATIC = float4(0.83125, 0.15556, 0.9875, 0.18889);
static const uint UI_INDEX_HEAD_EFFECTS = 43u;
static const float4 UI_RECT_HEAD_EFFECTS = float4(0.0125, 0.40278, 0.21188, 0.43889);
static const uint UI_INDEX_EFFECTS_1 = 44u;
static const float4 UI_RECT_EFFECTS_1 = float4(0.0125, 0.44722, 0.06898, 0.525);
static const uint UI_INDEX_EFFECTS_2 = 45u;
static const float4 UI_RECT_EFFECTS_2 = float4(0.07273, 0.44722, 0.12922, 0.525);
static const uint UI_INDEX_EFFECTS_3 = 46u;
static const float4 UI_RECT_EFFECTS_3 = float4(0.13297, 0.44722, 0.18945, 0.525);
static const uint UI_INDEX_EFFECTS_4 = 47u;
static const float4 UI_RECT_EFFECTS_4 = float4(0.1932, 0.44722, 0.24969, 0.525);
static const uint UI_INDEX_EFFECTS_5 = 48u;
static const float4 UI_RECT_EFFECTS_5 = float4(0.25344, 0.44722, 0.30992, 0.525);
static const uint UI_INDEX_EFFECTS_6 = 49u;
static const float4 UI_RECT_EFFECTS_6 = float4(0.31367, 0.44722, 0.37016, 0.525);
static const uint UI_INDEX_EFFECTS_7 = 50u;
static const float4 UI_RECT_EFFECTS_7 = float4(0.37391, 0.44722, 0.43039, 0.525);
static const uint UI_INDEX_EFFECTS_8 = 51u;
static const float4 UI_RECT_EFFECTS_8 = float4(0.43414, 0.44722, 0.49062, 0.525);
static const uint UI_INDEX_EFFECTS_9 = 52u;
static const float4 UI_RECT_EFFECTS_9 = float4(0.0125, 0.53333, 0.06898, 0.61111);
static const uint UI_INDEX_EFFECTS_10 = 53u;
static const float4 UI_RECT_EFFECTS_10 = float4(0.07273, 0.53333, 0.12922, 0.61111);
static const uint UI_INDEX_EFFECTS_11 = 54u;
static const float4 UI_RECT_EFFECTS_11 = float4(0.13297, 0.53333, 0.18945, 0.61111);
static const uint UI_INDEX_EFFECTS_12 = 55u;
static const float4 UI_RECT_EFFECTS_12 = float4(0.1932, 0.53333, 0.24969, 0.61111);
static const uint UI_INDEX_EFFECTS_13 = 56u;
static const float4 UI_RECT_EFFECTS_13 = float4(0.25344, 0.53333, 0.30992, 0.61111);
static const uint UI_INDEX_EFFECTS_14 = 57u;
static const float4 UI_RECT_EFFECTS_14 = float4(0.31367, 0.53333, 0.37016, 0.61111);
static const uint UI_INDEX_EFFECTS_15 = 58u;
static const float4 UI_RECT_EFFECTS_15 = float4(0.37391, 0.53333, 0.43039, 0.61111);
static const uint UI_INDEX_EFFECTS_16 = 59u;
static const float4 UI_RECT_EFFECTS_16 = float4(0.43414, 0.53333, 0.49062, 0.61111);
static const uint UI_INDEX_TIER_CALM = 60u;
static const float4 UI_RECT_TIER_CALM = float4(0.21563, 0.40278, 0.28063, 0.43611);
static const uint UI_INDEX_TIER_GROOVE = 61u;
static const float4 UI_RECT_TIER_GROOVE = float4(0.28437, 0.40278, 0.34937, 0.43611);
static const uint UI_INDEX_TIER_BUILD = 62u;
static const float4 UI_RECT_TIER_BUILD = float4(0.35313, 0.40278, 0.41813, 0.43611);
static const uint UI_INDEX_TIER_CRAZY = 63u;
static const float4 UI_RECT_TIER_CRAZY = float4(0.42188, 0.40278, 0.48688, 0.43611);
static const uint UI_INDEX_HEAD_COLOR = 64u;
static const float4 UI_RECT_HEAD_COLOR = float4(0.50938, 0.40278, 0.9875, 0.43889);
static const uint UI_INDEX_COLOR_1 = 65u;
static const float4 UI_RECT_COLOR_1 = float4(0.50938, 0.44722, 0.56586, 0.525);
static const uint UI_INDEX_COLOR_2 = 66u;
static const float4 UI_RECT_COLOR_2 = float4(0.56961, 0.44722, 0.62609, 0.525);
static const uint UI_INDEX_COLOR_3 = 67u;
static const float4 UI_RECT_COLOR_3 = float4(0.62984, 0.44722, 0.68633, 0.525);
static const uint UI_INDEX_COLOR_4 = 68u;
static const float4 UI_RECT_COLOR_4 = float4(0.69008, 0.44722, 0.74656, 0.525);
static const uint UI_INDEX_COLOR_5 = 69u;
static const float4 UI_RECT_COLOR_5 = float4(0.75031, 0.44722, 0.8068, 0.525);
static const uint UI_INDEX_COLOR_6 = 70u;
static const float4 UI_RECT_COLOR_6 = float4(0.81055, 0.44722, 0.86703, 0.525);
static const uint UI_INDEX_COLOR_7 = 71u;
static const float4 UI_RECT_COLOR_7 = float4(0.87078, 0.44722, 0.92727, 0.525);
static const uint UI_INDEX_COLOR_8 = 72u;
static const float4 UI_RECT_COLOR_8 = float4(0.93102, 0.44722, 0.9875, 0.525);
static const uint UI_INDEX_COLOR_9 = 73u;
static const float4 UI_RECT_COLOR_9 = float4(0.50938, 0.53333, 0.56586, 0.61111);
static const uint UI_INDEX_COLOR_10 = 74u;
static const float4 UI_RECT_COLOR_10 = float4(0.56961, 0.53333, 0.62609, 0.61111);
static const uint UI_INDEX_COLOR_11 = 75u;
static const float4 UI_RECT_COLOR_11 = float4(0.62984, 0.53333, 0.68633, 0.61111);
static const uint UI_INDEX_COLOR_12 = 76u;
static const float4 UI_RECT_COLOR_12 = float4(0.69008, 0.53333, 0.74656, 0.61111);
static const uint UI_INDEX_COLOR_13 = 77u;
static const float4 UI_RECT_COLOR_13 = float4(0.75031, 0.53333, 0.8068, 0.61111);
static const uint UI_INDEX_COLOR_14 = 78u;
static const float4 UI_RECT_COLOR_14 = float4(0.81055, 0.53333, 0.86703, 0.61111);
static const uint UI_INDEX_COLOR_15 = 79u;
static const float4 UI_RECT_COLOR_15 = float4(0.87078, 0.53333, 0.92727, 0.61111);
static const uint UI_INDEX_COLOR_16 = 80u;
static const float4 UI_RECT_COLOR_16 = float4(0.93102, 0.53333, 0.9875, 0.61111);
static const uint UI_INDEX_HEAD_CAMERA = 81u;
static const float4 UI_RECT_HEAD_CAMERA = float4(0.0125, 0.66667, 0.375, 0.70278);
static const uint UI_INDEX_CAM_UP = 82u;
static const float4 UI_RECT_CAM_UP = float4(0.07625, 0.71389, 0.13625, 0.79444);
static const uint UI_INDEX_CAM_LEFT = 83u;
static const float4 UI_RECT_CAM_LEFT = float4(0.0125, 0.80278, 0.0725, 0.88333);
static const uint UI_INDEX_CAM_DOWN = 84u;
static const float4 UI_RECT_CAM_DOWN = float4(0.07625, 0.80278, 0.13625, 0.88333);
static const uint UI_INDEX_CAM_RIGHT = 85u;
static const float4 UI_RECT_CAM_RIGHT = float4(0.14, 0.80278, 0.2, 0.88333);
static const uint UI_INDEX_CAM_IN = 86u;
static const float4 UI_RECT_CAM_IN = float4(0.2675, 0.71389, 0.3275, 0.79444);
static const uint UI_INDEX_CAM_OUT = 87u;
static const float4 UI_RECT_CAM_OUT = float4(0.2675, 0.80278, 0.3275, 0.88333);
static const uint UI_INDEX_CAM_HOME = 88u;
static const float4 UI_RECT_CAM_HOME = float4(0.33125, 0.71389, 0.39125, 0.79444);
static const uint UI_INDEX_HEAD_STATUS = 89u;
static const float4 UI_RECT_HEAD_STATUS = float4(0.4, 0.66667, 0.9875, 0.70278);
static const uint UI_INDEX_STATUS = 90u;
static const float4 UI_RECT_STATUS = float4(0.4, 0.71389, 0.9875, 0.88333);
static const uint UI_INDEX_LEGEND_FULL = 91u;
static const float4 UI_RECT_LEGEND_FULL = float4(0.0125, 0.91667, 0.49062, 0.97222);
static const uint UI_INDEX_LEGEND_FX = 92u;
static const float4 UI_RECT_LEGEND_FX = float4(0.50938, 0.91667, 0.9875, 0.97222);

static const uint UI_LABEL_CONTROL_TAP = 0u;
static const uint UI_LABEL_CONTROL_PLAY = 1u;
static const uint UI_LABEL_CONTROL_STOP = 2u;
static const uint UI_LABEL_CONTROL_SYNC = 3u;
static const uint UI_LABEL_CONTROL_BPM = 4u;
static const uint UI_LABEL_CONTROL_BEAT = 5u;
static const uint UI_LABEL_CONTROL_BLACKOUT = 6u;
static const uint UI_LABEL_CONTROL_STROBE = 7u;
static const uint UI_LABEL_CONTROL_HEAD_COMPLETE = 8u;
static const uint UI_LABEL_CONTROL_COMPLETE_1 = 9u;
static const uint UI_LABEL_CONTROL_COMPLETE_2 = 10u;
static const uint UI_LABEL_CONTROL_COMPLETE_3 = 11u;
static const uint UI_LABEL_CONTROL_COMPLETE_4 = 12u;
static const uint UI_LABEL_CONTROL_COMPLETE_5 = 13u;
static const uint UI_LABEL_CONTROL_COMPLETE_6 = 14u;
static const uint UI_LABEL_CONTROL_COMPLETE_7 = 15u;
static const uint UI_LABEL_CONTROL_COMPLETE_8 = 16u;
static const uint UI_LABEL_CONTROL_COMPLETE_9 = 17u;
static const uint UI_LABEL_CONTROL_COMPLETE_10 = 18u;
static const uint UI_LABEL_CONTROL_COMPLETE_11 = 19u;
static const uint UI_LABEL_CONTROL_COMPLETE_12 = 20u;
static const uint UI_LABEL_CONTROL_COMPLETE_13 = 21u;
static const uint UI_LABEL_CONTROL_COMPLETE_14 = 22u;
static const uint UI_LABEL_CONTROL_COMPLETE_15 = 23u;
static const uint UI_LABEL_CONTROL_COMPLETE_16 = 24u;
static const uint UI_LABEL_CONTROL_HEAD_STATIC = 25u;
static const uint UI_LABEL_CONTROL_STATIC_1 = 26u;
static const uint UI_LABEL_CONTROL_STATIC_2 = 27u;
static const uint UI_LABEL_CONTROL_STATIC_3 = 28u;
static const uint UI_LABEL_CONTROL_STATIC_4 = 29u;
static const uint UI_LABEL_CONTROL_STATIC_5 = 30u;
static const uint UI_LABEL_CONTROL_STATIC_6 = 31u;
static const uint UI_LABEL_CONTROL_STATIC_7 = 32u;
static const uint UI_LABEL_CONTROL_STATIC_8 = 33u;
static const uint UI_LABEL_CONTROL_STATIC_9 = 34u;
static const uint UI_LABEL_CONTROL_STATIC_10 = 35u;
static const uint UI_LABEL_CONTROL_STATIC_11 = 36u;
static const uint UI_LABEL_CONTROL_STATIC_12 = 37u;
static const uint UI_LABEL_CONTROL_STATIC_13 = 38u;
static const uint UI_LABEL_CONTROL_STATIC_14 = 39u;
static const uint UI_LABEL_CONTROL_STATIC_15 = 40u;
static const uint UI_LABEL_CONTROL_STATIC_16 = 41u;
static const uint UI_LABEL_CONTROL_TIER_STATIC = 42u;
static const uint UI_LABEL_CONTROL_HEAD_EFFECTS = 43u;
static const uint UI_LABEL_CONTROL_EFFECTS_1 = 44u;
static const uint UI_LABEL_CONTROL_EFFECTS_2 = 45u;
static const uint UI_LABEL_CONTROL_EFFECTS_3 = 46u;
static const uint UI_LABEL_CONTROL_EFFECTS_4 = 47u;
static const uint UI_LABEL_CONTROL_EFFECTS_5 = 48u;
static const uint UI_LABEL_CONTROL_EFFECTS_6 = 49u;
static const uint UI_LABEL_CONTROL_EFFECTS_7 = 50u;
static const uint UI_LABEL_CONTROL_EFFECTS_8 = 51u;
static const uint UI_LABEL_CONTROL_EFFECTS_9 = 52u;
static const uint UI_LABEL_CONTROL_EFFECTS_10 = 53u;
static const uint UI_LABEL_CONTROL_EFFECTS_11 = 54u;
static const uint UI_LABEL_CONTROL_EFFECTS_12 = 55u;
static const uint UI_LABEL_CONTROL_EFFECTS_13 = 56u;
static const uint UI_LABEL_CONTROL_EFFECTS_14 = 57u;
static const uint UI_LABEL_CONTROL_EFFECTS_15 = 58u;
static const uint UI_LABEL_CONTROL_EFFECTS_16 = 59u;
static const uint UI_LABEL_CONTROL_TIER_CALM = 60u;
static const uint UI_LABEL_CONTROL_TIER_GROOVE = 61u;
static const uint UI_LABEL_CONTROL_TIER_BUILD = 62u;
static const uint UI_LABEL_CONTROL_TIER_CRAZY = 63u;
static const uint UI_LABEL_CONTROL_HEAD_COLOR = 64u;
static const uint UI_LABEL_CONTROL_COLOR_1 = 65u;
static const uint UI_LABEL_CONTROL_COLOR_2 = 66u;
static const uint UI_LABEL_CONTROL_COLOR_3 = 67u;
static const uint UI_LABEL_CONTROL_COLOR_4 = 68u;
static const uint UI_LABEL_CONTROL_COLOR_5 = 69u;
static const uint UI_LABEL_CONTROL_COLOR_6 = 70u;
static const uint UI_LABEL_CONTROL_COLOR_7 = 71u;
static const uint UI_LABEL_CONTROL_COLOR_8 = 72u;
static const uint UI_LABEL_CONTROL_COLOR_9 = 73u;
static const uint UI_LABEL_CONTROL_COLOR_10 = 74u;
static const uint UI_LABEL_CONTROL_COLOR_11 = 75u;
static const uint UI_LABEL_CONTROL_COLOR_12 = 76u;
static const uint UI_LABEL_CONTROL_COLOR_13 = 77u;
static const uint UI_LABEL_CONTROL_COLOR_14 = 78u;
static const uint UI_LABEL_CONTROL_COLOR_15 = 79u;
static const uint UI_LABEL_CONTROL_COLOR_16 = 80u;
static const uint UI_LABEL_CONTROL_HEAD_CAMERA = 81u;
static const uint UI_LABEL_CONTROL_CAM_UP = 82u;
static const uint UI_LABEL_CONTROL_CAM_LEFT = 83u;
static const uint UI_LABEL_CONTROL_CAM_DOWN = 84u;
static const uint UI_LABEL_CONTROL_CAM_RIGHT = 85u;
static const uint UI_LABEL_CONTROL_CAM_IN = 86u;
static const uint UI_LABEL_CONTROL_CAM_OUT = 87u;
static const uint UI_LABEL_CONTROL_CAM_HOME = 88u;
static const uint UI_LABEL_CONTROL_HEAD_STATUS = 89u;
static const uint UI_LABEL_CONTROL_STATUS = 90u;
static const uint UI_LABEL_CONTROL_LEGEND_FULL = 91u;
static const uint UI_LABEL_CONTROL_LEGEND_FX = 92u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 3;
    if (labelId == 1u) return 4;
    if (labelId == 2u) return 4;
    if (labelId == 3u) return 4;
    if (labelId == 4u) return 9;
    if (labelId == 5u) return 12;
    if (labelId == 6u) return 8;
    if (labelId == 7u) return 6;
    if (labelId == 8u) return 10;
    if (labelId == 9u) return 7;
    if (labelId == 10u) return 4;
    if (labelId == 11u) return 4;
    if (labelId == 12u) return 6;
    if (labelId == 13u) return 9;
    if (labelId == 14u) return 10;
    if (labelId == 15u) return 5;
    if (labelId == 16u) return 8;
    if (labelId == 17u) return 6;
    if (labelId == 18u) return 8;
    if (labelId == 19u) return 8;
    if (labelId == 20u) return 4;
    if (labelId == 21u) return 4;
    if (labelId == 22u) return 5;
    if (labelId == 23u) return 7;
    if (labelId == 24u) return 9;
    if (labelId == 25u) return 6;
    if (labelId == 26u) return 6;
    if (labelId == 27u) return 9;
    if (labelId == 28u) return 8;
    if (labelId == 29u) return 5;
    if (labelId == 30u) return 6;
    if (labelId == 31u) return 5;
    if (labelId == 32u) return 4;
    if (labelId == 33u) return 5;
    if (labelId == 34u) return 7;
    if (labelId == 35u) return 6;
    if (labelId == 36u) return 4;
    if (labelId == 37u) return 8;
    if (labelId == 38u) return 4;
    if (labelId == 39u) return 4;
    if (labelId == 40u) return 6;
    if (labelId == 41u) return 5;
    if (labelId == 42u) return 17;
    if (labelId == 43u) return 7;
    if (labelId == 44u) return 5;
    if (labelId == 45u) return 4;
    if (labelId == 46u) return 7;
    if (labelId == 47u) return 5;
    if (labelId == 48u) return 5;
    if (labelId == 49u) return 4;
    if (labelId == 50u) return 4;
    if (labelId == 51u) return 5;
    if (labelId == 52u) return 6;
    if (labelId == 53u) return 7;
    if (labelId == 54u) return 6;
    if (labelId == 55u) return 9;
    if (labelId == 56u) return 4;
    if (labelId == 57u) return 5;
    if (labelId == 58u) return 7;
    if (labelId == 59u) return 9;
    if (labelId == 60u) return 4;
    if (labelId == 61u) return 6;
    if (labelId == 62u) return 5;
    if (labelId == 63u) return 5;
    if (labelId == 64u) return 5;
    if (labelId == 65u) return 5;
    if (labelId == 66u) return 3;
    if (labelId == 67u) return 5;
    if (labelId == 68u) return 8;
    if (labelId == 69u) return 6;
    if (labelId == 70u) return 5;
    if (labelId == 71u) return 2;
    if (labelId == 72u) return 4;
    if (labelId == 73u) return 7;
    if (labelId == 74u) return 7;
    if (labelId == 75u) return 5;
    if (labelId == 76u) return 4;
    if (labelId == 77u) return 5;
    if (labelId == 78u) return 8;
    if (labelId == 79u) return 5;
    if (labelId == 80u) return 5;
    if (labelId == 81u) return 6;
    if (labelId == 82u) return 2;
    if (labelId == 83u) return 1;
    if (labelId == 84u) return 4;
    if (labelId == 85u) return 1;
    if (labelId == 86u) return 2;
    if (labelId == 87u) return 3;
    if (labelId == 88u) return 4;
    if (labelId == 89u) return 10;
    if (labelId == 90u) return 10;
    if (labelId == 91u) return 49;
    if (labelId == 92u) return 49;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[3] = { 84, 65, 80 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[4] = { 80, 76, 65, 89 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[4] = { 83, 84, 79, 80 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[4] = { 83, 89, 78, 67 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[9] = { 45, 45, 45, 46, 45, 32, 66, 80, 77 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[12] = { 66, 65, 82, 32, 45, 32, 66, 69, 65, 84, 32, 45 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[8] = { 66, 76, 65, 67, 75, 79, 85, 84 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[6] = { 83, 84, 82, 79, 66, 69 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[10] = { 70, 85, 76, 76, 32, 76, 79, 79, 75, 83 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[7] = { 71, 69, 78, 69, 83, 73, 83 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[4] = { 76, 85, 76, 76 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[4] = { 68, 69, 69, 80 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 12u) {
        int codes[6] = { 69, 77, 66, 69, 82, 83 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 13u) {
        int codes[9] = { 72, 69, 65, 82, 84, 66, 69, 65, 84 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 14u) {
        int codes[10] = { 80, 82, 79, 67, 69, 83, 83, 73, 79, 78 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 15u) {
        int codes[5] = { 83, 87, 69, 76, 76 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 16u) {
        int codes[8] = { 67, 65, 82, 79, 85, 83, 69, 76 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 17u) {
        int codes[6] = { 65, 83, 67, 69, 78, 84 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 18u) {
        int codes[8] = { 80, 82, 69, 83, 83, 85, 82, 69 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 19u) {
        int codes[8] = { 73, 71, 78, 73, 84, 73, 79, 78 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 20u) {
        int codes[4] = { 90, 69, 82, 79 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 21u) {
        int codes[4] = { 82, 73, 79, 84 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 22u) {
        int codes[5] = { 83, 84, 79, 82, 77 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 23u) {
        int codes[7] = { 83, 72, 65, 84, 84, 69, 82 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 24u) {
        int codes[9] = { 83, 85, 80, 69, 82, 78, 79, 86, 65 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 25u) {
        int codes[6] = { 83, 84, 65, 84, 73, 67 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 26u) {
        int codes[6] = { 79, 82, 73, 71, 73, 78 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 27u) {
        int codes[9] = { 67, 65, 84, 72, 69, 68, 82, 65, 76 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 28u) {
        int codes[8] = { 83, 85, 78, 66, 85, 82, 83, 84 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 29u) {
        int codes[5] = { 67, 82, 79, 87, 78 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 30u) {
        int codes[6] = { 70, 73, 66, 69, 82, 83 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 31u) {
        int codes[5] = { 72, 69, 76, 73, 88 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 32u) {
        int codes[4] = { 67, 65, 71, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 33u) {
        int codes[5] = { 70, 82, 79, 78, 84 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 34u) {
        int codes[7] = { 78, 69, 69, 68, 76, 69, 83 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 35u) {
        int codes[6] = { 88, 45, 70, 73, 82, 69 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 36u) {
        int codes[4] = { 72, 65, 76, 79 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 37u) {
        int codes[8] = { 80, 73, 78, 80, 79, 73, 78, 84 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 38u) {
        int codes[4] = { 82, 69, 83, 84 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 39u) {
        int codes[4] = { 82, 73, 83, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 40u) {
        int codes[6] = { 73, 78, 74, 69, 67, 84 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 41u) {
        int codes[5] = { 66, 76, 79, 79, 77 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 42u) {
        int codes[17] = { 49, 51, 45, 49, 54, 32, 84, 82, 85, 83, 83, 32, 80, 79, 83, 69, 83 };
        return characterIndex >= 0 && characterIndex < 17 ? codes[characterIndex] : 32;
    }
    if (labelId == 43u) {
        int codes[7] = { 69, 70, 70, 69, 67, 84, 83 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 44u) {
        int codes[5] = { 68, 82, 73, 70, 84 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 45u) {
        int codes[4] = { 84, 73, 68, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 46u) {
        int codes[7] = { 66, 82, 69, 65, 84, 72, 69 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 47u) {
        int codes[5] = { 69, 77, 66, 69, 82 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 48u) {
        int codes[5] = { 80, 85, 76, 83, 69 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 49u) {
        int codes[4] = { 87, 65, 76, 75 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 50u) {
        int codes[4] = { 83, 87, 65, 89 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 51u) {
        int codes[5] = { 79, 82, 66, 73, 84 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 52u) {
        int codes[6] = { 65, 83, 67, 69, 78, 68 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 53u) {
        int codes[7] = { 84, 69, 78, 83, 73, 79, 78 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 54u) {
        int codes[6] = { 76, 65, 85, 78, 67, 72 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 55u) {
        int codes[9] = { 67, 79, 85, 78, 84, 68, 79, 87, 78 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 56u) {
        int codes[4] = { 82, 73, 79, 84 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 57u) {
        int codes[5] = { 83, 84, 79, 82, 77 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 58u) {
        int codes[7] = { 83, 72, 65, 84, 84, 69, 82 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 59u) {
        int codes[9] = { 83, 85, 80, 69, 82, 78, 79, 86, 65 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 60u) {
        int codes[4] = { 67, 65, 76, 77 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 61u) {
        int codes[6] = { 71, 82, 79, 79, 86, 69 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 62u) {
        int codes[5] = { 66, 85, 73, 76, 68 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 63u) {
        int codes[5] = { 67, 82, 65, 90, 89 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 64u) {
        int codes[5] = { 67, 79, 76, 79, 82 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 65u) {
        int codes[5] = { 87, 72, 73, 84, 69 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 66u) {
        int codes[3] = { 73, 67, 69 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 67u) {
        int codes[5] = { 80, 72, 65, 71, 69 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 68u) {
        int codes[8] = { 73, 78, 70, 82, 65, 82, 69, 68 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 69u) {
        int codes[6] = { 83, 79, 68, 73, 85, 77 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 70u) {
        int codes[5] = { 86, 73, 82, 65, 76 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 71u) {
        int codes[2] = { 85, 86 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 72u) {
        int codes[4] = { 82, 79, 83, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 73u) {
        int codes[7] = { 71, 76, 65, 67, 73, 69, 82 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 74u) {
        int codes[7] = { 66, 73, 79, 76, 85, 77, 69 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 75u) {
        int codes[5] = { 77, 65, 71, 77, 65 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 76u) {
        int codes[4] = { 68, 85, 83, 75 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 77u) {
        int codes[5] = { 84, 79, 88, 73, 67 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 78u) {
        int codes[8] = { 85, 86, 32, 83, 80, 76, 73, 84 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 79u) {
        int codes[5] = { 67, 79, 82, 65, 76 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 80u) {
        int codes[5] = { 83, 80, 76, 73, 84 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 81u) {
        int codes[6] = { 67, 65, 77, 69, 82, 65 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 82u) {
        int codes[2] = { 85, 80 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 83u) {
        int codes[1] = { 60 };
        return characterIndex >= 0 && characterIndex < 1 ? codes[characterIndex] : 32;
    }
    if (labelId == 84u) {
        int codes[4] = { 68, 79, 87, 78 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 85u) {
        int codes[1] = { 62 };
        return characterIndex >= 0 && characterIndex < 1 ? codes[characterIndex] : 32;
    }
    if (labelId == 86u) {
        int codes[2] = { 73, 78 };
        return characterIndex >= 0 && characterIndex < 2 ? codes[characterIndex] : 32;
    }
    if (labelId == 87u) {
        int codes[3] = { 79, 85, 84 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 88u) {
        int codes[4] = { 72, 79, 77, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 89u) {
        int codes[10] = { 80, 82, 79, 71, 82, 65, 77, 77, 69, 82 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 90u) {
        int codes[10] = { 68, 69, 83, 75, 32, 82, 69, 65, 68, 89 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 91u) {
        int codes[49] = { 70, 85, 76, 76, 32, 76, 79, 79, 75, 32, 61, 32, 83, 84, 65, 84, 73, 67, 32, 43, 32, 84, 82, 85, 83, 83, 32, 80, 79, 83, 69, 32, 43, 32, 69, 70, 70, 69, 67, 84, 83, 32, 43, 32, 67, 79, 76, 79, 82 };
        return characterIndex >= 0 && characterIndex < 49 ? codes[characterIndex] : 32;
    }
    if (labelId == 92u) {
        int codes[49] = { 69, 70, 70, 69, 67, 84, 83, 58, 32, 67, 65, 76, 77, 32, 47, 32, 71, 82, 79, 79, 86, 69, 32, 47, 32, 66, 85, 73, 76, 68, 32, 40, 49, 54, 32, 66, 69, 65, 84, 83, 41, 32, 47, 32, 67, 82, 65, 90, 89 };
        return characterIndex >= 0 && characterIndex < 49 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
