#ifndef _07___SIGNAL_CUT_FEATURE_CONSOLE_UI_GENERATED_HLSLI
#define _07___SIGNAL_CUT_FEATURE_CONSOLE_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: d759e91d5239c7d18f8977331aca7787b1fb3f809dd4bc7485ec5af2a8bea64b
static const uint UI_CONTROL_COUNT = 3u;
static const uint UI_LABEL_COUNT = 12u;
static const uint4 UI_MANIFEST_HASH = uint4(0xd759e91du, 0x5239c7d1u, 0x8f897733u, 0x1aca7787u);

static const uint UI_INDEX_TENSION = 0u;
static const float4 UI_RECT_TENSION = float4(0.653, 0.29, 0.928, 0.36);
static const uint UI_INDEX_DENSITY = 1u;
static const float4 UI_RECT_DENSITY = float4(0.653, 0.462, 0.928, 0.532);
static const uint UI_INDEX_MODE = 2u;
static const float4 UI_RECT_MODE = float4(0.653, 0.634, 0.928, 0.704);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_ANALYSIS = 1u;
static const uint UI_LABEL_TENSION = 2u;
static const uint UI_LABEL_DENSITY = 3u;
static const uint UI_LABEL_MODE = 4u;
static const uint UI_LABEL_ASCII_ON = 5u;
static const uint UI_LABEL_VECTOR = 6u;
static const uint UI_LABEL_AUTO = 7u;
static const uint UI_LABEL_DIRECT = 8u;
static const uint UI_LABEL_CONTROL_TENSION = 9u;
static const uint UI_LABEL_CONTROL_DENSITY = 10u;
static const uint UI_LABEL_CONTROL_MODE = 11u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 29;
    if (labelId == 1u) return 16;
    if (labelId == 2u) return 15;
    if (labelId == 3u) return 18;
    if (labelId == 4u) return 19;
    if (labelId == 5u) return 13;
    if (labelId == 6u) return 11;
    if (labelId == 7u) return 41;
    if (labelId == 8u) return 49;
    if (labelId == 9u) return 15;
    if (labelId == 10u) return 13;
    if (labelId == 11u) return 10;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[29] = { 83, 73, 71, 78, 65, 76, 32, 67, 85, 84, 32, 47, 32, 70, 69, 65, 84, 85, 82, 69, 32, 65, 78, 65, 76, 89, 83, 73, 83 };
        return characterIndex >= 0 && characterIndex < 29 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[16] = { 70, 69, 65, 84, 85, 82, 69, 32, 65, 78, 65, 76, 89, 83, 73, 83 };
        return characterIndex >= 0 && characterIndex < 16 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[15] = { 78, 69, 84, 87, 79, 82, 75, 32, 84, 69, 78, 83, 73, 79, 78 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[18] = { 65, 83, 67, 73, 73, 32, 67, 69, 76, 76, 32, 68, 69, 78, 83, 73, 84, 89 };
        return characterIndex >= 0 && characterIndex < 18 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[19] = { 65, 83, 67, 73, 73, 32, 47, 32, 86, 69, 67, 84, 79, 82, 32, 77, 79, 68, 69 };
        return characterIndex >= 0 && characterIndex < 19 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[13] = { 65, 83, 67, 73, 73, 32, 76, 69, 78, 83, 32, 79, 78 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[11] = { 86, 69, 67, 84, 79, 82, 32, 79, 78, 76, 89 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[41] = { 83, 84, 82, 79, 78, 71, 69, 83, 84, 32, 82, 69, 83, 80, 79, 78, 83, 69, 32, 83, 69, 76, 69, 67, 84, 69, 68, 32, 65, 85, 84, 79, 77, 65, 84, 73, 67, 65, 76, 76, 89 };
        return characterIndex >= 0 && characterIndex < 41 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[49] = { 82, 32, 47, 32, 88, 32, 47, 32, 89, 32, 86, 65, 76, 85, 69, 83, 32, 67, 79, 77, 69, 32, 70, 82, 79, 77, 32, 84, 72, 69, 32, 76, 73, 86, 69, 32, 67, 79, 82, 78, 69, 82, 32, 66, 85, 70, 70, 69, 82 };
        return characterIndex >= 0 && characterIndex < 49 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[15] = { 78, 101, 116, 119, 111, 114, 107, 32, 84, 101, 110, 115, 105, 111, 110 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[13] = { 65, 83, 67, 73, 73, 32, 68, 101, 110, 115, 105, 116, 121 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[10] = { 65, 83, 67, 73, 73, 32, 77, 111, 100, 101 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
