#ifndef TOPOGRAPHIC_SIGNAL_BUS_UI_GENERATED_HLSLI
#define TOPOGRAPHIC_SIGNAL_BUS_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: d45e6b3bc53f40429cdf87a8dcd13d65e3d5e3406a002c684e61e5f1bb5d312f
static const uint UI_CONTROL_COUNT = 0u;
static const uint UI_LABEL_COUNT = 0u;
static const uint4 UI_MANIFEST_HASH = uint4(0xd45e6b3bu, 0xc53f4042u, 0x9cdf87a8u, 0xdcd13d65u);



int uiLabelLength(uint labelId) {
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    return 32;
}

#endif
