#ifndef TOPOGRAPHIC_OPERATIONS_CONSOLE_UI_GENERATED_HLSLI
#define TOPOGRAPHIC_OPERATIONS_CONSOLE_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 913097c66d5c3931b4305ac675397e56e7d92677a37e13da53263e6bc752a97e
static const uint UI_CONTROL_COUNT = 2u;
static const uint UI_LABEL_COUNT = 2u;
static const uint4 UI_MANIFEST_HASH = uint4(0x913097c6u, 0x6d5c3931u, 0xb4305ac6u, 0x75397e56u);

static const uint UI_INDEX_MANUAL_ENERGY = 0u;
static const float4 UI_RECT_MANUAL_ENERGY = float4(0.055, 0.815, 0.475, 0.905);
static const uint UI_INDEX_MANUAL_SWEEP = 1u;
static const float4 UI_RECT_MANUAL_SWEEP = float4(0.525, 0.815, 0.945, 0.905);

static const uint UI_LABEL_CONTROL_MANUAL_ENERGY = 0u;
static const uint UI_LABEL_CONTROL_MANUAL_SWEEP = 1u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 18;
    if (labelId == 1u) return 17;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[18] = { 80, 101, 114, 102, 111, 114, 109, 97, 110, 99, 101, 32, 69, 110, 101, 114, 103, 121 };
        return characterIndex >= 0 && characterIndex < 18 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[17] = { 80, 101, 114, 102, 111, 114, 109, 97, 110, 99, 101, 32, 83, 119, 101, 101, 112 };
        return characterIndex >= 0 && characterIndex < 17 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
