#ifndef DESERT_WARP_DECK_UI_GENERATED_HLSLI
#define DESERT_WARP_DECK_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 3809f71d0051f00e85c301e36192772c31e377a1d522d519a18bc4a08a0f2fac
static const uint UI_CONTROL_COUNT = 13u;
static const uint UI_LABEL_COUNT = 36u;
static const uint4 UI_MANIFEST_HASH = uint4(0x3809f71du, 0x0051f00eu, 0x85c301e3u, 0x6192772cu);

static const uint UI_INDEX_WARP_STYLE = 0u;
static const float4 UI_RECT_WARP_STYLE = float4(0.06, 0.245, 0.455, 0.305);
static const uint UI_INDEX_MELT_MACRO = 1u;
static const float4 UI_RECT_MELT_MACRO = float4(0.06, 0.45, 0.245, 0.51);
static const uint UI_INDEX_SAG_MACRO = 2u;
static const float4 UI_RECT_SAG_MACRO = float4(0.27, 0.45, 0.455, 0.51);
static const uint UI_INDEX_SPREAD_MACRO = 3u;
static const float4 UI_RECT_SPREAD_MACRO = float4(0.06, 0.59, 0.245, 0.65);
static const uint UI_INDEX_EXPLODE_MACRO = 4u;
static const float4 UI_RECT_EXPLODE_MACRO = float4(0.27, 0.59, 0.455, 0.65);
static const uint UI_INDEX_WARP_PRIMARY = 5u;
static const float4 UI_RECT_WARP_PRIMARY = float4(0.06, 0.77, 0.245, 0.83);
static const uint UI_INDEX_WARP_SECONDARY = 6u;
static const float4 UI_RECT_WARP_SECONDARY = float4(0.27, 0.77, 0.455, 0.83);
static const uint UI_INDEX_TWIST_MACRO = 7u;
static const float4 UI_RECT_TWIST_MACRO = float4(0.06, 0.86, 0.455, 0.925);
static const uint UI_INDEX_PAINTERLY_MACRO = 8u;
static const float4 UI_RECT_PAINTERLY_MACRO = float4(0.55, 0.285, 0.92, 0.345);
static const uint UI_INDEX_FACET_MACRO = 9u;
static const float4 UI_RECT_FACET_MACRO = float4(0.55, 0.435, 0.92, 0.495);
static const uint UI_INDEX_HUE_MACRO = 10u;
static const float4 UI_RECT_HUE_MACRO = float4(0.55, 0.585, 0.92, 0.645);
static const uint UI_INDEX_HEAT_MACRO = 11u;
static const float4 UI_RECT_HEAT_MACRO = float4(0.55, 0.735, 0.92, 0.795);
static const uint UI_INDEX_SCATTER_MACRO = 12u;
static const float4 UI_RECT_SCATTER_MACRO = float4(0.55, 0.86, 0.92, 0.925);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_SUBTITLE = 1u;
static const uint UI_LABEL_LANGUAGE = 2u;
static const uint UI_LABEL_MONUMENT = 3u;
static const uint UI_LABEL_DALI = 4u;
static const uint UI_LABEL_CUBIST = 5u;
static const uint UI_LABEL_PAINTERLY = 6u;
static const uint UI_LABEL_PERFORMANCE = 7u;
static const uint UI_LABEL_STRUCTURE = 8u;
static const uint UI_LABEL_MELT = 9u;
static const uint UI_LABEL_SAG = 10u;
static const uint UI_LABEL_SPREAD = 11u;
static const uint UI_LABEL_EXPLODE = 12u;
static const uint UI_LABEL_WARP = 13u;
static const uint UI_LABEL_PRIMARY = 14u;
static const uint UI_LABEL_SECONDARY = 15u;
static const uint UI_LABEL_TWIST = 16u;
static const uint UI_LABEL_SURFACE = 17u;
static const uint UI_LABEL_PAINT = 18u;
static const uint UI_LABEL_FACET = 19u;
static const uint UI_LABEL_HUE = 20u;
static const uint UI_LABEL_HEAT = 21u;
static const uint UI_LABEL_ACCENTS = 22u;
static const uint UI_LABEL_CONTROL_WARP_STYLE = 23u;
static const uint UI_LABEL_CONTROL_MELT_MACRO = 24u;
static const uint UI_LABEL_CONTROL_SAG_MACRO = 25u;
static const uint UI_LABEL_CONTROL_SPREAD_MACRO = 26u;
static const uint UI_LABEL_CONTROL_EXPLODE_MACRO = 27u;
static const uint UI_LABEL_CONTROL_WARP_PRIMARY = 28u;
static const uint UI_LABEL_CONTROL_WARP_SECONDARY = 29u;
static const uint UI_LABEL_CONTROL_TWIST_MACRO = 30u;
static const uint UI_LABEL_CONTROL_PAINTERLY_MACRO = 31u;
static const uint UI_LABEL_CONTROL_FACET_MACRO = 32u;
static const uint UI_LABEL_CONTROL_HUE_MACRO = 33u;
static const uint UI_LABEL_CONTROL_HEAT_MACRO = 34u;
static const uint UI_LABEL_CONTROL_SCATTER_MACRO = 35u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 16;
    if (labelId == 1u) return 39;
    if (labelId == 2u) return 13;
    if (labelId == 3u) return 3;
    if (labelId == 4u) return 4;
    if (labelId == 5u) return 3;
    if (labelId == 6u) return 5;
    if (labelId == 7u) return 4;
    if (labelId == 8u) return 9;
    if (labelId == 9u) return 4;
    if (labelId == 10u) return 3;
    if (labelId == 11u) return 6;
    if (labelId == 12u) return 7;
    if (labelId == 13u) return 10;
    if (labelId == 14u) return 7;
    if (labelId == 15u) return 9;
    if (labelId == 16u) return 5;
    if (labelId == 17u) return 15;
    if (labelId == 18u) return 9;
    if (labelId == 19u) return 5;
    if (labelId == 20u) return 9;
    if (labelId == 21u) return 9;
    if (labelId == 22u) return 12;
    if (labelId == 23u) return 13;
    if (labelId == 24u) return 4;
    if (labelId == 25u) return 3;
    if (labelId == 26u) return 6;
    if (labelId == 27u) return 7;
    if (labelId == 28u) return 12;
    if (labelId == 29u) return 14;
    if (labelId == 30u) return 5;
    if (labelId == 31u) return 9;
    if (labelId == 32u) return 5;
    if (labelId == 33u) return 9;
    if (labelId == 34u) return 9;
    if (labelId == 35u) return 12;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[16] = { 68, 69, 83, 69, 82, 84, 32, 87, 65, 82, 80, 32, 68, 69, 67, 75 };
        return characterIndex >= 0 && characterIndex < 16 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[39] = { 83, 65, 70, 69, 32, 68, 79, 77, 65, 73, 78, 32, 68, 73, 83, 84, 79, 82, 84, 73, 79, 78, 32, 47, 32, 65, 83, 83, 69, 77, 66, 76, 89, 32, 70, 73, 69, 76, 68 };
        return characterIndex >= 0 && characterIndex < 39 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[13] = { 87, 65, 82, 80, 32, 76, 65, 78, 71, 85, 65, 71, 69 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[3] = { 77, 79, 78 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[4] = { 68, 65, 76, 73 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[3] = { 67, 85, 66 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[5] = { 80, 65, 73, 78, 84 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[4] = { 80, 69, 82, 70 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[9] = { 83, 84, 82, 85, 67, 84, 85, 82, 69 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[4] = { 77, 69, 76, 84 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[3] = { 83, 65, 71 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[6] = { 83, 80, 82, 69, 65, 68 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 12u) {
        int codes[7] = { 69, 88, 80, 76, 79, 68, 69 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 13u) {
        int codes[10] = { 87, 65, 82, 80, 32, 70, 73, 69, 76, 68 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 14u) {
        int codes[7] = { 80, 82, 73, 77, 65, 82, 89 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 15u) {
        int codes[9] = { 83, 69, 67, 79, 78, 68, 65, 82, 89 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 16u) {
        int codes[5] = { 84, 87, 73, 83, 84 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 17u) {
        int codes[15] = { 83, 85, 82, 70, 65, 67, 69, 32, 47, 32, 70, 73, 69, 76, 68 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 18u) {
        int codes[9] = { 80, 65, 73, 78, 84, 69, 82, 76, 89 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 19u) {
        int codes[5] = { 70, 65, 67, 69, 84 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 20u) {
        int codes[9] = { 72, 85, 69, 32, 83, 72, 73, 70, 84 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 21u) {
        int codes[9] = { 72, 69, 65, 84, 32, 72, 65, 90, 69 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 22u) {
        int codes[12] = { 65, 67, 67, 69, 78, 84, 32, 70, 73, 69, 76, 68 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 23u) {
        int codes[13] = { 87, 97, 114, 112, 32, 76, 97, 110, 103, 117, 97, 103, 101 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 24u) {
        int codes[4] = { 77, 101, 108, 116 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 25u) {
        int codes[3] = { 83, 97, 103 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 26u) {
        int codes[6] = { 83, 112, 114, 101, 97, 100 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 27u) {
        int codes[7] = { 69, 120, 112, 108, 111, 100, 101 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 28u) {
        int codes[12] = { 80, 114, 105, 109, 97, 114, 121, 32, 87, 97, 114, 112 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 29u) {
        int codes[14] = { 83, 101, 99, 111, 110, 100, 97, 114, 121, 32, 87, 97, 114, 112 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    if (labelId == 30u) {
        int codes[5] = { 84, 119, 105, 115, 116 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 31u) {
        int codes[9] = { 80, 97, 105, 110, 116, 101, 114, 108, 121 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 32u) {
        int codes[5] = { 70, 97, 99, 101, 116 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 33u) {
        int codes[9] = { 72, 117, 101, 32, 83, 104, 105, 102, 116 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 34u) {
        int codes[9] = { 72, 101, 97, 116, 32, 72, 97, 122, 101 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 35u) {
        int codes[12] = { 65, 99, 99, 101, 110, 116, 32, 70, 105, 101, 108, 100 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
