#ifndef DISCOVERY_MASTER_CLOCK_UI_GENERATED_HLSLI
#define DISCOVERY_MASTER_CLOCK_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: f10381748d77debd620f6b456e50b6a7812a6287929929f92adcdcd7f0304b9b
static const uint UI_CONTROL_COUNT = 4u;
static const uint UI_LABEL_COUNT = 6u;
static const uint4 UI_MANIFEST_HASH = uint4(0xf1038174u, 0x8d77debdu, 0x620f6b45u, 0x6e50b6a7u);

static const uint UI_INDEX_PLAY = 0u;
static const float4 UI_RECT_PLAY = float4(0.055, 0.82, 0.205, 0.925);
static const uint UI_INDEX_RESET_TRANSPORT = 1u;
static const float4 UI_RECT_RESET_TRANSPORT = float4(0.225, 0.82, 0.375, 0.925);
static const uint UI_INDEX_SCRUB_MODE = 2u;
static const float4 UI_RECT_SCRUB_MODE = float4(0.395, 0.82, 0.585, 0.925);
static const uint UI_INDEX_SCRUB_POSITION = 3u;
static const float4 UI_RECT_SCRUB_POSITION = float4(0.605, 0.82, 0.945, 0.925);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_SUBTITLE = 1u;
static const uint UI_LABEL_CONTROL_PLAY = 2u;
static const uint UI_LABEL_CONTROL_RESET_TRANSPORT = 3u;
static const uint UI_LABEL_CONTROL_SCRUB_MODE = 4u;
static const uint UI_LABEL_CONTROL_SCRUB_POSITION = 5u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 22;
    if (labelId == 1u) return 37;
    if (labelId == 2u) return 4;
    if (labelId == 3u) return 5;
    if (labelId == 4u) return 5;
    if (labelId == 5u) return 8;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[22] = { 68, 73, 83, 67, 79, 86, 69, 82, 89, 32, 77, 65, 83, 84, 69, 82, 32, 67, 76, 79, 67, 75 };
        return characterIndex >= 0 && characterIndex < 22 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[37] = { 73, 78, 84, 69, 71, 82, 65, 84, 69, 68, 32, 80, 72, 65, 83, 69, 32, 47, 32, 69, 78, 86, 69, 76, 79, 80, 69, 32, 65, 85, 84, 72, 79, 82, 73, 84, 89 };
        return characterIndex >= 0 && characterIndex < 37 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[4] = { 80, 76, 65, 89 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[5] = { 82, 69, 83, 69, 84 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[5] = { 83, 67, 82, 85, 66 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[8] = { 80, 79, 83, 73, 84, 73, 79, 78 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
