#ifndef TOPOGRAPHIC_OPERATIONS_CONSOLE_UI_GENERATED_HLSLI
#define TOPOGRAPHIC_OPERATIONS_CONSOLE_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: dfe1544d99ac8235e9cd72945a3bd55155ec9a1208128016fe8657a5e7686953
static const uint UI_CONTROL_COUNT = 16u;
static const uint UI_LABEL_COUNT = 41u;
static const uint4 UI_MANIFEST_HASH = uint4(0xdfe1544du, 0x99ac8235u, 0xe9cd7294u, 0x5a3bd551u);

static const uint UI_INDEX_AUTHORITY = 0u;
static const float4 UI_RECT_AUTHORITY = float4(0.055, 0.225, 0.47, 0.285);
static const uint UI_INDEX_CUE_MODE = 1u;
static const float4 UI_RECT_CUE_MODE = float4(0.055, 0.365, 0.47, 0.425);
static const uint UI_INDEX_TERRAIN = 2u;
static const float4 UI_RECT_TERRAIN = float4(0.055, 0.55, 0.27, 0.61);
static const uint UI_INDEX_NODE_DENSITY = 3u;
static const float4 UI_RECT_NODE_DENSITY = float4(0.3, 0.55, 0.515, 0.61);
static const uint UI_INDEX_PALETTE = 4u;
static const float4 UI_RECT_PALETTE = float4(0.055, 0.705, 0.515, 0.765);
static const uint UI_INDEX_LAYER_BLUE = 5u;
static const float4 UI_RECT_LAYER_BLUE = float4(0.585, 0.235, 0.93, 0.295);
static const uint UI_INDEX_LAYER_ACCENT = 6u;
static const float4 UI_RECT_LAYER_ACCENT = float4(0.585, 0.335, 0.93, 0.395);
static const uint UI_INDEX_LAYER_NODES = 7u;
static const float4 UI_RECT_LAYER_NODES = float4(0.585, 0.435, 0.93, 0.495);
static const uint UI_INDEX_LAYER_LABELS = 8u;
static const float4 UI_RECT_LAYER_LABELS = float4(0.585, 0.535, 0.93, 0.595);
static const uint UI_INDEX_MASTER_MIX = 9u;
static const float4 UI_RECT_MASTER_MIX = float4(0.585, 0.655, 0.93, 0.715);
static const uint UI_INDEX_MANUAL_ENERGY = 10u;
static const float4 UI_RECT_MANUAL_ENERGY = float4(0.055, 0.85, 0.255, 0.915);
static const uint UI_INDEX_MANUAL_SWEEP = 11u;
static const float4 UI_RECT_MANUAL_SWEEP = float4(0.275, 0.85, 0.475, 0.915);
static const uint UI_INDEX_PULSE_RATE = 12u;
static const float4 UI_RECT_PULSE_RATE = float4(0.52, 0.85, 0.62, 0.915);
static const uint UI_INDEX_SWEEP_RATE = 13u;
static const float4 UI_RECT_SWEEP_RATE = float4(0.64, 0.85, 0.74, 0.915);
static const uint UI_INDEX_BEAT_RATE = 14u;
static const float4 UI_RECT_BEAT_RATE = float4(0.76, 0.85, 0.86, 0.915);
static const uint UI_INDEX_BEAT_SHARP = 15u;
static const float4 UI_RECT_BEAT_SHARP = float4(0.88, 0.85, 0.95, 0.915);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_SUBTITLE = 1u;
static const uint UI_LABEL_AUTHORITY = 2u;
static const uint UI_LABEL_CUE = 3u;
static const uint UI_LABEL_TERRAIN = 4u;
static const uint UI_LABEL_DENSITY = 5u;
static const uint UI_LABEL_PALETTE = 6u;
static const uint UI_LABEL_LAYERS = 7u;
static const uint UI_LABEL_BLUE = 8u;
static const uint UI_LABEL_ACCENT = 9u;
static const uint UI_LABEL_NODES = 10u;
static const uint UI_LABEL_LABELS = 11u;
static const uint UI_LABEL_MASTER = 12u;
static const uint UI_LABEL_SIGNAL = 13u;
static const uint UI_LABEL_PULSE = 14u;
static const uint UI_LABEL_SWEEP = 15u;
static const uint UI_LABEL_BEAT = 16u;
static const uint UI_LABEL_MANUAL = 17u;
static const uint UI_LABEL_AUTO = 18u;
static const uint UI_LABEL_CONDUCTOR = 19u;
static const uint UI_LABEL_SURVEY = 20u;
static const uint UI_LABEL_THREAT = 21u;
static const uint UI_LABEL_NIGHT = 22u;
static const uint UI_LABEL_MINIMAL = 23u;
static const uint UI_LABEL_PERFORMANCE = 24u;
static const uint UI_LABEL_CONTROL_AUTHORITY = 25u;
static const uint UI_LABEL_CONTROL_CUE_MODE = 26u;
static const uint UI_LABEL_CONTROL_TERRAIN = 27u;
static const uint UI_LABEL_CONTROL_NODE_DENSITY = 28u;
static const uint UI_LABEL_CONTROL_PALETTE = 29u;
static const uint UI_LABEL_CONTROL_LAYER_BLUE = 30u;
static const uint UI_LABEL_CONTROL_LAYER_ACCENT = 31u;
static const uint UI_LABEL_CONTROL_LAYER_NODES = 32u;
static const uint UI_LABEL_CONTROL_LAYER_LABELS = 33u;
static const uint UI_LABEL_CONTROL_MASTER_MIX = 34u;
static const uint UI_LABEL_CONTROL_MANUAL_ENERGY = 35u;
static const uint UI_LABEL_CONTROL_MANUAL_SWEEP = 36u;
static const uint UI_LABEL_CONTROL_PULSE_RATE = 37u;
static const uint UI_LABEL_CONTROL_SWEEP_RATE = 38u;
static const uint UI_LABEL_CONTROL_BEAT_RATE = 39u;
static const uint UI_LABEL_CONTROL_BEAT_SHARP = 40u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 22;
    if (labelId == 1u) return 32;
    if (labelId == 2u) return 9;
    if (labelId == 3u) return 8;
    if (labelId == 4u) return 7;
    if (labelId == 5u) return 7;
    if (labelId == 6u) return 7;
    if (labelId == 7u) return 9;
    if (labelId == 8u) return 4;
    if (labelId == 9u) return 6;
    if (labelId == 10u) return 5;
    if (labelId == 11u) return 6;
    if (labelId == 12u) return 6;
    if (labelId == 13u) return 10;
    if (labelId == 14u) return 5;
    if (labelId == 15u) return 5;
    if (labelId == 16u) return 4;
    if (labelId == 17u) return 6;
    if (labelId == 18u) return 4;
    if (labelId == 19u) return 9;
    if (labelId == 20u) return 6;
    if (labelId == 21u) return 6;
    if (labelId == 22u) return 5;
    if (labelId == 23u) return 7;
    if (labelId == 24u) return 4;
    if (labelId == 25u) return 16;
    if (labelId == 26u) return 8;
    if (labelId == 27u) return 7;
    if (labelId == 28u) return 12;
    if (labelId == 29u) return 7;
    if (labelId == 30u) return 13;
    if (labelId == 31u) return 15;
    if (labelId == 32u) return 5;
    if (labelId == 33u) return 6;
    if (labelId == 34u) return 10;
    if (labelId == 35u) return 13;
    if (labelId == 36u) return 12;
    if (labelId == 37u) return 10;
    if (labelId == 38u) return 10;
    if (labelId == 39u) return 9;
    if (labelId == 40u) return 14;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[22] = { 84, 79, 80, 79, 71, 82, 65, 80, 72, 73, 67, 32, 79, 80, 69, 82, 65, 84, 73, 79, 78, 83 };
        return characterIndex >= 0 && characterIndex < 22 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[32] = { 84, 69, 82, 82, 65, 73, 78, 32, 47, 32, 83, 73, 71, 78, 65, 76, 32, 47, 32, 67, 85, 69, 32, 65, 85, 84, 72, 79, 82, 73, 84, 89 };
        return characterIndex >= 0 && characterIndex < 32 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[9] = { 65, 85, 84, 72, 79, 82, 73, 84, 89 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[8] = { 67, 85, 69, 32, 77, 79, 68, 69 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[7] = { 84, 69, 82, 82, 65, 73, 78 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[7] = { 68, 69, 78, 83, 73, 84, 89 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[7] = { 80, 65, 76, 69, 84, 84, 69 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[9] = { 76, 65, 89, 69, 82, 32, 77, 73, 88 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[4] = { 66, 76, 85, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[6] = { 65, 67, 67, 69, 78, 84 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[5] = { 78, 79, 68, 69, 83 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[6] = { 76, 65, 66, 69, 76, 83 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 12u) {
        int codes[6] = { 77, 65, 83, 84, 69, 82 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 13u) {
        int codes[10] = { 83, 73, 71, 78, 65, 76, 32, 66, 85, 83 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 14u) {
        int codes[5] = { 80, 85, 76, 83, 69 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 15u) {
        int codes[5] = { 83, 87, 69, 69, 80 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 16u) {
        int codes[4] = { 66, 69, 65, 84 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 17u) {
        int codes[6] = { 77, 65, 78, 85, 65, 76 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 18u) {
        int codes[4] = { 65, 85, 84, 79 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 19u) {
        int codes[9] = { 67, 79, 78, 68, 85, 67, 84, 79, 82 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 20u) {
        int codes[6] = { 83, 85, 82, 86, 69, 89 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 21u) {
        int codes[6] = { 84, 72, 82, 69, 65, 84 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 22u) {
        int codes[5] = { 78, 73, 71, 72, 84 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 23u) {
        int codes[7] = { 77, 73, 78, 73, 77, 65, 76 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 24u) {
        int codes[4] = { 80, 69, 82, 70 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 25u) {
        int codes[16] = { 83, 105, 103, 110, 97, 108, 32, 65, 117, 116, 104, 111, 114, 105, 116, 121 };
        return characterIndex >= 0 && characterIndex < 16 ? codes[characterIndex] : 32;
    }
    if (labelId == 26u) {
        int codes[8] = { 67, 117, 101, 32, 77, 111, 100, 101 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 27u) {
        int codes[7] = { 84, 101, 114, 114, 97, 105, 110 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 28u) {
        int codes[12] = { 78, 111, 100, 101, 32, 68, 101, 110, 115, 105, 116, 121 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 29u) {
        int codes[7] = { 80, 97, 108, 101, 116, 116, 101 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 30u) {
        int codes[13] = { 66, 108, 117, 101, 32, 67, 111, 110, 116, 111, 117, 114, 115 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 31u) {
        int codes[15] = { 65, 99, 99, 101, 110, 116, 32, 67, 111, 110, 116, 111, 117, 114, 115 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 32u) {
        int codes[5] = { 78, 111, 100, 101, 115 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 33u) {
        int codes[6] = { 76, 97, 98, 101, 108, 115 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 34u) {
        int codes[10] = { 77, 97, 115, 116, 101, 114, 32, 77, 105, 120 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 35u) {
        int codes[13] = { 77, 97, 110, 117, 97, 108, 32, 69, 110, 101, 114, 103, 121 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 36u) {
        int codes[12] = { 77, 97, 110, 117, 97, 108, 32, 83, 119, 101, 101, 112 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 37u) {
        int codes[10] = { 80, 117, 108, 115, 101, 32, 82, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 38u) {
        int codes[10] = { 83, 119, 101, 101, 112, 32, 82, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 39u) {
        int codes[9] = { 66, 101, 97, 116, 32, 82, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 40u) {
        int codes[14] = { 66, 101, 97, 116, 32, 83, 104, 97, 114, 112, 110, 101, 115, 115 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
