#ifndef IMPOSSIBLE_PERFORMANCE_DESK_UI_GENERATED_HLSLI
#define IMPOSSIBLE_PERFORMANCE_DESK_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 75325782c080f55aa2aea8acc7f302045523d8291b5621816946911d17e7b1a8
static const uint UI_CONTROL_COUNT = 6u;
static const uint UI_LABEL_COUNT = 10u;
static const uint4 UI_MANIFEST_HASH = uint4(0x75325782u, 0xc080f55au, 0xa2aea8acu, 0xc7f30204u);

static const uint UI_INDEX_PHASE = 0u;
static const float4 UI_RECT_PHASE = float4(0.055, 0.205, 0.295, 0.27);
static const uint UI_INDEX_PRESSURE = 1u;
static const float4 UI_RECT_PRESSURE = float4(0.055, 0.315, 0.295, 0.38);
static const uint UI_INDEX_REINDEX = 2u;
static const float4 UI_RECT_REINDEX = float4(0.055, 0.425, 0.295, 0.49);
static const uint UI_INDEX_STRIKE = 3u;
static const float4 UI_RECT_STRIKE = float4(0.055, 0.535, 0.295, 0.605);
static const uint UI_INDEX_FOCUS = 4u;
static const float4 UI_RECT_FOCUS = float4(0.055, 0.675, 0.168, 0.89);
static const uint UI_INDEX_RUPTURE = 5u;
static const float4 UI_RECT_RUPTURE = float4(0.182, 0.675, 0.295, 0.89);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_MACROS = 1u;
static const uint UI_LABEL_PROGRAM = 2u;
static const uint UI_LABEL_LIVE = 3u;
static const uint UI_LABEL_CONTROL_PHASE = 4u;
static const uint UI_LABEL_CONTROL_PRESSURE = 5u;
static const uint UI_LABEL_CONTROL_REINDEX = 6u;
static const uint UI_LABEL_CONTROL_STRIKE = 7u;
static const uint UI_LABEL_CONTROL_FOCUS = 8u;
static const uint UI_LABEL_CONTROL_RUPTURE = 9u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 44;
    if (labelId == 1u) return 22;
    if (labelId == 2u) return 30;
    if (labelId == 3u) return 64;
    if (labelId == 4u) return 12;
    if (labelId == 5u) return 19;
    if (labelId == 6u) return 16;
    if (labelId == 7u) return 12;
    if (labelId == 8u) return 11;
    if (labelId == 9u) return 17;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[44] = { 73, 78, 68, 69, 88, 32, 79, 70, 32, 73, 77, 80, 79, 83, 83, 73, 66, 76, 69, 32, 82, 79, 79, 77, 83, 32, 47, 32, 80, 69, 82, 70, 79, 82, 77, 65, 78, 67, 69, 32, 68, 69, 83, 75 };
        return characterIndex >= 0 && characterIndex < 44 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[22] = { 76, 73, 86, 69, 32, 83, 84, 82, 85, 67, 84, 85, 82, 65, 76, 32, 77, 65, 67, 82, 79, 83 };
        return characterIndex >= 0 && characterIndex < 22 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[30] = { 65, 83, 80, 69, 67, 84, 32, 67, 79, 82, 82, 69, 67, 84, 32, 80, 82, 79, 71, 82, 65, 77, 32, 77, 79, 78, 73, 84, 79, 82 };
        return characterIndex >= 0 && characterIndex < 30 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[64] = { 76, 73, 86, 69, 32, 67, 79, 78, 84, 82, 79, 76, 32, 66, 85, 83, 32, 47, 32, 70, 79, 67, 85, 83, 32, 43, 32, 82, 85, 80, 84, 85, 82, 69, 32, 43, 32, 80, 82, 69, 83, 83, 85, 82, 69, 32, 43, 32, 82, 69, 73, 78, 68, 69, 88, 32, 43, 32, 83, 84, 82, 73, 75, 69 };
        return characterIndex >= 0 && characterIndex < 64 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[12] = { 83, 104, 97, 114, 101, 100, 32, 80, 104, 97, 115, 101 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[19] = { 83, 116, 114, 117, 99, 116, 117, 114, 97, 108, 32, 80, 114, 101, 115, 115, 117, 114, 101 };
        return characterIndex >= 0 && characterIndex < 19 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[16] = { 75, 105, 110, 101, 116, 105, 99, 32, 82, 101, 45, 105, 110, 100, 101, 120 };
        return characterIndex >= 0 && characterIndex < 16 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[12] = { 80, 108, 97, 116, 101, 32, 83, 116, 114, 105, 107, 101 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[11] = { 83, 116, 97, 103, 101, 32, 70, 111, 99, 117, 115 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[17] = { 82, 117, 112, 116, 117, 114, 101, 32, 68, 105, 114, 101, 99, 116, 105, 111, 110 };
        return characterIndex >= 0 && characterIndex < 17 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
