#ifndef SCIENTIFIC_FONT_STYLE_SAMPLER_UI_GENERATED_HLSLI
#define SCIENTIFIC_FONT_STYLE_SAMPLER_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 25ea0e882f6824bd54119ddada93b243ff81323004194fcc7019539f31fa49ad
static const uint UI_CONTROL_COUNT = 1u;
static const uint UI_LABEL_COUNT = 7u;
static const uint4 UI_MANIFEST_HASH = uint4(0x25ea0e88u, 0x2f6824bdu, 0x54119ddau, 0xda93b243u);

static const uint UI_INDEX_WEIGHT = 0u;
static const float4 UI_RECT_WEIGHT = float4(0.667, 0.867, 0.925, 0.93);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_REGULAR = 1u;
static const uint UI_LABEL_LIGHT = 2u;
static const uint UI_LABEL_CLEAN = 3u;
static const uint UI_LABEL_FULL = 4u;
static const uint UI_LABEL_SPECIMEN = 5u;
static const uint UI_LABEL_CONTROL_WEIGHT = 6u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 22;
    if (labelId == 1u) return 7;
    if (labelId == 2u) return 10;
    if (labelId == 3u) return 10;
    if (labelId == 4u) return 9;
    if (labelId == 5u) return 8;
    if (labelId == 6u) return 26;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[22] = { 83, 67, 73, 69, 78, 84, 73, 70, 73, 67, 65, 32, 87, 69, 73, 71, 72, 84, 32, 76, 65, 66 };
        return characterIndex >= 0 && characterIndex < 22 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[7] = { 82, 69, 71, 85, 76, 65, 82 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[10] = { 76, 73, 71, 72, 84, 32, 69, 68, 71, 69 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[10] = { 67, 76, 69, 65, 78, 32, 69, 68, 71, 69 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[9] = { 70, 85, 76, 76, 32, 69, 68, 71, 69 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[8] = { 65, 97, 48, 57, 46, 87, 47, 43 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[26] = { 67, 117, 115, 116, 111, 109, 32, 82, 101, 103, 117, 108, 97, 114, 32, 69, 100, 103, 101, 32, 87, 101, 105, 103, 104, 116 };
        return characterIndex >= 0 && characterIndex < 26 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
