#ifndef INTERACTIVE_ARCHITECTURAL_LIGHTING_UI_GENERATED_HLSLI
#define INTERACTIVE_ARCHITECTURAL_LIGHTING_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: ae072c853284e2344365cfa54b4d48105cf2ee71aa075794f5daf5c55395719f
static const uint UI_CONTROL_COUNT = 2u;
static const uint UI_LABEL_COUNT = 10u;
static const uint4 UI_MANIFEST_HASH = uint4(0xae072c85u, 0x3284e234u, 0x4365cfa5u, 0x4b4d4810u);

static const uint UI_INDEX_RESET = 0u;
static const float4 UI_RECT_RESET = float4(0.79, 0.032, 0.875, 0.078);
static const uint UI_INDEX_RESET_ALL = 1u;
static const float4 UI_RECT_RESET_ALL = float4(0.882, 0.032, 0.97, 0.078);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_SUN = 1u;
static const uint UI_LABEL_KEY = 2u;
static const uint UI_LABEL_FILL = 3u;
static const uint UI_LABEL_CANOPY = 4u;
static const uint UI_LABEL_PLAN = 5u;
static const uint UI_LABEL_RESET = 6u;
static const uint UI_LABEL_RESET_ALL = 7u;
static const uint UI_LABEL_CONTROL_RESET = 8u;
static const uint UI_LABEL_CONTROL_RESET_ALL = 9u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 22;
    if (labelId == 1u) return 3;
    if (labelId == 2u) return 3;
    if (labelId == 3u) return 4;
    if (labelId == 4u) return 6;
    if (labelId == 5u) return 38;
    if (labelId == 6u) return 3;
    if (labelId == 7u) return 7;
    if (labelId == 8u) return 14;
    if (labelId == 9u) return 9;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[22] = { 65, 82, 67, 72, 73, 84, 69, 67, 84, 85, 82, 65, 76, 32, 76, 73, 71, 72, 84, 73, 78, 71 };
        return characterIndex >= 0 && characterIndex < 22 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[3] = { 83, 85, 78 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[3] = { 75, 69, 89 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[4] = { 70, 73, 76, 76 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[6] = { 67, 65, 78, 79, 80, 89 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[38] = { 76, 73, 86, 69, 32, 76, 73, 71, 72, 84, 32, 66, 85, 70, 70, 69, 82, 32, 47, 32, 84, 79, 80, 45, 68, 79, 87, 78, 32, 83, 73, 84, 69, 32, 80, 76, 65, 78 };
        return characterIndex >= 0 && characterIndex < 38 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[3] = { 82, 83, 84 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[7] = { 82, 83, 84, 32, 65, 76, 76 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[14] = { 82, 101, 115, 101, 116, 32, 83, 101, 108, 101, 99, 116, 101, 100 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[9] = { 82, 101, 115, 101, 116, 32, 65, 108, 108 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
