#include "../_shared/ui/sui_v2.hlsli"
#include "_ui.generated.hlsli"
#include "../_shared/ui/sui_generated_text.hlsli"
#include "types.hlsli"
StructuredBuffer<LightRecord> Lights:register(t0);StructuredBuffer<LightControlState> Controls:register(t1);RWTexture2D<float4> OutputUAV:register(u0);
SuiTheme lightTheme(){SuiTheme t=suiMonochromeTheme();t.background=float3(.006,.007,.009);t.panel=float3(.012,.013,.016);t.panelRaised=float3(.020,.021,.025);t.control=float3(.030,.032,.038);t.controlHover=float3(.050,.053,.060);t.controlDown=float3(.82,.60,.24);t.text=float3(.88,.90,.92);t.muted=float3(.42,.45,.49);t.border=float3(.12,.13,.15);t.accent=float3(.82,.60,.24);t.axisY=float3(.66,.68,.71);return t;}
float2 worldToUi(float2 p){return lcWorldToCanvas(p);}
float seg(float2 p,float2 a,float2 b){float2 pa=p-a,ba=b-a;float h=saturate(dot(pa,ba)/max(dot(ba,ba),1e-5));return length(pa-ba*h);}
[numthreads(8,8,1)]void main(uint3 id:SV_DispatchThreadID){if(id.x>=(uint)_Resolution.x||id.y>=(uint)_Resolution.y)return;SuiContext c=suiContext(id.xy,_Resolution.xy);SuiTheme theme=lightTheme();float3 col=theme.background;suiComposite(col,float3(.018,.019,.022),suiGridPx(c,24,.42));suiPanel(col,c,theme,float4(.012,.018,.988,.982),false);suiComposite(col,theme.panelRaised,suiFillRect(c,float4(.012,.018,.988,.092)));suiComposite(col,theme.accent,suiFillRect(c,float4(.012,.018,.016,.092)));suiComposite(col,theme.text,suiLabelText(c,float2(.032,.041),suiTextStyle(1.25,.15),UI_LABEL_TITLE));
 float4 plan=LC_EDIT_RECT;suiPanel(col,c,theme,plan,true);float2 w=lcCanvasToWorld(c.uv);float grid=1-smoothstep(.465,.495,min(abs(frac(w)-.5).x,abs(frac(w)-.5).y));col+=grid*float3(.035,.037,.041);float2 siteC=worldToUi(float2(0,0))*_Resolution.xy;float2 siteH=float2(1.0,14.0/18.0)*(LC_EDIT_RECT.zw-LC_EDIT_RECT.xy)*_Resolution.xy*.5;float2 q=abs(((float2)id.xy+.5)-siteC)-siteH;float site=length(max(q,0))+min(max(q.x,q.y),0);col+=(1-smoothstep(.8,2.0,abs(site)))*theme.border;
 [loop]for(uint j=1u;j<8u;j++){LightRecord l=Lights[j];if(l.enabled<.5)continue;float2 cc=worldToUi(l.position.xz);float radius=5.0+sqrt(max(l.intensity,0))*2.5;float3 lc=lerp(float3(.56,.58,.61),theme.accent,saturate(l.intensity/8));suiComposite(col,lc,suiRingPx(c,cc,radius,1.25));float2 end=worldToUi(l.position.xz+normalize(l.direction.xz+float2(.001,.001))*1.2);float ray=1-smoothstep(1,2.3,seg((float2)id.xy+.5,cc*_Resolution.xy,end*_Resolution.xy));col+=ray*lc*.8;}
 float2 sunHandle=Controls[0].position,keyHandle=Controls[1].position,fillHandle=Controls[2].position,canopyHandle=Controls[3].position;float2 center=worldToUi(float2(0,0));float sunRay=1-smoothstep(1,2.5,seg((float2)id.xy+.5,center*_Resolution.xy,sunHandle*_Resolution.xy));col+=sunRay*theme.accent;suiComposite(col,lcSelected(1)?theme.accent:theme.axisY,suiRingPx(c,sunHandle,lcSelected(1)?11:9,1.7));suiComposite(col,lcSelected(2)?theme.accent:theme.axisY,suiRingPx(c,keyHandle,lcSelected(2)?10:7,1.5));suiComposite(col,lcSelected(3)?theme.accent:theme.axisY,suiRingPx(c,fillHandle,lcSelected(3)?10:7,1.5));suiComposite(col,lcSelected(4)?theme.accent:theme.axisY,suiRingPx(c,canopyHandle,lcSelected(4)?10:7,1.5));
 suiComposite(col,lcSelected(1)?theme.accent:theme.axisY,suiLabelText(c,sunHandle+float2(12,-16)*c.invResolution,suiTextStyle(.72,0),UI_LABEL_SUN));suiComposite(col,lcSelected(2)?theme.accent:theme.axisY,suiLabelText(c,keyHandle+float2(12,-14)*c.invResolution,suiTextStyle(.72,0),UI_LABEL_KEY));suiComposite(col,lcSelected(3)?theme.accent:theme.axisY,suiLabelText(c,fillHandle+float2(12,14)*c.invResolution,suiTextStyle(.72,0),UI_LABEL_FILL));suiComposite(col,lcSelected(4)?theme.accent:theme.axisY,suiLabelText(c,canopyHandle+float2(12,-14)*c.invResolution,suiTextStyle(.72,0),UI_LABEL_CANOPY));
 suiPanel(col,c,theme,UI_RECT_RESET,false);suiPanel(col,c,theme,UI_RECT_RESET_ALL,false);suiComposite(col,theme.text,suiLabelText(c,UI_RECT_RESET.xy+float2(8,10)*c.invResolution,suiBodyStyle(),UI_LABEL_RESET));suiComposite(col,theme.text,suiLabelText(c,UI_RECT_RESET_ALL.xy+float2(8,10)*c.invResolution,suiBodyStyle(),UI_LABEL_RESET_ALL));
 suiComposite(col,theme.border,suiStrokeRect(c,plan,1));suiComposite(col,theme.muted,suiLabelText(c,float2(plan.x+.01,plan.w-.02),suiTextStyle(.68,0),UI_LABEL_PLAN));OutputUAV[id.xy]=float4(saturate(col),1);}
