#ifndef ZAHA_GESTURE_LOFT_LABORATORY_UI_GENERATED_HLSLI
#define ZAHA_GESTURE_LOFT_LABORATORY_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 79bc0e67441e058655ccdb2f39a1c644d08547f68b055e6f32c9c7055cd89f6e
static const uint UI_CONTROL_COUNT = 2u;
static const uint UI_LABEL_COUNT = 6u;
static const uint4 UI_MANIFEST_HASH = uint4(0x79bc0e67u, 0x441e0586u, 0x55ccdb2fu, 0x39a1c644u);

static const uint UI_INDEX_MORPH_FIELD = 0u;
static const float4 UI_RECT_MORPH_FIELD = float4(0.03, 0.15, 0.48, 0.91);
static const uint UI_INDEX_TORSION_FIELD = 1u;
static const float4 UI_RECT_TORSION_FIELD = float4(0.52, 0.15, 0.97, 0.91);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_SUBTITLE = 1u;
static const uint UI_LABEL_MORPH = 2u;
static const uint UI_LABEL_TORSION = 3u;
static const uint UI_LABEL_CONTROL_MORPH_FIELD = 4u;
static const uint UI_LABEL_CONTROL_TORSION_FIELD = 5u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 23;
    if (labelId == 1u) return 45;
    if (labelId == 2u) return 13;
    if (labelId == 3u) return 13;
    if (labelId == 4u) return 19;
    if (labelId == 5u) return 13;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[23] = { 71, 69, 83, 84, 85, 82, 69, 32, 76, 79, 70, 84, 32, 76, 65, 66, 79, 82, 65, 84, 79, 82, 89 };
        return characterIndex >= 0 && characterIndex < 23 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[45] = { 84, 87, 79, 32, 83, 80, 65, 84, 73, 65, 76, 32, 70, 73, 69, 76, 68, 83, 32, 47, 32, 79, 78, 69, 32, 67, 79, 78, 84, 73, 78, 85, 79, 85, 83, 32, 83, 72, 69, 76, 76, 32, 68, 78, 65 };
        return characterIndex >= 0 && characterIndex < 45 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[13] = { 77, 65, 83, 83, 73, 78, 71, 32, 70, 73, 69, 76, 68 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[13] = { 84, 79, 82, 83, 73, 79, 78, 32, 70, 73, 69, 76, 68 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[19] = { 77, 97, 115, 115, 105, 110, 103, 32, 77, 111, 114, 112, 104, 32, 70, 105, 101, 108, 100 };
        return characterIndex >= 0 && characterIndex < 19 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[13] = { 84, 111, 114, 115, 105, 111, 110, 32, 70, 105, 101, 108, 100 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
