#ifndef INTERACTIVE_BUILDING_MASSING_UI_GENERATED_HLSLI
#define INTERACTIVE_BUILDING_MASSING_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 55691e6a88d5e831ce2b982d6f605dd60d5e5d29a86a7801059993e8bf2bb53a
static const uint UI_CONTROL_COUNT = 6u;
static const uint UI_LABEL_COUNT = 14u;
static const uint4 UI_MANIFEST_HASH = uint4(0x55691e6au, 0x88d5e831u, 0xce2b982du, 0x6f605dd6u);

static const uint UI_INDEX_MOVE = 0u;
static const float4 UI_RECT_MOVE = float4(0.43, 0.032, 0.515, 0.078);
static const uint UI_INDEX_ROTATE = 1u;
static const float4 UI_RECT_ROTATE = float4(0.522, 0.032, 0.615, 0.078);
static const uint UI_INDEX_SNAP = 2u;
static const float4 UI_RECT_SNAP = float4(0.622, 0.032, 0.695, 0.078);
static const uint UI_INDEX_FIT = 3u;
static const float4 UI_RECT_FIT = float4(0.702, 0.032, 0.765, 0.078);
static const uint UI_INDEX_RESET = 4u;
static const float4 UI_RECT_RESET = float4(0.772, 0.032, 0.855, 0.078);
static const uint UI_INDEX_RESET_ALL = 5u;
static const float4 UI_RECT_RESET_ALL = float4(0.862, 0.032, 0.97, 0.078);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_PLAN = 1u;
static const uint UI_LABEL_MOVE = 2u;
static const uint UI_LABEL_ROTATE = 3u;
static const uint UI_LABEL_SNAP = 4u;
static const uint UI_LABEL_FIT = 5u;
static const uint UI_LABEL_RESET = 6u;
static const uint UI_LABEL_RESET_ALL = 7u;
static const uint UI_LABEL_CONTROL_MOVE = 8u;
static const uint UI_LABEL_CONTROL_ROTATE = 9u;
static const uint UI_LABEL_CONTROL_SNAP = 10u;
static const uint UI_LABEL_CONTROL_FIT = 11u;
static const uint UI_LABEL_CONTROL_RESET = 12u;
static const uint UI_LABEL_CONTROL_RESET_ALL = 13u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 17;
    if (labelId == 1u) return 30;
    if (labelId == 2u) return 4;
    if (labelId == 3u) return 6;
    if (labelId == 4u) return 4;
    if (labelId == 5u) return 3;
    if (labelId == 6u) return 3;
    if (labelId == 7u) return 7;
    if (labelId == 8u) return 9;
    if (labelId == 9u) return 11;
    if (labelId == 10u) return 4;
    if (labelId == 11u) return 8;
    if (labelId == 12u) return 14;
    if (labelId == 13u) return 9;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[17] = { 77, 65, 83, 83, 73, 78, 71, 32, 87, 79, 82, 75, 66, 69, 78, 67, 72 };
        return characterIndex >= 0 && characterIndex < 17 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[30] = { 76, 73, 86, 69, 32, 66, 76, 85, 69, 80, 82, 73, 78, 84, 32, 47, 32, 49, 56, 77, 32, 83, 73, 84, 69, 32, 71, 82, 73, 68 };
        return characterIndex >= 0 && characterIndex < 30 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[4] = { 77, 79, 86, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[6] = { 82, 79, 84, 65, 84, 69 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[4] = { 83, 78, 65, 80 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[3] = { 70, 73, 84 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[3] = { 82, 83, 84 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[7] = { 82, 83, 84, 32, 65, 76, 76 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[9] = { 77, 111, 118, 101, 32, 84, 111, 111, 108 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[11] = { 82, 111, 116, 97, 116, 101, 32, 84, 111, 111, 108 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[4] = { 83, 110, 97, 112 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[8] = { 70, 105, 116, 32, 80, 108, 97, 110 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 12u) {
        int codes[14] = { 82, 101, 115, 101, 116, 32, 83, 101, 108, 101, 99, 116, 101, 100 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    if (labelId == 13u) {
        int codes[9] = { 82, 101, 115, 101, 116, 32, 65, 108, 108 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
