#ifndef SPLINE_DESK_UI_GENERATED_HLSLI
#define SPLINE_DESK_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: d32b9e6e132d19eb37c9ffff566360ded1634f8e3d9a148f48400a2bd2717687
static const uint UI_CONTROL_COUNT = 4u;
static const uint UI_LABEL_COUNT = 4u;
static const uint4 UI_MANIFEST_HASH = uint4(0xd32b9e6eu, 0x132d19ebu, 0x37c9ffffu, 0x566360deu);

static const uint UI_INDEX_TOOL = 0u;
static const float4 UI_RECT_TOOL = float4(0.016, 0.038, 0.15, 0.086);
static const uint UI_INDEX_TANGENT = 1u;
static const float4 UI_RECT_TANGENT = float4(0.166, 0.038, 0.276, 0.086);
static const uint UI_INDEX_CLOSE = 2u;
static const float4 UI_RECT_CLOSE = float4(0.286, 0.038, 0.372, 0.086);
static const uint UI_INDEX_DELETE = 3u;
static const float4 UI_RECT_DELETE = float4(0.382, 0.038, 0.47, 0.086);

static const uint UI_LABEL_CONTROL_TOOL = 0u;
static const uint UI_LABEL_CONTROL_TANGENT = 1u;
static const uint UI_LABEL_CONTROL_CLOSE = 2u;
static const uint UI_LABEL_CONTROL_DELETE = 3u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 4;
    if (labelId == 1u) return 13;
    if (labelId == 2u) return 12;
    if (labelId == 3u) return 15;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[4] = { 84, 111, 111, 108 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[13] = { 67, 121, 99, 108, 101, 32, 84, 97, 110, 103, 101, 110, 116 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[12] = { 79, 112, 101, 110, 32, 47, 32, 67, 108, 111, 115, 101 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[15] = { 68, 101, 108, 101, 116, 101, 32, 83, 101, 108, 101, 99, 116, 101, 100 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
