#ifndef SCIENTIFIC_SPLINE_EDITOR_UI_GENERATED_HLSLI
#define SCIENTIFIC_SPLINE_EDITOR_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: bd13e13d5b2d44564e3ab27f7df647431d903d609e676945f53de86ed89ff81f
static const uint UI_CONTROL_COUNT = 5u;
static const uint UI_LABEL_COUNT = 12u;
static const uint4 UI_MANIFEST_HASH = uint4(0xbd13e13du, 0x5b2d4456u, 0x4e3ab27fu, 0x7df64743u);

static const uint UI_INDEX_SELECT = 0u;
static const float4 UI_RECT_SELECT = float4(0.219, 0.026, 0.315, 0.096);
static const uint UI_INDEX_PEN = 1u;
static const float4 UI_RECT_PEN = float4(0.325, 0.026, 0.392, 0.096);
static const uint UI_INDEX_TANGENT = 2u;
static const float4 UI_RECT_TANGENT = float4(0.404, 0.026, 0.521, 0.096);
static const uint UI_INDEX_CLOSE = 3u;
static const float4 UI_RECT_CLOSE = float4(0.533, 0.026, 0.615, 0.096);
static const uint UI_INDEX_DELETE = 4u;
static const float4 UI_RECT_DELETE = float4(0.627, 0.026, 0.723, 0.096);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_SPLINE = 1u;
static const uint UI_LABEL_SELECT = 2u;
static const uint UI_LABEL_PEN = 3u;
static const uint UI_LABEL_TANGENT = 4u;
static const uint UI_LABEL_CLOSE = 5u;
static const uint UI_LABEL_DELETE = 6u;
static const uint UI_LABEL_CONTROL_SELECT = 7u;
static const uint UI_LABEL_CONTROL_PEN = 8u;
static const uint UI_LABEL_CONTROL_TANGENT = 9u;
static const uint UI_LABEL_CONTROL_CLOSE = 10u;
static const uint UI_LABEL_CONTROL_DELETE = 11u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 13;
    if (labelId == 1u) return 6;
    if (labelId == 2u) return 6;
    if (labelId == 3u) return 3;
    if (labelId == 4u) return 7;
    if (labelId == 5u) return 5;
    if (labelId == 6u) return 6;
    if (labelId == 7u) return 11;
    if (labelId == 8u) return 8;
    if (labelId == 9u) return 13;
    if (labelId == 10u) return 12;
    if (labelId == 11u) return 15;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[13] = { 83, 80, 76, 73, 78, 69, 32, 69, 68, 73, 84, 79, 82 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[6] = { 83, 80, 76, 73, 78, 69 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[6] = { 83, 69, 76, 69, 67, 84 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[3] = { 80, 69, 78 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[7] = { 84, 65, 78, 71, 69, 78, 84 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[5] = { 67, 76, 79, 83, 69 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[6] = { 68, 69, 76, 69, 84, 69 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[11] = { 83, 101, 108, 101, 99, 116, 32, 84, 111, 111, 108 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[8] = { 80, 101, 110, 32, 84, 111, 111, 108 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[13] = { 67, 121, 99, 108, 101, 32, 84, 97, 110, 103, 101, 110, 116 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[12] = { 79, 112, 101, 110, 32, 47, 32, 67, 108, 111, 115, 101 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[15] = { 68, 101, 108, 101, 116, 101, 32, 83, 101, 108, 101, 99, 116, 101, 100 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
