#ifndef AXIOM_06___POLYRHYTHM_RACK_UI_GENERATED_HLSLI
#define AXIOM_06___POLYRHYTHM_RACK_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 144beb8e32783a197ff465cd5ab3d6c6961059dd08a35223d6c7ff7769f5b23c
static const uint UI_CONTROL_COUNT = 3u;
static const uint UI_LABEL_COUNT = 3u;
static const uint4 UI_MANIFEST_HASH = uint4(0x144beb8eu, 0x32783a19u, 0x7ff465cdu, 0x5ab3d6c6u);

static const uint UI_INDEX_TRANSPORT_RUN = 0u;
static const float4 UI_RECT_TRANSPORT_RUN = float4(0.045, 0.865, 0.125, 0.952);
static const uint UI_INDEX_RESET_PHASE = 1u;
static const float4 UI_RECT_RESET_PHASE = float4(0.135, 0.865, 0.215, 0.952);
static const uint UI_INDEX_SCRUB_PHASE = 2u;
static const float4 UI_RECT_SCRUB_PHASE = float4(0.245, 0.865, 0.945, 0.952);

static const uint UI_LABEL_CONTROL_TRANSPORT_RUN = 0u;
static const uint UI_LABEL_CONTROL_RESET_PHASE = 1u;
static const uint UI_LABEL_CONTROL_SCRUB_PHASE = 2u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 3;
    if (labelId == 1u) return 5;
    if (labelId == 2u) return 5;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[3] = { 82, 117, 110 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[5] = { 82, 101, 115, 101, 116 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[5] = { 80, 104, 97, 115, 101 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
