#ifndef ZAHA_SURFACE_CLONER_AND_APERTURE_FIELD_UI_GENERATED_HLSLI
#define ZAHA_SURFACE_CLONER_AND_APERTURE_FIELD_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: e91f896690d57d2d2bd36505a0fe27ffd135b35270b8746f50762308b1fb8916
static const uint UI_CONTROL_COUNT = 2u;
static const uint UI_LABEL_COUNT = 5u;
static const uint4 UI_MANIFEST_HASH = uint4(0xe91f8966u, 0x90d57d2du, 0x2bd36505u, 0xa0fe27ffu);

static const uint UI_INDEX_ATTRACTOR_FIELD = 0u;
static const float4 UI_RECT_ATTRACTOR_FIELD = float4(0.035, 0.155, 0.495, 0.905);
static const uint UI_INDEX_APERTURE_FIELD = 1u;
static const float4 UI_RECT_APERTURE_FIELD = float4(0.505, 0.155, 0.965, 0.905);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_SUBTITLE = 1u;
static const uint UI_LABEL_MAP = 2u;
static const uint UI_LABEL_CONTROL_ATTRACTOR_FIELD = 3u;
static const uint UI_LABEL_CONTROL_APERTURE_FIELD = 4u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 32;
    if (labelId == 1u) return 47;
    if (labelId == 2u) return 16;
    if (labelId == 3u) return 17;
    if (labelId == 4u) return 14;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[32] = { 83, 85, 82, 70, 65, 67, 69, 32, 67, 76, 79, 78, 69, 82, 32, 47, 32, 65, 80, 69, 82, 84, 85, 82, 69, 32, 87, 69, 65, 86, 69, 82 };
        return characterIndex >= 0 && characterIndex < 32 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[47] = { 82, 73, 66, 83, 32, 43, 32, 67, 69, 76, 76, 83, 32, 43, 32, 84, 69, 82, 82, 65, 67, 69, 83, 32, 47, 32, 85, 78, 87, 82, 65, 80, 80, 69, 68, 32, 76, 73, 86, 69, 32, 70, 65, 67, 65, 68, 69 };
        return characterIndex >= 0 && characterIndex < 47 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[16] = { 67, 76, 79, 78, 69, 82, 32, 70, 73, 69, 76, 68, 32, 77, 65, 80 };
        return characterIndex >= 0 && characterIndex < 16 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[17] = { 83, 117, 114, 102, 97, 99, 101, 32, 65, 116, 116, 114, 97, 99, 116, 111, 114 };
        return characterIndex >= 0 && characterIndex < 17 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[14] = { 65, 112, 101, 114, 116, 117, 114, 101, 32, 70, 105, 101, 108, 100 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
