#ifndef LIVING_ROOM_FURNISHINGS_PLAN_EDITOR_UI_GENERATED_HLSLI
#define LIVING_ROOM_FURNISHINGS_PLAN_EDITOR_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: cc7c55199df16b3646079347108b1f7c00a303078b8848d9480e93214842be8f
static const uint UI_CONTROL_COUNT = 6u;
static const uint UI_LABEL_COUNT = 13u;
static const uint4 UI_MANIFEST_HASH = uint4(0xcc7c5519u, 0x9df16b36u, 0x46079347u, 0x108b1f7cu);

static const uint UI_INDEX_MOVE = 0u;
static const float4 UI_RECT_MOVE = float4(0.025, 0.025, 0.135, 0.105);
static const uint UI_INDEX_ROTATE = 1u;
static const float4 UI_RECT_ROTATE = float4(0.145, 0.025, 0.265, 0.105);
static const uint UI_INDEX_SNAP = 2u;
static const float4 UI_RECT_SNAP = float4(0.285, 0.025, 0.385, 0.105);
static const uint UI_INDEX_FIT = 3u;
static const float4 UI_RECT_FIT = float4(0.415, 0.025, 0.505, 0.105);
static const uint UI_INDEX_RESET = 4u;
static const float4 UI_RECT_RESET = float4(0.705, 0.025, 0.825, 0.105);
static const uint UI_INDEX_RESET_ALL = 5u;
static const float4 UI_RECT_RESET_ALL = float4(0.835, 0.025, 0.975, 0.105);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_MOVE = 1u;
static const uint UI_LABEL_ROTATE = 2u;
static const uint UI_LABEL_SNAP = 3u;
static const uint UI_LABEL_RESET = 4u;
static const uint UI_LABEL_RESET_ALL = 5u;
static const uint UI_LABEL_FIT = 6u;
static const uint UI_LABEL_CONTROL_MOVE = 7u;
static const uint UI_LABEL_CONTROL_ROTATE = 8u;
static const uint UI_LABEL_CONTROL_SNAP = 9u;
static const uint UI_LABEL_CONTROL_FIT = 10u;
static const uint UI_LABEL_CONTROL_RESET = 11u;
static const uint UI_LABEL_CONTROL_RESET_ALL = 12u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 16;
    if (labelId == 1u) return 4;
    if (labelId == 2u) return 6;
    if (labelId == 3u) return 4;
    if (labelId == 4u) return 5;
    if (labelId == 5u) return 9;
    if (labelId == 6u) return 3;
    if (labelId == 7u) return 9;
    if (labelId == 8u) return 11;
    if (labelId == 9u) return 4;
    if (labelId == 10u) return 8;
    if (labelId == 11u) return 14;
    if (labelId == 12u) return 9;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[16] = { 70, 85, 82, 78, 73, 83, 72, 73, 78, 71, 83, 32, 80, 76, 65, 78 };
        return characterIndex >= 0 && characterIndex < 16 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[4] = { 77, 79, 86, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[6] = { 82, 79, 84, 65, 84, 69 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[4] = { 83, 78, 65, 80 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[5] = { 82, 69, 83, 69, 84 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[9] = { 82, 69, 83, 69, 84, 32, 65, 76, 76 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[3] = { 70, 73, 84 };
        return characterIndex >= 0 && characterIndex < 3 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[9] = { 77, 111, 118, 101, 32, 84, 111, 111, 108 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[11] = { 82, 111, 116, 97, 116, 101, 32, 84, 111, 111, 108 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[4] = { 83, 110, 97, 112 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[8] = { 70, 105, 116, 32, 80, 108, 97, 110 };
        return characterIndex >= 0 && characterIndex < 8 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[14] = { 82, 101, 115, 101, 116, 32, 83, 101, 108, 101, 99, 116, 101, 100 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    if (labelId == 12u) {
        int codes[9] = { 82, 101, 115, 101, 116, 32, 65, 108, 108 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
