#ifndef AU_DECK_UI_GENERATED_HLSLI
#define AU_DECK_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: abd82cf12d467d159a13f987d0b10bce1ba8cb47da7f7c9af8d0209e559144ae
static const uint UI_CONTROL_COUNT = 3u;
static const uint UI_LABEL_COUNT = 3u;
static const uint4 UI_MANIFEST_HASH = uint4(0xabd82cf1u, 0x2d467d15u, 0x9a13f987u, 0xd0b10bceu);

static const uint UI_INDEX_PAD_FIELD = 0u;
static const float4 UI_RECT_PAD_FIELD = float4(0.04, 0.2, 0.32, 0.76);
static const uint UI_INDEX_PAD_RELIEF = 1u;
static const float4 UI_RECT_PAD_RELIEF = float4(0.355, 0.2, 0.635, 0.76);
static const uint UI_INDEX_PAD_PRINT = 2u;
static const float4 UI_RECT_PAD_PRINT = float4(0.67, 0.2, 0.95, 0.76);

static const uint UI_LABEL_CONTROL_PAD_FIELD = 0u;
static const uint UI_LABEL_CONTROL_PAD_RELIEF = 1u;
static const uint UI_LABEL_CONTROL_PAD_PRINT = 2u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 11;
    if (labelId == 1u) return 12;
    if (labelId == 2u) return 11;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[11] = { 70, 105, 101, 108, 100, 32, 77, 97, 99, 114, 111 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[12] = { 82, 101, 108, 105, 101, 102, 32, 77, 97, 99, 114, 111 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[11] = { 80, 114, 105, 110, 116, 32, 77, 97, 99, 114, 111 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
