#ifndef STRATA_COMPOSITION_DESK_UI_GENERATED_HLSLI
#define STRATA_COMPOSITION_DESK_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 085ca2d470a4df538f14d8a06cb002963a5c0733287a5fede79a7c1ae1595a1a
static const uint UI_CONTROL_COUNT = 4u;
static const uint UI_LABEL_COUNT = 4u;
static const uint4 UI_MANIFEST_HASH = uint4(0x085ca2d4u, 0x70a4df53u, 0x8f14d8a0u, 0x6cb00296u);

static const uint UI_INDEX_BLOB_MIX = 0u;
static const float4 UI_RECT_BLOB_MIX = float4(0.055, 0.65, 0.475, 0.735);
static const uint UI_INDEX_MARBLE_MIX = 1u;
static const float4 UI_RECT_MARBLE_MIX = float4(0.525, 0.65, 0.945, 0.735);
static const uint UI_INDEX_WIRE_MIX = 2u;
static const float4 UI_RECT_WIRE_MIX = float4(0.055, 0.815, 0.475, 0.9);
static const uint UI_INDEX_MARKS_MIX = 3u;
static const float4 UI_RECT_MARKS_MIX = float4(0.525, 0.815, 0.945, 0.9);

static const uint UI_LABEL_CONTROL_BLOB_MIX = 0u;
static const uint UI_LABEL_CONTROL_MARBLE_MIX = 1u;
static const uint UI_LABEL_CONTROL_WIRE_MIX = 2u;
static const uint UI_LABEL_CONTROL_MARKS_MIX = 3u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 15;
    if (labelId == 1u) return 12;
    if (labelId == 2u) return 10;
    if (labelId == 3u) return 13;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[15] = { 83, 99, 117, 108, 112, 116, 117, 114, 101, 32, 80, 108, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[12] = { 77, 97, 114, 98, 108, 101, 32, 80, 108, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[10] = { 87, 105, 114, 101, 32, 80, 108, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[13] = { 71, 114, 97, 112, 104, 105, 99, 32, 77, 97, 114, 107, 115 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
