#ifndef STRATA_COMPOSITION_DESK_UI_GENERATED_HLSLI
#define STRATA_COMPOSITION_DESK_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 7a9f70d061432cdacb91b95b21153de16d53b503eeb06becff1f50a92db417dd
static const uint UI_CONTROL_COUNT = 13u;
static const uint UI_LABEL_COUNT = 36u;
static const uint4 UI_MANIFEST_HASH = uint4(0x7a9f70d0u, 0x61432cdau, 0xcb91b95bu, 0x21153de1u);

static const uint UI_INDEX_MASTER_SEED = 0u;
static const float4 UI_RECT_MASTER_SEED = float4(0.06, 0.245, 0.455, 0.305);
static const uint UI_INDEX_PALETTE_VARIANT = 1u;
static const float4 UI_RECT_PALETTE_VARIANT = float4(0.06, 0.395, 0.455, 0.455);
static const uint UI_INDEX_MELT_MACRO = 2u;
static const float4 UI_RECT_MELT_MACRO = float4(0.06, 0.565, 0.245, 0.625);
static const uint UI_INDEX_TWIST_MACRO = 3u;
static const float4 UI_RECT_TWIST_MACRO = float4(0.27, 0.565, 0.455, 0.625);
static const uint UI_INDEX_MARBLE_WARP_MACRO = 4u;
static const float4 UI_RECT_MARBLE_WARP_MACRO = float4(0.06, 0.705, 0.455, 0.765);
static const uint UI_INDEX_SPREAD_MACRO = 5u;
static const float4 UI_RECT_SPREAD_MACRO = float4(0.06, 0.85, 0.245, 0.91);
static const uint UI_INDEX_WIRE_SCALE_MACRO = 6u;
static const float4 UI_RECT_WIRE_SCALE_MACRO = float4(0.27, 0.85, 0.455, 0.91);
static const uint UI_INDEX_BLOB_MIX = 7u;
static const float4 UI_RECT_BLOB_MIX = float4(0.55, 0.25, 0.92, 0.31);
static const uint UI_INDEX_MARBLE_MIX = 8u;
static const float4 UI_RECT_MARBLE_MIX = float4(0.55, 0.38, 0.92, 0.44);
static const uint UI_INDEX_WIRE_MIX = 9u;
static const float4 UI_RECT_WIRE_MIX = float4(0.55, 0.51, 0.92, 0.57);
static const uint UI_INDEX_MARKS_MIX = 10u;
static const float4 UI_RECT_MARKS_MIX = float4(0.55, 0.64, 0.92, 0.7);
static const uint UI_INDEX_FEATURE_ENABLED = 11u;
static const float4 UI_RECT_FEATURE_ENABLED = float4(0.55, 0.825, 0.65, 0.9);
static const uint UI_INDEX_FEATURE_GAIN = 12u;
static const float4 UI_RECT_FEATURE_GAIN = float4(0.685, 0.825, 0.92, 0.9);

static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_SUBTITLE = 1u;
static const uint UI_LABEL_COMPOSITION = 2u;
static const uint UI_LABEL_SEED = 3u;
static const uint UI_LABEL_PALETTE = 4u;
static const uint UI_LABEL_ATELIER = 5u;
static const uint UI_LABEL_CHROME = 6u;
static const uint UI_LABEL_POSTER = 7u;
static const uint UI_LABEL_CAGE = 8u;
static const uint UI_LABEL_MONO = 9u;
static const uint UI_LABEL_DISTORTION = 10u;
static const uint UI_LABEL_MELT = 11u;
static const uint UI_LABEL_TWIST = 12u;
static const uint UI_LABEL_MARBLE = 13u;
static const uint UI_LABEL_SPREAD = 14u;
static const uint UI_LABEL_WIRE_SCALE = 15u;
static const uint UI_LABEL_PLATE_MIX = 16u;
static const uint UI_LABEL_SCULPTURE = 17u;
static const uint UI_LABEL_MARBLE_PLATE = 18u;
static const uint UI_LABEL_WIRE = 19u;
static const uint UI_LABEL_MARKS = 20u;
static const uint UI_LABEL_FEATURES = 21u;
static const uint UI_LABEL_CORNERS = 22u;
static const uint UI_LABEL_CONTROL_MASTER_SEED = 23u;
static const uint UI_LABEL_CONTROL_PALETTE_VARIANT = 24u;
static const uint UI_LABEL_CONTROL_MELT_MACRO = 25u;
static const uint UI_LABEL_CONTROL_TWIST_MACRO = 26u;
static const uint UI_LABEL_CONTROL_MARBLE_WARP_MACRO = 27u;
static const uint UI_LABEL_CONTROL_SPREAD_MACRO = 28u;
static const uint UI_LABEL_CONTROL_WIRE_SCALE_MACRO = 29u;
static const uint UI_LABEL_CONTROL_BLOB_MIX = 30u;
static const uint UI_LABEL_CONTROL_MARBLE_MIX = 31u;
static const uint UI_LABEL_CONTROL_WIRE_MIX = 32u;
static const uint UI_LABEL_CONTROL_MARKS_MIX = 33u;
static const uint UI_LABEL_CONTROL_FEATURE_ENABLED = 34u;
static const uint UI_LABEL_CONTROL_FEATURE_GAIN = 35u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 23;
    if (labelId == 1u) return 34;
    if (labelId == 2u) return 11;
    if (labelId == 3u) return 11;
    if (labelId == 4u) return 7;
    if (labelId == 5u) return 7;
    if (labelId == 6u) return 6;
    if (labelId == 7u) return 6;
    if (labelId == 8u) return 4;
    if (labelId == 9u) return 4;
    if (labelId == 10u) return 10;
    if (labelId == 11u) return 4;
    if (labelId == 12u) return 5;
    if (labelId == 13u) return 11;
    if (labelId == 14u) return 6;
    if (labelId == 15u) return 10;
    if (labelId == 16u) return 9;
    if (labelId == 17u) return 9;
    if (labelId == 18u) return 6;
    if (labelId == 19u) return 4;
    if (labelId == 20u) return 5;
    if (labelId == 21u) return 14;
    if (labelId == 22u) return 7;
    if (labelId == 23u) return 11;
    if (labelId == 24u) return 7;
    if (labelId == 25u) return 4;
    if (labelId == 26u) return 5;
    if (labelId == 27u) return 11;
    if (labelId == 28u) return 6;
    if (labelId == 29u) return 10;
    if (labelId == 30u) return 15;
    if (labelId == 31u) return 12;
    if (labelId == 32u) return 10;
    if (labelId == 33u) return 13;
    if (labelId == 34u) return 14;
    if (labelId == 35u) return 11;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[23] = { 83, 84, 82, 65, 84, 65, 32, 67, 79, 77, 80, 79, 83, 73, 84, 73, 79, 78, 32, 68, 69, 83, 75 };
        return characterIndex >= 0 && characterIndex < 23 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[34] = { 80, 76, 65, 84, 69, 32, 83, 89, 83, 84, 69, 77, 32, 47, 32, 80, 82, 69, 77, 85, 76, 84, 73, 80, 76, 73, 69, 68, 32, 65, 76, 80, 72, 65 };
        return characterIndex >= 0 && characterIndex < 34 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[11] = { 67, 79, 77, 80, 79, 83, 73, 84, 73, 79, 78 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[11] = { 77, 65, 83, 84, 69, 82, 32, 83, 69, 69, 68 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[7] = { 80, 65, 76, 69, 84, 84, 69 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[7] = { 65, 84, 69, 76, 73, 69, 82 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[6] = { 67, 72, 82, 79, 77, 69 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[6] = { 80, 79, 83, 84, 69, 82 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 8u) {
        int codes[4] = { 67, 65, 71, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 9u) {
        int codes[4] = { 77, 79, 78, 79 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 10u) {
        int codes[10] = { 68, 73, 83, 84, 79, 82, 84, 73, 79, 78 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 11u) {
        int codes[4] = { 77, 69, 76, 84 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 12u) {
        int codes[5] = { 84, 87, 73, 83, 84 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 13u) {
        int codes[11] = { 77, 65, 82, 66, 76, 69, 32, 87, 65, 82, 80 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 14u) {
        int codes[6] = { 83, 80, 82, 69, 65, 68 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 15u) {
        int codes[10] = { 87, 73, 82, 69, 32, 83, 67, 65, 76, 69 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 16u) {
        int codes[9] = { 80, 76, 65, 84, 69, 32, 77, 73, 88 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 17u) {
        int codes[9] = { 83, 67, 85, 76, 80, 84, 85, 82, 69 };
        return characterIndex >= 0 && characterIndex < 9 ? codes[characterIndex] : 32;
    }
    if (labelId == 18u) {
        int codes[6] = { 77, 65, 82, 66, 76, 69 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 19u) {
        int codes[4] = { 87, 73, 82, 69 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 20u) {
        int codes[5] = { 77, 65, 82, 75, 83 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 21u) {
        int codes[14] = { 70, 69, 65, 84, 85, 82, 69, 32, 84, 72, 82, 69, 65, 68 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    if (labelId == 22u) {
        int codes[7] = { 67, 79, 82, 78, 69, 82, 83 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 23u) {
        int codes[11] = { 77, 97, 115, 116, 101, 114, 32, 83, 101, 101, 100 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 24u) {
        int codes[7] = { 80, 97, 108, 101, 116, 116, 101 };
        return characterIndex >= 0 && characterIndex < 7 ? codes[characterIndex] : 32;
    }
    if (labelId == 25u) {
        int codes[4] = { 77, 101, 108, 116 };
        return characterIndex >= 0 && characterIndex < 4 ? codes[characterIndex] : 32;
    }
    if (labelId == 26u) {
        int codes[5] = { 84, 119, 105, 115, 116 };
        return characterIndex >= 0 && characterIndex < 5 ? codes[characterIndex] : 32;
    }
    if (labelId == 27u) {
        int codes[11] = { 77, 97, 114, 98, 108, 101, 32, 87, 97, 114, 112 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 28u) {
        int codes[6] = { 83, 112, 114, 101, 97, 100 };
        return characterIndex >= 0 && characterIndex < 6 ? codes[characterIndex] : 32;
    }
    if (labelId == 29u) {
        int codes[10] = { 87, 105, 114, 101, 32, 83, 99, 97, 108, 101 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 30u) {
        int codes[15] = { 83, 99, 117, 108, 112, 116, 117, 114, 101, 32, 80, 108, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 15 ? codes[characterIndex] : 32;
    }
    if (labelId == 31u) {
        int codes[12] = { 77, 97, 114, 98, 108, 101, 32, 80, 108, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 12 ? codes[characterIndex] : 32;
    }
    if (labelId == 32u) {
        int codes[10] = { 87, 105, 114, 101, 32, 80, 108, 97, 116, 101 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 33u) {
        int codes[13] = { 71, 114, 97, 112, 104, 105, 99, 32, 77, 97, 114, 107, 115 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    if (labelId == 34u) {
        int codes[14] = { 70, 101, 97, 116, 117, 114, 101, 32, 84, 104, 114, 101, 97, 100 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    if (labelId == 35u) {
        int codes[11] = { 84, 104, 114, 101, 97, 100, 32, 71, 97, 105, 110 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
