#ifndef GIZMO_DESK_UI_GENERATED_HLSLI
#define GIZMO_DESK_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: bed8b4a6c53422c356f8738ba37109bb019d7d32858f2de0f61276dab330d488
static const uint UI_CONTROL_COUNT = 2u;
static const uint UI_LABEL_COUNT = 2u;
static const uint4 UI_MANIFEST_HASH = uint4(0xbed8b4a6u, 0xc53422c3u, 0x56f8738bu, 0xa37109bbu);

static const uint UI_INDEX_MODE = 0u;
static const float4 UI_RECT_MODE = float4(0.016, 0.038, 0.23, 0.086);
static const uint UI_INDEX_LOCAL = 1u;
static const float4 UI_RECT_LOCAL = float4(0.246, 0.038, 0.36, 0.086);

static const uint UI_LABEL_CONTROL_MODE = 0u;
static const uint UI_LABEL_CONTROL_LOCAL = 1u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 14;
    if (labelId == 1u) return 13;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[14] = { 84, 114, 97, 110, 115, 102, 111, 114, 109, 32, 77, 111, 100, 101 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[13] = { 87, 111, 114, 108, 100, 32, 47, 32, 76, 111, 99, 97, 108 };
        return characterIndex >= 0 && characterIndex < 13 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
