#ifndef PD___PERFORMANCE_EXCHANGE_UI_GENERATED_HLSLI
#define PD___PERFORMANCE_EXCHANGE_UI_GENERATED_HLSLI

// Generated by tools/module-ui.ps1 from manifest.yaml. Do not hand edit.
// manifest-sha256: 5ea63fad611d38e6d21a5d93f2722c5fa41313682666e536f09f84ea7aa4c279
static const uint UI_CONTROL_COUNT = 0u;
static const uint UI_LABEL_COUNT = 8u;
static const uint4 UI_MANIFEST_HASH = uint4(0x5ea63fadu, 0x611d38e6u, 0xd21a5d93u, 0xf2722c5fu);


static const uint UI_LABEL_TITLE = 0u;
static const uint UI_LABEL_STAGE = 1u;
static const uint UI_LABEL_FLOW = 2u;
static const uint UI_LABEL_PRESSURE = 3u;
static const uint UI_LABEL_MARGIN = 4u;
static const uint UI_LABEL_ACTIVE = 5u;
static const uint UI_LABEL_MACRO = 6u;
static const uint UI_LABEL_INSTRUCTION = 7u;

int uiLabelLength(uint labelId) {
    if (labelId == 0u) return 20;
    if (labelId == 1u) return 28;
    if (labelId == 2u) return 26;
    if (labelId == 3u) return 14;
    if (labelId == 4u) return 11;
    if (labelId == 5u) return 11;
    if (labelId == 6u) return 10;
    if (labelId == 7u) return 31;
    return 0;
}

int uiLabelCode(uint labelId, int characterIndex) {
    if (labelId == 0u) {
        int codes[20] = { 80, 69, 82, 70, 79, 82, 77, 65, 78, 67, 69, 32, 69, 88, 67, 72, 65, 78, 71, 69 };
        return characterIndex >= 0 && characterIndex < 20 ? codes[characterIndex] : 32;
    }
    if (labelId == 1u) {
        int codes[28] = { 76, 69, 68, 71, 69, 82, 32, 86, 79, 76, 85, 77, 69, 32, 47, 32, 68, 73, 82, 69, 67, 84, 32, 70, 79, 67, 85, 83 };
        return characterIndex >= 0 && characterIndex < 28 ? codes[characterIndex] : 32;
    }
    if (labelId == 2u) {
        int codes[26] = { 68, 73, 86, 69, 82, 71, 69, 78, 67, 69, 32, 47, 32, 67, 65, 77, 69, 82, 65, 32, 70, 79, 76, 76, 79, 87 };
        return characterIndex >= 0 && characterIndex < 26 ? codes[characterIndex] : 32;
    }
    if (labelId == 3u) {
        int codes[14] = { 80, 82, 73, 78, 84, 32, 80, 82, 69, 83, 83, 85, 82, 69 };
        return characterIndex >= 0 && characterIndex < 14 ? codes[characterIndex] : 32;
    }
    if (labelId == 4u) {
        int codes[11] = { 77, 65, 82, 71, 73, 78, 32, 67, 65, 76, 76 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 5u) {
        int codes[11] = { 65, 67, 84, 73, 86, 69, 32, 68, 69, 66, 84 };
        return characterIndex >= 0 && characterIndex < 11 ? codes[characterIndex] : 32;
    }
    if (labelId == 6u) {
        int codes[10] = { 77, 65, 67, 82, 79, 32, 77, 65, 83, 83 };
        return characterIndex >= 0 && characterIndex < 10 ? codes[characterIndex] : 32;
    }
    if (labelId == 7u) {
        int codes[31] = { 68, 82, 65, 71, 32, 83, 84, 65, 71, 69, 32, 79, 82, 32, 82, 73, 71, 72, 84, 45, 72, 65, 78, 68, 32, 70, 73, 69, 76, 68, 83 };
        return characterIndex >= 0 && characterIndex < 31 ? codes[characterIndex] : 32;
    }
    return 32;
}

#endif
