// Generated by tools/phage_labels.py. Edit the generator, not this file.
#ifndef PH_LABELS_HLSLI
#define PH_LABELS_HLSLI
static const uint PH_LBL_CH[152]={80,72,65,71,69,32,47,32,77,79,84,73,79,78,32,67,79,78,84,82,79,76,66,79,68,89,67,65,80,83,73,68,76,69,71,72,69,73,71,72,84,89,65,87,83,80,73,78,83,72,69,65,84,72,76,73,70,84,83,87,73,78,71,80,76,65,78,69,76,69,86,65,84,73,79,78,80,82,79,71,82,65,77,77,69,82,82,69,83,84,32,72,79,76,68,83,84,82,69,84,67,72,84,65,82,71,69,84,77,68,69,71,77,65,78,85,65,76,68,69,77,79,70,82,79,78,84,32,69,76,69,86,65,84,73,79,78,80,76,65,78,32,40,76,73,86,69,41,82,69,83,84};
static const uint2 PH_LBL_RANGE[23]={uint2(0,22),uint2(22,4),uint2(26,6),uint2(32,3),uint2(35,6),uint2(41,3),uint2(44,4),uint2(48,6),uint2(54,4),uint2(58,5),uint2(63,4),uint2(67,9),uint2(76,10),uint2(86,9),uint2(95,7),uint2(102,6),uint2(108,1),uint2(109,3),uint2(112,6),uint2(118,4),uint2(122,15),uint2(137,11),uint2(148,4)};
float phLabelWidth(uint id,float s){return (float)PH_LBL_RANGE[id].y*SUI3_ADVANCE*s;}
float phLabel(float2 P,float2 anchor,float s,uint id){
 uint2 r=PH_LBL_RANGE[id];if(sui3RunMiss(P,anchor,s,(int)r.y))return 0;
 int k=(int)floor((P.x-anchor.x)/(SUI3_ADVANCE*s));if(k<0||k>=(int)r.y)return 0;
 float cov=sui3Glyph(P,anchor+float2((float)k*SUI3_ADVANCE*s,0),s,(int)PH_LBL_CH[r.x+(uint)k]);
 if(k>0)cov=max(cov,sui3Glyph(P,anchor+float2((float)(k-1)*SUI3_ADVANCE*s,0),s,(int)PH_LBL_CH[r.x+(uint)k-1]));
 return cov;}
#endif
